//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIControl.h>

@class UIImageView, UILabel;
@protocol AMSliderProgressChangedDelegate;

@interface AMVerticalSliderView : UIControl
{
    id <AMSliderProgressChangedDelegate> _mDelegate;
    double _progress;
    UIImageView *_mThumbImageView;
    UILabel *_mValueLabel;
}

@property(retain, nonatomic) UILabel *mValueLabel; // @synthesize mValueLabel=_mValueLabel;
@property(retain, nonatomic) UIImageView *mThumbImageView; // @synthesize mThumbImageView=_mThumbImageView;
@property(nonatomic) double progress; // @synthesize progress=_progress;
@property(nonatomic) __weak id <AMSliderProgressChangedDelegate> mDelegate; // @synthesize mDelegate=_mDelegate;
- (void).cxx_destruct;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)drawRect:(struct CGRect)arg1;
- (void)sliderValueChanged;
- (void)panGestureAction:(id)arg1;
- (id)init;

@end

