//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface AppManagerModule : NSObject
{
}

+ (id)routerHandle_AppManagerModule_setkParams:(id)arg1 callback:(CDUnknownBlockType)arg2;
+ (id)routerHandle_AppManagerModule_getkParams:(id)arg1 callback:(CDUnknownBlockType)arg2;
+ (id)routerHandle_AppManagerModule_clearkParams:(id)arg1 callback:(CDUnknownBlockType)arg2;
+ (id)routerHandle_AppManagerModule_isLaunched:(id)arg1 callback:(CDUnknownBlockType)arg2;
+ (id)routerHandle_AppManagerModule_getPartnerStr:(id)arg1 callback:(CDUnknownBlockType)arg2;
+ (id)routerHandle_AppManagerModule_checkVersion:(id)arg1 callback:(CDUnknownBlockType)arg2;
+ (id)routerHandle_AppManagerModule_getAPP_DOWNLOAD_URL:(id)arg1 callback:(CDUnknownBlockType)arg2;
+ (id)routerHandle_AppManagerModule_getMainFunctionIdWithFunIdKey:(id)arg1 callback:(CDUnknownBlockType)arg2;
+ (id)routerHandle_AppManagerModule_getABTestConfig:(id)arg1 callback:(CDUnknownBlockType)arg2;
+ (id)routerHandle_AppManagerModule_runAppWithTarget_action:(id)arg1 callback:(CDUnknownBlockType)arg2;
+ (id)routerHandle_AppManagerModule_setProgressTarget_progressAction:(id)arg1 callback:(CDUnknownBlockType)arg2;
+ (id)routerHandle_AppManagerModule_getPagePushControlConfigDict:(id)arg1 callback:(CDUnknownBlockType)arg2;
+ (id)routerHandle_AppManagerModule_getServerConfig:(id)arg1 callback:(CDUnknownBlockType)arg2;
+ (id)routerHandle_AppManagerModule_targetIphoneDebug:(id)arg1 callback:(CDUnknownBlockType)arg2;

@end

