//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <JDDBaseModule/JDModel.h>

@class AddRiskCheckInfoModel, NSString;

@interface AppointModel : JDModel
{
    _Bool _flag;
    _Bool _isSuccess;
    NSString *_link;
    NSString *_title;
    NSString *_msg;
    NSString *_content;
    NSString *_guide;
    NSString *_addCartTitle;
    NSString *_addCartContent;
    AddRiskCheckInfoModel *_addRiskCheckInfo;
}

@property(retain, nonatomic) AddRiskCheckInfoModel *addRiskCheckInfo; // @synthesize addRiskCheckInfo=_addRiskCheckInfo;
@property(nonatomic) _Bool isSuccess; // @synthesize isSuccess=_isSuccess;
@property(copy, nonatomic) NSString *addCartContent; // @synthesize addCartContent=_addCartContent;
@property(copy, nonatomic) NSString *addCartTitle; // @synthesize addCartTitle=_addCartTitle;
@property(copy, nonatomic) NSString *guide; // @synthesize guide=_guide;
@property(copy, nonatomic) NSString *content; // @synthesize content=_content;
@property(copy, nonatomic) NSString *msg; // @synthesize msg=_msg;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) _Bool flag; // @synthesize flag=_flag;
@property(copy, nonatomic) NSString *link; // @synthesize link=_link;
- (void).cxx_destruct;
- (void)setDataWithDic:(id)arg1;
- (void)dealloc;

@end

