//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SecKillBaseViewController.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class BrandKillExposureManager, BrandKillModel, JDImageView, NSArray, NSString, SSSScrollDepthManage, SecKillObserverModel, SecKillRequestManager, UIColor, UITableView;

@interface BrandKillViewController : SecKillBaseViewController <UITableViewDataSource, UITableViewDelegate>
{
    _Bool _notFirstRecord;
    NSString *_brandId;
    BrandKillModel *_brandKillModel;
    NSArray *_tableViewData;
    UIColor *_frameColor;
    UITableView *_tableView;
    JDImageView *_bannerView;
    SecKillRequestManager *_requestManager;
    SecKillObserverModel *_observerModel;
    SSSScrollDepthManage *_depthTrack;
    NSString *_innerLink;
    BrandKillExposureManager *_exposureManager;
}

@property(nonatomic) _Bool notFirstRecord; // @synthesize notFirstRecord=_notFirstRecord;
@property(retain, nonatomic) BrandKillExposureManager *exposureManager; // @synthesize exposureManager=_exposureManager;
@property(copy, nonatomic) NSString *innerLink; // @synthesize innerLink=_innerLink;
@property(retain, nonatomic) SSSScrollDepthManage *depthTrack; // @synthesize depthTrack=_depthTrack;
@property(retain, nonatomic) SecKillObserverModel *observerModel; // @synthesize observerModel=_observerModel;
@property(retain, nonatomic) SecKillRequestManager *requestManager; // @synthesize requestManager=_requestManager;
@property(retain, nonatomic) JDImageView *bannerView; // @synthesize bannerView=_bannerView;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) UIColor *frameColor; // @synthesize frameColor=_frameColor;
@property(retain, nonatomic) NSArray *tableViewData; // @synthesize tableViewData=_tableViewData;
@property(retain, nonatomic) BrandKillModel *brandKillModel; // @synthesize brandKillModel=_brandKillModel;
@property(copy, nonatomic) NSString *brandId; // @synthesize brandId=_brandId;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)timerFired;
- (void)stopTimer;
- (void)startTimer;
- (id)tableViewDataWithBrandKillModel:(id)arg1;
- (void)reloadData;
- (void)reconnect;
- (void)applicationWillResignActive;
- (void)applicationDidBecomeActive;
- (void)constructTableView;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithParam:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

