//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface CategoryMTAInterface : NSObject
{
}

+ (void)recordAbnormalWithErrorType:(int)arg1 functionID:(id)arg2 params:(id)arg3 url:(id)arg4 error:(id)arg5 response:(id)arg6;
+ (void)setPageLevel:(int)arg1 pageClassName:(id)arg2 pageEventID:(id)arg3 otherID:(id)arg4 pageParam:(id)arg5;
+ (void)jdmta_event_click:(id)arg1 PageParam:(id)arg2 EventID:(id)arg3 EventName:(id)arg4 ParamValue:(id)arg5 NextPageName:(id)arg6 shopID:(id)arg7 pageID:(id)arg8 params:(id)arg9;
+ (void)jdmta_event_click:(id)arg1 PageParam:(id)arg2 EventID:(id)arg3 EventName:(id)arg4 ParamValue:(id)arg5 NextPageName:(id)arg6 shopID:(id)arg7 pageID:(id)arg8;

@end

