//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class CategoryNewPromotionView, UIPanGestureRecognizer;

@protocol CategoryNewPromotionViewDelegate <NSObject>

@optional
- (void)overlapCardView:(CategoryNewPromotionView *)arg1 panGesture:(UIPanGestureRecognizer *)arg2;
- (void)overlapCardView:(CategoryNewPromotionView *)arg1 didSelectAtIndex:(long long)arg2;
@end

