//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface CategoryThirdModel : NSObject
{
    _Bool _isMerger;
    _Bool _isIndividual;
    _Bool _isCatalogMiddlePage;
    _Bool _isExposureMta;
    int _cid;
    int _level1Cid;
    int _level2Cid;
    int _level3Cid;
    int _extendFlag;
    int _originCid;
    NSString *_name;
    NSString *_icon;
    NSString *_path;
    NSArray *_extendCategory;
    long long _virtualFlag;
    NSString *_searchKey;
    NSArray *_filterConfigKeys;
    NSString *_shopId;
    NSString *_action;
    NSString *_destination;
    NSArray *_labelArray;
    NSArray *_expandPropertysArray;
    long long _type;
    double _haveIconLabelHeight;
    NSString *_desc;
    NSString *_title;
    NSString *_algorithmType;
    long long _isRealid;
}

@property(nonatomic) long long isRealid; // @synthesize isRealid=_isRealid;
@property(copy, nonatomic) NSString *algorithmType; // @synthesize algorithmType=_algorithmType;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(copy, nonatomic) NSString *desc; // @synthesize desc=_desc;
@property(nonatomic) _Bool isExposureMta; // @synthesize isExposureMta=_isExposureMta;
@property(nonatomic) double haveIconLabelHeight; // @synthesize haveIconLabelHeight=_haveIconLabelHeight;
@property(nonatomic) long long type; // @synthesize type=_type;
@property(nonatomic) _Bool isCatalogMiddlePage; // @synthesize isCatalogMiddlePage=_isCatalogMiddlePage;
@property(nonatomic) _Bool isIndividual; // @synthesize isIndividual=_isIndividual;
@property(nonatomic) _Bool isMerger; // @synthesize isMerger=_isMerger;
@property(retain, nonatomic) NSArray *expandPropertysArray; // @synthesize expandPropertysArray=_expandPropertysArray;
@property(retain, nonatomic) NSArray *labelArray; // @synthesize labelArray=_labelArray;
@property(nonatomic) int originCid; // @synthesize originCid=_originCid;
@property(copy, nonatomic) NSString *destination; // @synthesize destination=_destination;
@property(copy, nonatomic) NSString *action; // @synthesize action=_action;
@property(copy, nonatomic) NSString *shopId; // @synthesize shopId=_shopId;
@property(retain, nonatomic) NSArray *filterConfigKeys; // @synthesize filterConfigKeys=_filterConfigKeys;
@property(copy, nonatomic) NSString *searchKey; // @synthesize searchKey=_searchKey;
@property(nonatomic) long long virtualFlag; // @synthesize virtualFlag=_virtualFlag;
@property(retain, nonatomic) NSArray *extendCategory; // @synthesize extendCategory=_extendCategory;
@property(nonatomic) int extendFlag; // @synthesize extendFlag=_extendFlag;
@property(nonatomic) int level3Cid; // @synthesize level3Cid=_level3Cid;
@property(nonatomic) int level2Cid; // @synthesize level2Cid=_level2Cid;
@property(nonatomic) int level1Cid; // @synthesize level1Cid=_level1Cid;
@property(copy, nonatomic) NSString *path; // @synthesize path=_path;
@property(copy, nonatomic) NSString *icon; // @synthesize icon=_icon;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(nonatomic) int cid; // @synthesize cid=_cid;
- (void).cxx_destruct;

@end

