//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class BJChoiceCouponModel;

@interface CCCouponCToastCell : UICollectionViewCell
{
    _Bool isHorizontal;
    BJChoiceCouponModel *_couponModel;
}

@property(retain, nonatomic) BJChoiceCouponModel *couponModel; // @synthesize couponModel=_couponModel;
- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)arg1;
- (void)updateViewWithItem:(id)arg1 horizontal:(_Bool)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

