//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class BJCCNvgTabModel, JDButton, JDImageView;

@interface CCCouponCenterTabBtnView : UIView
{
    _Bool _selected;
    _Bool _redPointFlag;
    _Bool _shouldOnlyReportCouponMarketBottomTab;
    _Bool _lastSelectedState;
    _Bool _showRedPoint;
    CDUnknownBlockType _tabBarBtnAction;
    BJCCNvgTabModel *_tabModel;
    JDButton *_btn;
    JDImageView *_selectedImageView;
    JDImageView *_unSelectedImageView;
    JDImageView *_redPointImageView;
}

@property(nonatomic) _Bool showRedPoint; // @synthesize showRedPoint=_showRedPoint;
@property(retain, nonatomic) JDImageView *redPointImageView; // @synthesize redPointImageView=_redPointImageView;
@property(retain, nonatomic) JDImageView *unSelectedImageView; // @synthesize unSelectedImageView=_unSelectedImageView;
@property(retain, nonatomic) JDImageView *selectedImageView; // @synthesize selectedImageView=_selectedImageView;
@property(retain, nonatomic) JDButton *btn; // @synthesize btn=_btn;
@property(nonatomic) _Bool lastSelectedState; // @synthesize lastSelectedState=_lastSelectedState;
@property(nonatomic) _Bool shouldOnlyReportCouponMarketBottomTab; // @synthesize shouldOnlyReportCouponMarketBottomTab=_shouldOnlyReportCouponMarketBottomTab;
@property(nonatomic) _Bool redPointFlag; // @synthesize redPointFlag=_redPointFlag;
@property(nonatomic) _Bool selected; // @synthesize selected=_selected;
@property(retain, nonatomic) BJCCNvgTabModel *tabModel; // @synthesize tabModel=_tabModel;
@property(copy, nonatomic) CDUnknownBlockType tabBarBtnAction; // @synthesize tabBarBtnAction=_tabBarBtnAction;
- (void).cxx_destruct;
- (void)jdmtaEvent;
- (void)btnTaped;
- (void)updateRedPoint:(_Bool)arg1;
- (id)defaultIconUnSelected;
- (id)defaultIconSelected;
- (id)initWithFrame:(struct CGRect)arg1;

@end

