//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JDImageView.h"

@class BJCCActivityItemModel;

@interface CCMarketResPosTotalView : JDImageView
{
    BJCCActivityItemModel *_marketResPosModel;
    CDUnknownBlockType _resetHightBlock;
    JDImageView *_imageView;
}

@property(retain, nonatomic) JDImageView *imageView; // @synthesize imageView=_imageView;
@property(copy, nonatomic) CDUnknownBlockType resetHightBlock; // @synthesize resetHightBlock=_resetHightBlock;
@property(retain, nonatomic) BJCCActivityItemModel *marketResPosModel; // @synthesize marketResPosModel=_marketResPosModel;
- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;

@end

