//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "COCheckoutAbstractApi.h"

@class NSString;

@interface COCheckoutGetAddressByPinApi : COCheckoutAbstractApi
{
    _Bool _isNeedPickAddressList;
    NSString *_address;
    long long _pageId;
}

@property(nonatomic) long long pageId; // @synthesize pageId=_pageId;
@property(copy, nonatomic) NSString *address; // @synthesize address=_address;
@property(nonatomic) _Bool isNeedPickAddressList; // @synthesize isNeedPickAddressList=_isNeedPickAddressList;
- (void).cxx_destruct;
- (id)memoryKeys;
- (id)requestParams;
- (id)parseWithKeyValues:(id)arg1;
- (id)functionId;

@end

