//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <JDDBaseModule/JDModel.h>

@class COCheckoutGetGiftCardRM, COCheckoutNotifyRM;

@interface COCheckoutCardRM : JDModel
{
    long long _maxSelectNum;
    COCheckoutGetGiftCardRM *_cards;
    COCheckoutNotifyRM *_notifyInfos;
}

@property(retain, nonatomic) COCheckoutNotifyRM *notifyInfos; // @synthesize notifyInfos=_notifyInfos;
@property(retain, nonatomic) COCheckoutGetGiftCardRM *cards; // @synthesize cards=_cards;
@property(nonatomic) long long maxSelectNum; // @synthesize maxSelectNum=_maxSelectNum;
- (void).cxx_destruct;
- (void)setDataWithDic:(id)arg1;

@end

