//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface COCheckoutVenderShowSkuMarkStyleModel : NSObject
{
    NSString *_backColor;
    NSString *_markStr;
    NSString *_markStrColor;
    long long _height;
    long long _width;
    double _transparency;
}

@property(readonly, nonatomic) double transparency; // @synthesize transparency=_transparency;
@property(readonly, nonatomic) long long width; // @synthesize width=_width;
@property(readonly, nonatomic) long long height; // @synthesize height=_height;
@property(readonly, copy, nonatomic) NSString *markStrColor; // @synthesize markStrColor=_markStrColor;
@property(readonly, copy, nonatomic) NSString *markStr; // @synthesize markStr=_markStr;
@property(readonly, copy, nonatomic) NSString *backColor; // @synthesize backColor=_backColor;
- (void).cxx_destruct;

@end

