//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSNumber, NSString;

@interface COCheckoutMainShipmentMidSmallSaveInfo : NSObject
{
    NSNumber *_promiseType;
    NSObject *_promiseSendPay;
    NSString *_promiseDate;
    NSString *_promiseTimeRange;
    NSString *_promiseTagType;
    NSString *_codeTimeId;
    NSNumber *_midSmallBatchId;
    NSNumber *_cutOrder;
    NSString *_midSmallInstallDate;
}

@property(copy, nonatomic) NSString *midSmallInstallDate; // @synthesize midSmallInstallDate=_midSmallInstallDate;
@property(retain, nonatomic) NSNumber *cutOrder; // @synthesize cutOrder=_cutOrder;
@property(retain, nonatomic) NSNumber *midSmallBatchId; // @synthesize midSmallBatchId=_midSmallBatchId;
@property(copy, nonatomic) NSString *codeTimeId; // @synthesize codeTimeId=_codeTimeId;
@property(copy, nonatomic) NSString *promiseTagType; // @synthesize promiseTagType=_promiseTagType;
@property(copy, nonatomic) NSString *promiseTimeRange; // @synthesize promiseTimeRange=_promiseTimeRange;
@property(copy, nonatomic) NSString *promiseDate; // @synthesize promiseDate=_promiseDate;
@property(retain, nonatomic) NSObject *promiseSendPay; // @synthesize promiseSendPay=_promiseSendPay;
@property(retain, nonatomic) NSNumber *promiseType; // @synthesize promiseType=_promiseType;
- (void).cxx_destruct;

@end

