//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "COCheckoutMainAbstractVM.h"

@class NSAttributedString, NSString;

@interface COCheckoutMainInputVM : COCheckoutMainAbstractVM
{
    unsigned long long _inputType;
    NSAttributedString *_attributedPlaceholder;
    NSString *_mobileText;
    NSString *_editingStr;
    CDUnknownBlockType _inputNoteDidChangeTextBlock;
    CDUnknownBlockType _inputNoteDidBeginTextBlock;
    NSString *_promptStr;
}

@property(copy, nonatomic) NSString *promptStr; // @synthesize promptStr=_promptStr;
@property(copy, nonatomic) CDUnknownBlockType inputNoteDidBeginTextBlock; // @synthesize inputNoteDidBeginTextBlock=_inputNoteDidBeginTextBlock;
@property(copy, nonatomic) CDUnknownBlockType inputNoteDidChangeTextBlock; // @synthesize inputNoteDidChangeTextBlock=_inputNoteDidChangeTextBlock;
@property(copy, nonatomic) NSString *editingStr; // @synthesize editingStr=_editingStr;
@property(copy, nonatomic) NSString *mobileText; // @synthesize mobileText=_mobileText;
@property(copy, nonatomic) NSAttributedString *attributedPlaceholder; // @synthesize attributedPlaceholder=_attributedPlaceholder;
@property(nonatomic) unsigned long long inputType; // @synthesize inputType=_inputType;
- (void).cxx_destruct;
- (unsigned long long)type;
- (id)init;

@end

