//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class COCheckoutMainImmediatelyBuyCountDownTimeVM, COCheckoutMainWeakTimer, UILabel;

@interface COCheckoutMainImmediatelyBuyCountDownTimeView : UIView
{
    COCheckoutMainImmediatelyBuyCountDownTimeVM *_model;
    double _viewWidth;
    long long _type;
    UILabel *_hourLabel;
    UILabel *_minuteLabel;
    UILabel *_secondLabel;
    UILabel *_titleLabel;
    UILabel *_colon1Label;
    UILabel *_colon2Label;
    UIView *_bgView;
    long long _currentTime;
    COCheckoutMainWeakTimer *_timer;
}

@property(retain, nonatomic) COCheckoutMainWeakTimer *timer; // @synthesize timer=_timer;
@property(nonatomic) long long currentTime; // @synthesize currentTime=_currentTime;
@property(retain, nonatomic) UIView *bgView; // @synthesize bgView=_bgView;
@property(retain, nonatomic) UILabel *colon2Label; // @synthesize colon2Label=_colon2Label;
@property(retain, nonatomic) UILabel *colon1Label; // @synthesize colon1Label=_colon1Label;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UILabel *secondLabel; // @synthesize secondLabel=_secondLabel;
@property(retain, nonatomic) UILabel *minuteLabel; // @synthesize minuteLabel=_minuteLabel;
@property(retain, nonatomic) UILabel *hourLabel; // @synthesize hourLabel=_hourLabel;
@property(nonatomic) long long type; // @synthesize type=_type;
@property(nonatomic) double viewWidth; // @synthesize viewWidth=_viewWidth;
@property(retain, nonatomic) COCheckoutMainImmediatelyBuyCountDownTimeVM *model; // @synthesize model=_model;
- (void).cxx_destruct;
- (void)stopTimer;
- (void)coundDown;
- (void)setHourText:(long long)arg1 minuteText:(long long)arg2 secondText:(long long)arg3;
- (void)refreshTimerView;
- (void)updateUi;
- (id)initWithType:(long long)arg1;
- (void)dealloc;

@end

