//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class COCheckoutInternationalAuthModel, JDStoreNetwork;

@interface COCheckoutInternationalAuthManager : NSObject
{
    JDStoreNetwork *_net;
    COCheckoutInternationalAuthModel *_authModel;
    CDUnknownBlockType _authCallBack;
}

+ (id)sharedInternationalAuthManager;
@property(copy, nonatomic) CDUnknownBlockType authCallBack; // @synthesize authCallBack=_authCallBack;
@property(retain, nonatomic) COCheckoutInternationalAuthModel *authModel; // @synthesize authModel=_authModel;
@property(retain, nonatomic) JDStoreNetwork *net; // @synthesize net=_net;
- (void).cxx_destruct;
- (void)setAuthResultWithParams:(id)arg1;
- (void)goAuthInternationalWithCallBack:(CDUnknownBlockType)arg1;

@end

