//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "COCheckoutMainAbstractVM.h"

@class COCheckoutMainVenderPagingToastVM, NSAttributedString, NSNumber, NSString;

@interface COCheckoutMainVenderPagingVM : COCheckoutMainAbstractVM
{
    _Bool _swithFlag;
    NSString *_title;
    NSString *_freight;
    NSAttributedString *_descriptionText;
    NSNumber *_packageId;
    NSString *_venderId;
    COCheckoutMainVenderPagingToastVM *_toastVM;
    NSNumber *_charge;
}

@property(retain, nonatomic) NSNumber *charge; // @synthesize charge=_charge;
@property(retain, nonatomic) COCheckoutMainVenderPagingToastVM *toastVM; // @synthesize toastVM=_toastVM;
@property(copy, nonatomic) NSString *venderId; // @synthesize venderId=_venderId;
@property(retain, nonatomic) NSNumber *packageId; // @synthesize packageId=_packageId;
@property(nonatomic) _Bool swithFlag; // @synthesize swithFlag=_swithFlag;
@property(copy, nonatomic) NSAttributedString *descriptionText; // @synthesize descriptionText=_descriptionText;
@property(copy, nonatomic) NSString *freight; // @synthesize freight=_freight;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (unsigned long long)type;

@end

