//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QAnnotationView.h"

@class COCheckoutSiteMapCalloutView;

@interface COCheckoutSiteMapAnnotationView : QAnnotationView
{
    CDUnknownBlockType _selectedCalloutViewCallBack;
    COCheckoutSiteMapCalloutView *_calloutView;
}

@property(retain, nonatomic) COCheckoutSiteMapCalloutView *calloutView; // @synthesize calloutView=_calloutView;
@property(copy, nonatomic) CDUnknownBlockType selectedCalloutViewCallBack; // @synthesize selectedCalloutViewCallBack=_selectedCalloutViewCallBack;
- (void).cxx_destruct;
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setAnnotation:(id)arg1;

@end

