//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <JDDBaseModule/JDModel.h>

@class COCheckoutGoodsViewModel, NSString;

@interface COCheckoutToastGoods : JDModel
{
    COCheckoutGoodsViewModel *_goodsViewModel;
    NSString *_title;
    NSString *_priceText;
    NSString *_unitsText;
    NSString *_purchaseLimitText;
    NSString *_giftText;
}

@property(copy, nonatomic) NSString *giftText; // @synthesize giftText=_giftText;
@property(copy, nonatomic) NSString *purchaseLimitText; // @synthesize purchaseLimitText=_purchaseLimitText;
@property(copy, nonatomic) NSString *unitsText; // @synthesize unitsText=_unitsText;
@property(copy, nonatomic) NSString *priceText; // @synthesize priceText=_priceText;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) COCheckoutGoodsViewModel *goodsViewModel; // @synthesize goodsViewModel=_goodsViewModel;
- (void).cxx_destruct;

@end

