//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "COCheckoutInvoiceDistributeBaseView.h"

#import "UITextFieldDelegate-Protocol.h"
#import "UITextViewDelegate-Protocol.h"

@class COCheckoutInvoiceAddressVM, COCheckoutShippingAddressModel, NSString, UILabel;
@protocol COCheckoutReceivePersonInfoViewDelegate;

@interface COCheckoutInvoiceReceivePersonInfoView : COCheckoutInvoiceDistributeBaseView <UITextFieldDelegate, UITextViewDelegate>
{
    COCheckoutInvoiceAddressVM *_contactViewModel;
    id <COCheckoutReceivePersonInfoViewDelegate> _receivePersonInfoViewDelegate;
    UILabel *_titleLabel;
    UILabel *_titleLabelDetail;
    COCheckoutShippingAddressModel *_shippingAddressModel;
}

@property(retain, nonatomic) COCheckoutShippingAddressModel *shippingAddressModel; // @synthesize shippingAddressModel=_shippingAddressModel;
@property(retain, nonatomic) UILabel *titleLabelDetail; // @synthesize titleLabelDetail=_titleLabelDetail;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) __weak id <COCheckoutReceivePersonInfoViewDelegate> receivePersonInfoViewDelegate; // @synthesize receivePersonInfoViewDelegate=_receivePersonInfoViewDelegate;
@property(retain, nonatomic) COCheckoutInvoiceAddressVM *contactViewModel; // @synthesize contactViewModel=_contactViewModel;
- (void).cxx_destruct;
- (id)lableWithFrame:(struct CGRect)arg1 Text:(id)arg2 Font:(double)arg3 TextClolor:(id)arg4;
- (id)viewWithFrame:(struct CGRect)arg1 BackColor:(id)arg2;
- (void)textViewDidEndEditing:(id)arg1;
- (void)textViewDidChange:(id)arg1;
- (_Bool)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (_Bool)textViewShouldBeginEditing:(id)arg1;
- (_Bool)textFieldShouldClear:(id)arg1;
- (void)textFieldDidEndEditing:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (_Bool)textFieldShouldBeginEditing:(id)arg1;
- (void)btnTapped:(id)arg1;
- (void)refreshView;
- (void)addTitle;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

