//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface COCheckoutMainAbstractVM : NSObject
{
    SEL _eventSelector;
    id _selectorParam;
    SEL _apiEventSelector;
    struct UIEdgeInsets _padding;
}

@property(nonatomic) SEL apiEventSelector; // @synthesize apiEventSelector=_apiEventSelector;
@property(retain, nonatomic) id selectorParam; // @synthesize selectorParam=_selectorParam;
@property(nonatomic) SEL eventSelector; // @synthesize eventSelector=_eventSelector;
@property(nonatomic) struct UIEdgeInsets padding; // @synthesize padding=_padding;
- (void).cxx_destruct;
- (id)identity;
- (unsigned long long)type;
- (id)init;

@end

