//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSNumber, NSString;

@interface COCheckoutNotifyRM : NSObject
{
    NSString *_notifyMessage;
    NSString *_notifyMessageBgColor;
    NSString *_notifyMessageBgOpacity;
    NSString *_notifyMessageIcon;
    NSString *_notifyMessageColor;
    NSString *_notifyMessageBgImg;
    NSString *_clickNotifyMsg;
    NSString *_clickNotifyType;
    NSString *_clickNotifyUrl;
    NSString *_clickTitle;
    NSArray *_clickNotifyMsgs;
    NSNumber *_pointType;
}

@property(readonly, nonatomic) NSNumber *pointType; // @synthesize pointType=_pointType;
@property(readonly, nonatomic) NSArray *clickNotifyMsgs; // @synthesize clickNotifyMsgs=_clickNotifyMsgs;
@property(readonly, copy, nonatomic) NSString *clickTitle; // @synthesize clickTitle=_clickTitle;
@property(readonly, copy, nonatomic) NSString *clickNotifyUrl; // @synthesize clickNotifyUrl=_clickNotifyUrl;
@property(readonly, copy, nonatomic) NSString *clickNotifyType; // @synthesize clickNotifyType=_clickNotifyType;
@property(readonly, copy, nonatomic) NSString *clickNotifyMsg; // @synthesize clickNotifyMsg=_clickNotifyMsg;
@property(readonly, copy, nonatomic) NSString *notifyMessageBgImg; // @synthesize notifyMessageBgImg=_notifyMessageBgImg;
@property(readonly, copy, nonatomic) NSString *notifyMessageColor; // @synthesize notifyMessageColor=_notifyMessageColor;
@property(readonly, copy, nonatomic) NSString *notifyMessageIcon; // @synthesize notifyMessageIcon=_notifyMessageIcon;
@property(readonly, copy, nonatomic) NSString *notifyMessageBgOpacity; // @synthesize notifyMessageBgOpacity=_notifyMessageBgOpacity;
@property(readonly, copy, nonatomic) NSString *notifyMessageBgColor; // @synthesize notifyMessageBgColor=_notifyMessageBgColor;
@property(readonly, copy, nonatomic) NSString *notifyMessage; // @synthesize notifyMessage=_notifyMessage;
- (void).cxx_destruct;

@end

