//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "COCheckoutAbstractApi.h"

@class NSDictionary;

@interface COCheckoutSaveVenderPackagingApi : COCheckoutAbstractApi
{
    NSDictionary *_venderPageInfo;
}

@property(retain, nonatomic) NSDictionary *venderPageInfo; // @synthesize venderPageInfo=_venderPageInfo;
- (void).cxx_destruct;
- (id)requestParams;
- (id)functionId;
- (id)initWithVenderPageInfo:(id)arg1;

@end

