//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSNumber, NSString;

@interface COCheckoutVenderConsolidatorRM : NSObject
{
    NSString *_imageDomain;
    NSString *_consolidatorId;
    NSString *_consolidatorName;
    NSString *_logo;
    NSNumber *_isSelected;
    NSNumber *_proviceId;
    NSNumber *_cityId;
    NSNumber *_countyId;
    NSNumber *_townId;
    NSString *_detailAddr;
    NSString *_chargeStandard;
    NSString *_appLogoUrl;
    NSArray *_unsupportSkus;
    NSArray *_unsupportSkuMap;
    NSString *_consolidatorShipmentNotSupportSkuMsg;
}

+ (id)objectClassInArray;
+ (id)replacedKeyFromPropertyName;
@property(readonly, copy, nonatomic) NSString *consolidatorShipmentNotSupportSkuMsg; // @synthesize consolidatorShipmentNotSupportSkuMsg=_consolidatorShipmentNotSupportSkuMsg;
@property(readonly, nonatomic) NSArray *unsupportSkuMap; // @synthesize unsupportSkuMap=_unsupportSkuMap;
@property(readonly, nonatomic) NSArray *unsupportSkus; // @synthesize unsupportSkus=_unsupportSkus;
@property(readonly, copy, nonatomic) NSString *appLogoUrl; // @synthesize appLogoUrl=_appLogoUrl;
@property(readonly, copy, nonatomic) NSString *chargeStandard; // @synthesize chargeStandard=_chargeStandard;
@property(readonly, copy, nonatomic) NSString *detailAddr; // @synthesize detailAddr=_detailAddr;
@property(readonly, nonatomic) NSNumber *townId; // @synthesize townId=_townId;
@property(readonly, nonatomic) NSNumber *countyId; // @synthesize countyId=_countyId;
@property(readonly, nonatomic) NSNumber *cityId; // @synthesize cityId=_cityId;
@property(readonly, nonatomic) NSNumber *proviceId; // @synthesize proviceId=_proviceId;
@property(readonly, nonatomic) NSNumber *isSelected; // @synthesize isSelected=_isSelected;
@property(readonly, copy, nonatomic) NSString *logo; // @synthesize logo=_logo;
@property(readonly, copy, nonatomic) NSString *consolidatorName; // @synthesize consolidatorName=_consolidatorName;
@property(readonly, copy, nonatomic) NSString *consolidatorId; // @synthesize consolidatorId=_consolidatorId;
@property(readonly, copy, nonatomic) NSString *imageDomain; // @synthesize imageDomain=_imageDomain;
- (void).cxx_destruct;
- (id)getRequestParams;
- (void)updateConsolidatorShipmentNotSupportSkuMsg:(id)arg1;
- (void)updateImageDomain:(id)arg1;

@end

