//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class JDImageView, NSString;

@interface COCheckoutMainImmediatelyBuyOnlyOneItemView : UIView
{
    double _viewWidth;
    NSString *_imageUrl;
    JDImageView *_imageView;
}

@property(retain, nonatomic) JDImageView *imageView; // @synthesize imageView=_imageView;
@property(copy, nonatomic) NSString *imageUrl; // @synthesize imageUrl=_imageUrl;
@property(nonatomic) double viewWidth; // @synthesize viewWidth=_viewWidth;
- (void).cxx_destruct;
- (void)setUpUi;
- (id)init;

@end

