//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <JDDBaseModule/JDModel.h>

@class COCheckoutOrderListWareModel, NSString;

@interface COCheckoutPurchaseLimitModel : JDModel
{
    NSString *_purchaseLimitTitle;
    NSString *_skuId;
    COCheckoutOrderListWareModel *_wareModel;
}

@property(retain, nonatomic) COCheckoutOrderListWareModel *wareModel; // @synthesize wareModel=_wareModel;
@property(copy, nonatomic) NSString *skuId; // @synthesize skuId=_skuId;
@property(copy, nonatomic) NSString *purchaseLimitTitle; // @synthesize purchaseLimitTitle=_purchaseLimitTitle;
- (void).cxx_destruct;
- (id)convertToToastGoods;

@end

