//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "COCheckoutMainAbstractView.h"

@class UILabel;

@interface COCheckoutMainLocStoreView : COCheckoutMainAbstractView
{
    UILabel *_storeNameLb;
    UILabel *_storeAddressLb;
}

@property(retain, nonatomic) UILabel *storeAddressLb; // @synthesize storeAddressLb=_storeAddressLb;
@property(retain, nonatomic) UILabel *storeNameLb; // @synthesize storeNameLb=_storeNameLb;
- (void).cxx_destruct;
- (void)updateUiFrame;
- (void)setViewModel:(id)arg1;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

