//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSNumber, NSString;

@interface COCheckoutMainVenderProductVORM : NSObject
{
    NSNumber *_type;
    NSString *_title;
    NSString *_titleName;
    NSString *_priceHide;
    NSString *_jdPrice;
    NSString *_num;
    NSArray *_venderCommodityList;
}

+ (id)objectClassInArray;
@property(readonly, nonatomic) NSArray *venderCommodityList; // @synthesize venderCommodityList=_venderCommodityList;
@property(readonly, nonatomic) NSString *num; // @synthesize num=_num;
@property(readonly, nonatomic) NSString *jdPrice; // @synthesize jdPrice=_jdPrice;
@property(readonly, nonatomic) NSString *priceHide; // @synthesize priceHide=_priceHide;
@property(readonly, nonatomic) NSString *titleName; // @synthesize titleName=_titleName;
@property(readonly, nonatomic) NSString *title; // @synthesize title=_title;
@property(readonly, nonatomic) NSNumber *type; // @synthesize type=_type;
- (void).cxx_destruct;

@end

