//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "COCheckoutMainAbstractVM.h"

@class NSNumber, NSString;

@interface COCheckoutMainEditCountVM : COCheckoutMainAbstractVM
{
    NSString *_wareId;
    NSString *_warePromoId;
    NSNumber *_productAttributeType;
    long long _wareType;
    long long _minNum;
    long long _maxNum;
    long long _number;
    NSString *_title;
    NSString *_limitText;
}

@property(copy, nonatomic) NSString *limitText; // @synthesize limitText=_limitText;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) long long number; // @synthesize number=_number;
@property(nonatomic) long long maxNum; // @synthesize maxNum=_maxNum;
@property(nonatomic) long long minNum; // @synthesize minNum=_minNum;
@property(nonatomic) long long wareType; // @synthesize wareType=_wareType;
@property(retain, nonatomic) NSNumber *productAttributeType; // @synthesize productAttributeType=_productAttributeType;
@property(copy, nonatomic) NSString *warePromoId; // @synthesize warePromoId=_warePromoId;
@property(copy, nonatomic) NSString *wareId; // @synthesize wareId=_wareId;
- (void).cxx_destruct;
- (unsigned long long)type;

@end

