//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class CommuneSingleExpertModel, JDImageView, NSString, UIButton, UILabel;
@protocol CommuneCommentContentViewDelegate;

@interface CommuneCommentContentView : UIView
{
    _Bool _titleBold;
    NSString *_targetId;
    NSString *_targetName;
    NSString *_isSelf;
    NSString *_contentType;
    CommuneSingleExpertModel *_expertModel;
    id <CommuneCommentContentViewDelegate> _delegate;
    NSString *_title;
    NSString *_time;
    NSString *_iconImage;
    NSString *_content;
    double _offsetX;
    double _height;
    UILabel *_titleLabel;
    JDImageView *_iconImageView;
    UILabel *_contentLabel;
    unsigned long long _type;
    NSString *_to;
    UIButton *_reportBtn;
    JDImageView *_typeImageView;
}

@property(retain, nonatomic) JDImageView *typeImageView; // @synthesize typeImageView=_typeImageView;
@property(retain, nonatomic) UIButton *reportBtn; // @synthesize reportBtn=_reportBtn;
@property(copy, nonatomic) NSString *to; // @synthesize to=_to;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
@property(retain, nonatomic) UILabel *contentLabel; // @synthesize contentLabel=_contentLabel;
@property(retain, nonatomic) JDImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) double height; // @synthesize height=_height;
@property(nonatomic) double offsetX; // @synthesize offsetX=_offsetX;
@property(copy, nonatomic) NSString *content; // @synthesize content=_content;
@property(copy, nonatomic) NSString *iconImage; // @synthesize iconImage=_iconImage;
@property(copy, nonatomic) NSString *time; // @synthesize time=_time;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) _Bool titleBold; // @synthesize titleBold=_titleBold;
@property(nonatomic) __weak id <CommuneCommentContentViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) CommuneSingleExpertModel *expertModel; // @synthesize expertModel=_expertModel;
@property(copy, nonatomic) NSString *contentType; // @synthesize contentType=_contentType;
@property(copy, nonatomic) NSString *isSelf; // @synthesize isSelf=_isSelf;
@property(copy, nonatomic) NSString *targetName; // @synthesize targetName=_targetName;
@property(copy, nonatomic) NSString *targetId; // @synthesize targetId=_targetId;
- (void).cxx_destruct;
- (void)typeViewTap:(id)arg1;
- (void)reportCommentAndReply;
- (void)clickToCommentAndReply;
- (void)layoutSubviews;
- (id)addReplyUserNameColor:(id)arg1 userNameLength:(unsigned long long)arg2;
- (double)widthCulcuteFor:(id)arg1 text:(id)arg2;
- (void)setUpView;
- (id)initWithFrame:(struct CGRect)arg1 title:(id)arg2 time:(id)arg3 iconImage:(id)arg4 content:(id)arg5 contentHeight:(double)arg6 offsetX:(double)arg7 type:(unsigned long long)arg8 to:(id)arg9;
- (id)initWithFrame:(struct CGRect)arg1 title:(id)arg2 time:(id)arg3 iconImage:(id)arg4 content:(id)arg5 contentHeight:(double)arg6 offsetX:(double)arg7 type:(unsigned long long)arg8;

@end

