//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CommuneBaseDao.h"

@class CommuneStoreNetWork;

@interface CommuneDetailDao : CommuneBaseDao
{
    CommuneStoreNetWork *_getQuestionDao;
    CommuneStoreNetWork *_isAnswerQualifiedDao;
    CommuneStoreNetWork *_publishAnswerDao;
    CommuneStoreNetWork *_praiseAnswerDao;
    CommuneStoreNetWork *_setBestAnswerDao;
    CommuneStoreNetWork *_followQuestion;
}

- (void).cxx_destruct;
- (void)getSellerDetail:(id)arg1 questionId:(id)arg2 responseUsingBlock:(CDUnknownBlockType)arg3;
- (void)followQuestionAction:(id)arg1 option:(id)arg2 responseUsingBlock:(CDUnknownBlockType)arg3;
- (void)rewardBestAnswer:(id)arg1 questionId:(id)arg2 productId:(id)arg3 beansCount:(id)arg4 reponseUsingBlock:(CDUnknownBlockType)arg5;
- (void)setBestAnswer:(id)arg1 questionId:(id)arg2 productId:(id)arg3 responseUsingBlock:(CDUnknownBlockType)arg4;
- (void)unpraiseAnswer:(id)arg1 responseUsingBlock:(CDUnknownBlockType)arg2;
- (void)praiseAnswer:(id)arg1 responseUsingBlock:(CDUnknownBlockType)arg2;
- (void)publishAnswer:(id)arg1 productId:(id)arg2 content:(id)arg3 anonymous:(id)arg4 responseUsingBlock:(CDUnknownBlockType)arg5;
- (void)isAnswerQualified:(id)arg1 responseUsingBlock:(CDUnknownBlockType)arg2;
- (void)getQuestionDetail:(id)arg1 questionId:(id)arg2 Page:(id)arg3 PageSize:(id)arg4 BiAnswerList:(id)arg5 responseUsingBlock:(CDUnknownBlockType)arg6;
- (void)dealloc;

@end

