//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString, UIImageView;

@protocol CommentDetailVideoCellDelegate <NSObject>

@optional
- (void)hideKeyBoard;
- (void)getVideoUrlWithId:(NSString *)arg1 responseBlock:(void (^)(NSString *))arg2;
- (void)reloadCell;
- (void)didTapPicOnCell:(UIImageView *)arg1 index:(long long)arg2;
@end

