//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSString, UIColor, UIImage, UIImageView, UILabel;

@interface CommuneDetailAnswerHeaderButton : UIView
{
    _Bool _selected;
    NSString *_text;
    UIImage *_image;
    double _sepratorWidth;
    double _imageYOffset;
    UIColor *_textColor;
    UIColor *_selectedTextColor;
    UIImageView *_imageView;
    UILabel *_textLabel;
}

@property(retain, nonatomic) UILabel *textLabel; // @synthesize textLabel=_textLabel;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) UIColor *selectedTextColor; // @synthesize selectedTextColor=_selectedTextColor;
@property(retain, nonatomic) UIColor *textColor; // @synthesize textColor=_textColor;
@property(nonatomic) _Bool selected; // @synthesize selected=_selected;
@property(nonatomic) double imageYOffset; // @synthesize imageYOffset=_imageYOffset;
@property(nonatomic) double sepratorWidth; // @synthesize sepratorWidth=_sepratorWidth;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
@property(copy, nonatomic) NSString *text; // @synthesize text=_text;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)setupSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

