//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <JDDBaseModule/JDModel.h>

@class NSDictionary, NSString;

@interface CommunePageFunctionModel : JDModel
{
    NSString *_functionID;
    NSString *_functionName;
    NSDictionary *_params;
}

@property(retain, nonatomic) NSDictionary *params; // @synthesize params=_params;
@property(copy, nonatomic) NSString *functionName; // @synthesize functionName=_functionName;
@property(copy, nonatomic) NSString *functionID; // @synthesize functionID=_functionID;
- (void).cxx_destruct;
- (void)setDataWithDic:(id)arg1;

@end

