//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <JDDBaseModule/JDModel.h>

@class NSString;

@interface CommentServiceSkuInstallTextModel : JDModel
{
    NSString *_installKey;
    NSString *_installValue;
}

@property(copy, nonatomic) NSString *installValue; // @synthesize installValue=_installValue;
@property(copy, nonatomic) NSString *installKey; // @synthesize installKey=_installKey;
- (void).cxx_destruct;

@end

