//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

#import "CommuneCommentContentViewDelegate-Protocol.h"

@class CommuneCommentReplyModel, NSString, UIView;

@interface CommuneCommentDetailContentCell : UITableViewCell <CommuneCommentContentViewDelegate>
{
    CDUnknownBlockType _replyBlock;
    CDUnknownBlockType _reportBlock;
    unsigned long long _type;
    UIView *_backView;
    CommuneCommentReplyModel *_model;
}

@property(retain, nonatomic) CommuneCommentReplyModel *model; // @synthesize model=_model;
@property(retain, nonatomic) UIView *backView; // @synthesize backView=_backView;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
@property(copy, nonatomic) CDUnknownBlockType reportBlock; // @synthesize reportBlock=_reportBlock;
@property(copy, nonatomic) CDUnknownBlockType replyBlock; // @synthesize replyBlock=_replyBlock;
- (void).cxx_destruct;
- (void)reportUserName:(id)arg1 destReplyId:(id)arg2;
- (void)replyUserName:(id)arg1 destReplyId:(id)arg2;
- (void)resetModel:(id)arg1;
- (void)layoutSubviews;
- (void)setUpViews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

