//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CommuneBaseDao.h"

@class CommuneStoreNetWork;

@interface CommuneCommentDao : CommuneBaseDao
{
    CommuneStoreNetWork *_commentListDao;
    CommuneStoreNetWork *_sendComemntDao;
    CommuneStoreNetWork *_sendReplyDao;
    CommuneStoreNetWork *_replyListDao;
    CommuneStoreNetWork *_textMapDao;
}

- (void).cxx_destruct;
- (void)sendRequestFundtionId:(id)arg1 params:(id)arg2 block:(CDUnknownBlockType)arg3 dao:(id)arg4;
- (void)sendReplyFunctionId:(id)arg1 questionId:(id)arg2 answerId:(id)arg3 commentId:(id)arg4 destReplyId:(id)arg5 content:(id)arg6 anonymous:(id)arg7 callBack:(CDUnknownBlockType)arg8;
- (void)sendCommentFunctionId:(id)arg1 questionId:(id)arg2 answerId:(id)arg3 content:(id)arg4 anonymous:(id)arg5 callBack:(CDUnknownBlockType)arg6;
- (void)loadReplyFunctionId:(id)arg1 questionId:(id)arg2 answerId:(id)arg3 commentId:(id)arg4 page:(id)arg5 pageSize:(id)arg6 callBack:(CDUnknownBlockType)arg7;
- (void)loadCommentList:(id)arg1 questionId:(id)arg2 answerId:(id)arg3 page:(id)arg4 pageSize:(id)arg5 callBack:(CDUnknownBlockType)arg6;

@end

