//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class CommuneRecommendQuestionModel, UILabel;

@interface CommuneDetailRecommendQuestionSingleView : UIView
{
    CommuneRecommendQuestionModel *_model;
    UILabel *_questionContentLabel;
    UILabel *_answerCountLabel;
}

@property(retain, nonatomic) UILabel *answerCountLabel; // @synthesize answerCountLabel=_answerCountLabel;
@property(retain, nonatomic) UILabel *questionContentLabel; // @synthesize questionContentLabel=_questionContentLabel;
@property(retain, nonatomic) CommuneRecommendQuestionModel *model; // @synthesize model=_model;
- (void).cxx_destruct;
- (void)setupSubview;
- (id)initWithFrame:(struct CGRect)arg1;

@end

