//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JDViewController.h"

#import "JDDJXYFooterRefreshViewDelegate-Protocol.h"
#import "NewRefreshTableHeaderViewDelegate-Protocol.h"

@class JDDJXYFooterRefreshView, NSString, NewRefreshTableHeaderView, UIScrollView;

@interface DJXYBaseViewController : JDViewController <NewRefreshTableHeaderViewDelegate, JDDJXYFooterRefreshViewDelegate>
{
    _Bool _isScrolling;
    _Bool _isLast;
    NewRefreshTableHeaderView *_refreshHeaderView;
    JDDJXYFooterRefreshView *_refreshFooterView;
    UIScrollView *_scrollView;
}

@property(nonatomic) _Bool isLast; // @synthesize isLast=_isLast;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(nonatomic) _Bool isScrolling; // @synthesize isScrolling=_isScrolling;
@property(retain, nonatomic) JDDJXYFooterRefreshView *refreshFooterView; // @synthesize refreshFooterView=_refreshFooterView;
@property(retain, nonatomic) NewRefreshTableHeaderView *refreshHeaderView; // @synthesize refreshHeaderView=_refreshHeaderView;
- (void).cxx_destruct;
- (void)removeReloadView;
- (void)showReloadView;
- (void)afterReloadScrollViewData;
- (void)refreshData;
- (void)loadNextData;
- (id)matchedScrollView;
- (_Bool)hasRefreshFooter;
- (_Bool)hasRefreshHeader;
- (void)scrollViewDidEndScroll;
- (void)setRefreshFoooterHidden:(_Bool)arg1;
- (void)loadNextDataFinished;
- (void)refreshFinished;
- (_Bool)footerRefreshViewDataSourceIsLoading:(id)arg1;
- (void)footerRefreshViewDidTriggerRefresh;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)finishLoadingFooterView;
- (void)updateFootView;
- (void)isHiddenrefreshFooterView:(_Bool)arg1;
- (void)addRefreshHeadView:(id)arg1;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithIsLast:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

