//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DJXYBaseCollectionViewCell.h"

@class DJXYHomeSwFloorModel, NSArray, UIImageView, UILabel;

@interface DJXYWaterflowRecommendFloorCell : DJXYBaseCollectionViewCell
{
    UIImageView *_titleLBLeftImgV;
    UIImageView *_titleLBRightImgV;
    UILabel *_titleLB;
    UIImageView *_topSceneBGView;
    NSArray *_labelViews;
    DJXYHomeSwFloorModel *_classedModel;
}

+ (struct CGSize)fixedSize;
@property(retain, nonatomic) DJXYHomeSwFloorModel *classedModel; // @synthesize classedModel=_classedModel;
@property(retain, nonatomic) NSArray *labelViews; // @synthesize labelViews=_labelViews;
@property(retain, nonatomic) UIImageView *topSceneBGView; // @synthesize topSceneBGView=_topSceneBGView;
@property(retain, nonatomic) UILabel *titleLB; // @synthesize titleLB=_titleLB;
@property(retain, nonatomic) UIImageView *titleLBRightImgV; // @synthesize titleLBRightImgV=_titleLBRightImgV;
@property(retain, nonatomic) UIImageView *titleLBLeftImgV; // @synthesize titleLBLeftImgV=_titleLBLeftImgV;
- (void).cxx_destruct;
- (void)labelJump:(id)arg1;
- (id)makeLabelView;
- (void)setDataModel:(id)arg1;
- (void)resetUpLabels;
- (void)layoutLabelViews;
- (void)layoutSubviews;
- (void)initSubViews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

