//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class DPGDetailArticlePositionSku, NSString, UIImageView, UILabel;

@interface DPGDetailOutFitItemView : UIView
{
    NSString *_anchorImg;
    NSString *_anchorDocument;
    CDUnknownBlockType _fitItemViewClickBlock;
    UIView *_mBackGroundView;
    UILabel *_mPriceLab;
    UIImageView *_mCircleImg;
    DPGDetailArticlePositionSku *_model;
}

@property(retain, nonatomic) DPGDetailArticlePositionSku *model; // @synthesize model=_model;
@property(retain, nonatomic) UIImageView *mCircleImg; // @synthesize mCircleImg=_mCircleImg;
@property(retain, nonatomic) UILabel *mPriceLab; // @synthesize mPriceLab=_mPriceLab;
@property(retain, nonatomic) UIView *mBackGroundView; // @synthesize mBackGroundView=_mBackGroundView;
@property(copy, nonatomic) CDUnknownBlockType fitItemViewClickBlock; // @synthesize fitItemViewClickBlock=_fitItemViewClickBlock;
@property(copy, nonatomic) NSString *anchorDocument; // @synthesize anchorDocument=_anchorDocument;
@property(copy, nonatomic) NSString *anchorImg; // @synthesize anchorImg=_anchorImg;
- (void).cxx_destruct;
- (void)startBackViewAnimation;
- (void)layoutLeftOrientaion:(_Bool)arg1;
- (void)positionSkuClick:(id)arg1;
- (void)assignData:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

