//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class DPGDetailJumpModel, NSString;

@interface DPGDetailSimilarArticleModel : NSObject
{
    NSString *_mId;
    NSString *_indexImage;
    NSString *_title;
    NSString *_authorId;
    NSString *_authorName;
    NSString *_authorPic;
    DPGDetailJumpModel *_jump;
    DPGDetailJumpModel *_authorPageJump;
}

+ (id)replacedKeyFromPropertyName;
@property(retain, nonatomic) DPGDetailJumpModel *authorPageJump; // @synthesize authorPageJump=_authorPageJump;
@property(retain, nonatomic) DPGDetailJumpModel *jump; // @synthesize jump=_jump;
@property(copy, nonatomic) NSString *authorPic; // @synthesize authorPic=_authorPic;
@property(copy, nonatomic) NSString *authorName; // @synthesize authorName=_authorName;
@property(copy, nonatomic) NSString *authorId; // @synthesize authorId=_authorId;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(copy, nonatomic) NSString *indexImage; // @synthesize indexImage=_indexImage;
@property(copy, nonatomic) NSString *mId; // @synthesize mId=_mId;
- (void).cxx_destruct;

@end

