//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class NewFinderImageView, UILabel;

@interface DPGDetailAttentionCollectionCell : UICollectionViewCell
{
    NewFinderImageView *_mCardImg;
    UILabel *_mTitleLab;
    UILabel *_mPriceLab;
}

@property(retain, nonatomic) UILabel *mPriceLab; // @synthesize mPriceLab=_mPriceLab;
@property(retain, nonatomic) UILabel *mTitleLab; // @synthesize mTitleLab=_mTitleLab;
@property(retain, nonatomic) NewFinderImageView *mCardImg; // @synthesize mCardImg=_mCardImg;
- (void).cxx_destruct;
- (void)bindData:(id)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

