//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIButton;

@interface DPGDetailNavigationBar : UIView
{
    CDUnknownBlockType _backClickBlock;
    CDUnknownBlockType _closeClickBlock;
    CDUnknownBlockType _shareClickBlock;
    UIButton *_mShareBtn;
    UIButton *_mCloseBtn;
    UIButton *_mBackBtn;
}

@property(retain, nonatomic) UIButton *mBackBtn; // @synthesize mBackBtn=_mBackBtn;
@property(retain, nonatomic) UIButton *mCloseBtn; // @synthesize mCloseBtn=_mCloseBtn;
@property(retain, nonatomic) UIButton *mShareBtn; // @synthesize mShareBtn=_mShareBtn;
@property(copy, nonatomic) CDUnknownBlockType shareClickBlock; // @synthesize shareClickBlock=_shareClickBlock;
@property(copy, nonatomic) CDUnknownBlockType closeClickBlock; // @synthesize closeClickBlock=_closeClickBlock;
@property(copy, nonatomic) CDUnknownBlockType backClickBlock; // @synthesize backClickBlock=_backClickBlock;
- (void).cxx_destruct;
- (void)backClick;
- (void)closeClick;
- (void)shareClick;
- (void)setHiddenCloseBtn:(_Bool)arg1 hiddenShareBtn:(_Bool)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

