//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JDViewController.h"

@class FinderArticleCommentView, FinderArticleDetailBuryData, FinderArticleDetailCompleteModel, FinderArticleDetailFloatSkuView, FinderArticleDetailNavigationView, FinderArticleDetailNetworkRequest, FinderArticleDetailParamsData, FinderArticleDetailWebViewLoadFailView, FinderArticleDetailWebViewLoadgingView, FinderTabBar, JDSHUnplGenerator, NewFinderNetworkProvider, UITableView;

@interface FinderArticleDetailViewController : JDViewController
{
    FinderArticleDetailParamsData *_paramsData;
    FinderArticleDetailNetworkRequest *_networkRequest;
    FinderArticleDetailCompleteModel *_dataModel;
    FinderArticleDetailBuryData *_buryData;
    JDSHUnplGenerator *_unplGenerator;
    NewFinderNetworkProvider *_networkProvider;
    FinderArticleCommentView *_commentView;
    UITableView *_mainTableView;
    FinderArticleDetailNavigationView *_navigationView;
    FinderTabBar *_finderTabBar;
    FinderArticleDetailFloatSkuView *_floatSkuView;
    FinderArticleDetailWebViewLoadgingView *_webviewLoadingView;
    FinderArticleDetailWebViewLoadFailView *_webviewFailView;
}

@property(retain, nonatomic) FinderArticleDetailWebViewLoadFailView *webviewFailView; // @synthesize webviewFailView=_webviewFailView;
@property(retain, nonatomic) FinderArticleDetailWebViewLoadgingView *webviewLoadingView; // @synthesize webviewLoadingView=_webviewLoadingView;
@property(retain, nonatomic) FinderArticleDetailFloatSkuView *floatSkuView; // @synthesize floatSkuView=_floatSkuView;
@property(retain, nonatomic) FinderTabBar *finderTabBar; // @synthesize finderTabBar=_finderTabBar;
@property(retain, nonatomic) FinderArticleDetailNavigationView *navigationView; // @synthesize navigationView=_navigationView;
@property(retain, nonatomic) UITableView *mainTableView; // @synthesize mainTableView=_mainTableView;
@property(retain, nonatomic) FinderArticleCommentView *commentView; // @synthesize commentView=_commentView;
@property(retain, nonatomic) NewFinderNetworkProvider *networkProvider; // @synthesize networkProvider=_networkProvider;
@property(retain, nonatomic) JDSHUnplGenerator *unplGenerator; // @synthesize unplGenerator=_unplGenerator;
@property(retain, nonatomic) FinderArticleDetailBuryData *buryData; // @synthesize buryData=_buryData;
@property(retain, nonatomic) FinderArticleDetailCompleteModel *dataModel; // @synthesize dataModel=_dataModel;
@property(retain, nonatomic) FinderArticleDetailNetworkRequest *networkRequest; // @synthesize networkRequest=_networkRequest;
@property(retain, nonatomic) FinderArticleDetailParamsData *paramsData; // @synthesize paramsData=_paramsData;
- (void).cxx_destruct;
- (void)resetMainTableView;
- (void)scrollToCommentSection;
- (void)refreshCommentList;
- (void)refreshPrasieCellWithModel:(id)arg1;
- (void)refreshFollowViewsStateWithModel:(id)arg1;
- (void)showFloatSkuView;
- (void)addFloatView;
- (void)finderTabBarNetWorkFinishModel:(id)arg1;
- (void)finderTabBarClickModel:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (void)initView;
- (void)initData;
- (void)removeWebViewLoadingView;
- (void)didLoadingWebViewTimeout;
- (void)didLoadingWebViewFailureWithHint:(id)arg1;
- (void)didLoadingWebViewSuccess;
- (void)reconnect;
- (void)requestArticleContentFail;
- (void)requestArticleContentNoData;
- (void)requestArticleContentSuccess;
- (void)articleContentRequest;
- (void)dealloc;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithParams:(id)arg1;
- (void)likeArtielAfterLoginWithPraiseModel:(id)arg1;
- (void)likeArticleWithPraiseModel:(id)arg1;
- (void)followAuthorAfterLogin;
- (void)followAuthor;
- (id)nonFinderArticleVC;
- (_Bool)isHideBottomFollowFloor;
- (id)finderExpressVC;
- (void)clickPopToNonFinderArticleVC;
- (void)clickPopToFinderVC;
- (void)didSendRichtextContent:(CDUnknownBlockType)arg1;
- (void)didJumpToNextPage:(id)arg1;
- (void)didUsingCPSWithSkuId:(id)arg1;
- (void)usingJumpWithStr:(id)arg1;
- (void)cpsWithSkuId:(id)arg1;
- (void)jumpToProductManagerWithSku:(id)arg1 hasUnpl:(_Bool)arg2;
- (void)clickJumpToAuthor;
- (void)clickFloatSkuView:(id)arg1;
- (void)clickFloatView:(id)arg1;
- (void)clickBottomIconCell:(id)arg1;
- (void)clickSourceModel:(id)arg1;
- (void)clickBannerModel:(id)arg1;
- (void)clickFlashTabCell:(id)arg1 Model:(id)arg2;
- (void)clickTagSetCell:(id)arg1;
- (void)clickGuessLikeCell:(id)arg1 Model:(id)arg2;
- (void)clickToRelatArticleVC:(id)arg1;
- (void)clickPraiseCell:(id)arg1 Model:(id)arg2;
- (void)clickTopIcon;
- (void)clickReport;
- (void)clickShareView;
- (void)startCaptchaCheckcodeRequest:(id)arg1 CommentView:(id)arg2;
- (void)startCaptchaSessionRequestWithCommentView:(id)arg1;
- (void)setCallBacksForCommentView:(id)arg1;
- (void)sendComment:(id)arg1 CommentView:(id)arg2 Captcha:(id)arg3;
- (void)showCommentView:(id)arg1 TableView:(id)arg2;
- (void)praiseCommentLogin:(id)arg1;
- (void)praiseComment:(id)arg1;
- (void)didFinishInToastView:(id)arg1;
- (void)didCancelInToastView:(id)arg1;
- (void)showBaseToastWithTitle:(id)arg1 Subtitle:(id)arg2 DonButton:(id)arg3;
- (void)processDeleteComment:(id)arg1;
- (void)clickDeleteCommentModel:(id)arg1;
- (void)processAddCommentModel:(id)arg1;
- (void)startSendCaptcha:(id)arg1 comment:(id)arg2 bsid:(id)arg3;
- (void)startAddCommentRequest:(id)arg1 CommentView:(id)arg2;
- (void)startAddComment:(id)arg1;
- (void)startCommentRequest;
- (void)commentNotification:(id)arg1;
- (void)clickFoldComment:(id)arg1;
- (void)clickCommentToDaren:(id)arg1;
- (void)clickPraiseCommentModel:(id)arg1;
- (void)clickToCommentDetailVC:(id)arg1 ShowCommentView:(_Bool)arg2;
- (void)clickToCommentDetailVC:(id)arg1;
- (void)setCallbackEventsForCommentsCell:(id)arg1 Model:(id)arg2;
- (void)clickReportButton;
- (void)clickFinderButton;
- (void)clickShareButton;
- (void)clickCloseButton;
- (void)clickReturnButton;
- (void)setNavigationView:(id)arg1 Offset:(double)arg2;
- (void)setNavigationViewClickEvents:(id)arg1;
- (id)moreBarButton;
- (id)closeBarButton;
- (id)returnBarButton;
- (id)fetchRightButtonItem;
- (id)fetchLeftButtonItems;

@end

