//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class JDImageView, UILabel;

@interface FinderPhotoBrowserFooterView : UIView
{
    UILabel *_lblNotic;
    JDImageView *_ivArrow;
}

@property(retain, nonatomic) JDImageView *ivArrow; // @synthesize ivArrow=_ivArrow;
@property(retain, nonatomic) UILabel *lblNotic; // @synthesize lblNotic=_lblNotic;
- (void).cxx_destruct;
- (void)prepare;
- (id)initWithFrame:(struct CGRect)arg1;

@end

