//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIImageView, UILabel;

@interface FinderAttentionTagView : UIView
{
    UIImageView *_mTagImageView;
    UILabel *_mTagLabel;
}

@property(retain, nonatomic) UILabel *mTagLabel; // @synthesize mTagLabel=_mTagLabel;
@property(retain, nonatomic) UIImageView *mTagImageView; // @synthesize mTagImageView=_mTagImageView;
- (void).cxx_destruct;
- (void)configModel:(id)arg1;
- (void)layoutSubviews;
- (void)setUpViews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

