//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIControl.h>

@class UIImageView, UILabel;

@interface FinderAttentionAssisantControl : UIControl
{
    UIImageView *_imageView;
    UILabel *_displayLabel;
}

@property(retain, nonatomic) UILabel *displayLabel; // @synthesize displayLabel=_displayLabel;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
- (void).cxx_destruct;
- (void)sizeToFit;
- (void)layoutSubviews;
- (void)setSelected:(_Bool)arg1;
- (void)configWithSelected:(_Bool)arg1 text:(id)arg2;
- (void)commonInit;
- (void)awakeFromNib;
- (id)initWithFrame:(struct CGRect)arg1;

@end

