//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FinderHotTableViewCell.h"

@class FinderHotListCellBottomView, NewFinderImageView, UIImageView, UILabel, UIView;

@interface FinderHotBigVideoCell : FinderHotTableViewCell
{
    UIView *_mBackgroundView;
    NewFinderImageView *_mPicImage;
    UILabel *_mTitleLab;
    UIImageView *_mPlayImg;
    UILabel *_mPlayDurationLab;
    FinderHotListCellBottomView *_mAuthorView;
}

@property(retain, nonatomic) FinderHotListCellBottomView *mAuthorView; // @synthesize mAuthorView=_mAuthorView;
@property(retain, nonatomic) UILabel *mPlayDurationLab; // @synthesize mPlayDurationLab=_mPlayDurationLab;
@property(retain, nonatomic) UIImageView *mPlayImg; // @synthesize mPlayImg=_mPlayImg;
@property(retain, nonatomic) UILabel *mTitleLab; // @synthesize mTitleLab=_mTitleLab;
@property(retain, nonatomic) NewFinderImageView *mPicImage; // @synthesize mPicImage=_mPicImage;
@property(retain, nonatomic) UIView *mBackgroundView; // @synthesize mBackgroundView=_mBackgroundView;
- (void).cxx_destruct;
- (void)hiddenPlayView;
- (void)showPlayView;
- (void)refresh:(id)arg1;
- (void)assignValue:(id)arg1;
- (void)layoutSubviews;
- (void)setupViews;

@end

