//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FinderJumpModel, NSNumber, NSString;

@interface FinderAttentionRecAuthor : NSObject
{
    _Bool _shop;
    NSString *_authorId;
    NSString *_name;
    NSString *_imgUrl;
    NSNumber *_isRec;
    NSString *_followNumStr;
    NSString *_area;
    NSString *_publishCountStr;
    NSString *_reason;
    FinderJumpModel *_jump;
}

@property(retain, nonatomic) FinderJumpModel *jump; // @synthesize jump=_jump;
@property(copy, nonatomic) NSString *reason; // @synthesize reason=_reason;
@property(nonatomic) _Bool shop; // @synthesize shop=_shop;
@property(copy, nonatomic) NSString *publishCountStr; // @synthesize publishCountStr=_publishCountStr;
@property(copy, nonatomic) NSString *area; // @synthesize area=_area;
@property(copy, nonatomic) NSString *followNumStr; // @synthesize followNumStr=_followNumStr;
@property(copy, nonatomic) NSNumber *isRec; // @synthesize isRec=_isRec;
@property(copy, nonatomic) NSString *imgUrl; // @synthesize imgUrl=_imgUrl;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(copy, nonatomic) NSString *authorId; // @synthesize authorId=_authorId;
- (void).cxx_destruct;
- (id)init;

@end

