//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface FMImageTool : NSObject
{
}

+ (id)sampleBufferToUIImage:(struct opaqueCMSampleBuffer *)arg1 rotation:(int)arg2 horizontallyMirror:(_Bool)arg3;
+ (id)fixOrientation:(id)arg1;

@end

