//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "FMAngleHintViewDelegate-Protocol.h"
#import "UIAlertViewDelegate-Protocol.h"

@class CMMotionManager, FMAngleHintView, FMCameraView, FMFootImageTool, FMRequestor, FMScanView, FMTakePhotoGuideView, NSDictionary, NSString, UIButton, UILabel;

@interface FMMeasurementView : UIView <FMAngleHintViewDelegate, UIAlertViewDelegate>
{
    FMRequestor *request;
    _Bool _isSelfTakePhoto;
    CDUnknownBlockType _onClickBackBtn;
    CDUnknownBlockType _onGotoSuggestVCBlock;
    FMCameraView *_cameraView;
    FMAngleHintView *_angleHintView;
    UIButton *_backView;
    UIButton *_helpView;
    UIButton *_changeDirectionView;
    FMFootImageTool *_footImageTool;
    CMMotionManager *_motionManager;
    long long _currentStatusType;
    UILabel *_currentStateLabel;
    UILabel *_currentFootImage;
    FMScanView *_scanView;
    FMTakePhotoGuideView *_guideView;
    NSString *_sku;
    NSDictionary *_params;
}

@property(retain, nonatomic) NSDictionary *params; // @synthesize params=_params;
@property(copy, nonatomic) NSString *sku; // @synthesize sku=_sku;
@property(retain, nonatomic) FMTakePhotoGuideView *guideView; // @synthesize guideView=_guideView;
@property(retain, nonatomic) FMScanView *scanView; // @synthesize scanView=_scanView;
@property(retain, nonatomic) UILabel *currentFootImage; // @synthesize currentFootImage=_currentFootImage;
@property(retain, nonatomic) UILabel *currentStateLabel; // @synthesize currentStateLabel=_currentStateLabel;
@property(nonatomic) _Bool isSelfTakePhoto; // @synthesize isSelfTakePhoto=_isSelfTakePhoto;
@property(nonatomic) long long currentStatusType; // @synthesize currentStatusType=_currentStatusType;
@property(retain, nonatomic) CMMotionManager *motionManager; // @synthesize motionManager=_motionManager;
@property(retain, nonatomic) FMFootImageTool *footImageTool; // @synthesize footImageTool=_footImageTool;
@property(retain, nonatomic) UIButton *changeDirectionView; // @synthesize changeDirectionView=_changeDirectionView;
@property(retain, nonatomic) UIButton *helpView; // @synthesize helpView=_helpView;
@property(retain, nonatomic) UIButton *backView; // @synthesize backView=_backView;
@property(retain, nonatomic) FMAngleHintView *angleHintView; // @synthesize angleHintView=_angleHintView;
@property(retain, nonatomic) FMCameraView *cameraView; // @synthesize cameraView=_cameraView;
@property(copy, nonatomic) CDUnknownBlockType onGotoSuggestVCBlock; // @synthesize onGotoSuggestVCBlock=_onGotoSuggestVCBlock;
@property(copy, nonatomic) CDUnknownBlockType onClickBackBtn; // @synthesize onClickBackBtn=_onClickBackBtn;
- (void).cxx_destruct;
- (void)showAngel;
- (void)hideAngel;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)changeDirectionButtonAction;
- (void)popViewAction;
- (void)backButtonAction;
- (void)uploadDataToService;
- (void)chooiseTakePhotoType;
- (void)eventClickWithEventParam:(id)arg1 eventName:(id)arg2 eventId:(id)arg3;
- (void)guideButtonAction;
- (void)guideWithShowStartButton:(_Bool)arg1;
- (void)showNoviceGuideView;
- (void)failResonToast:(int)arg1;
- (void)showScanView;
- (void)stepToNextAction;
- (_Bool)chekoutCurrentTypeIsLeft;
- (_Bool)chekoutCurrentTypeIsHeel;
- (void)takePicture;
- (void)switchFMMeasureStatusType:(long long)arg1;
- (void)updateCoremotion;
- (void)initSubViews;
- (void)initData;
- (void)cameraClose;
- (void)cameraResume;
- (void)fmSetNewFrame:(struct CGRect)arg1 withParams:(id)arg2;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

