//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UIScrollViewDelegate-Protocol.h"

@class FMTakePhotoPageControl, NSArray, NSString, UIButton, UIScrollView;

@interface FMTakePhotoGuideView : UIView <UIScrollViewDelegate>
{
    _Bool _alwaysShowStarButton;
    long long _takePhotoWay;
    UIScrollView *_fmScrollView;
    FMTakePhotoPageControl *_pageControl;
    UIButton *_startButton;
    NSArray *_imageNameArray;
    NSArray *_stringArray;
    NSArray *_currentImageArray;
    NSString *_skuId;
}

+ (id)showInView:(id)arg1 takePhotoWay:(long long)arg2;
+ (id)showInView:(id)arg1 takePhotoBySelf:(_Bool)arg2 withNewGuide:(_Bool)arg3 withSkuId:(id)arg4;
+ (id)showInView:(id)arg1 takePhotoBySelf:(_Bool)arg2 withNewGuide:(_Bool)arg3;
+ (id)showInView:(id)arg1 takePhotoBySelf:(_Bool)arg2;
@property(retain, nonatomic) NSString *skuId; // @synthesize skuId=_skuId;
@property(nonatomic) _Bool alwaysShowStarButton; // @synthesize alwaysShowStarButton=_alwaysShowStarButton;
@property(retain, nonatomic) NSArray *currentImageArray; // @synthesize currentImageArray=_currentImageArray;
@property(retain, nonatomic) NSArray *stringArray; // @synthesize stringArray=_stringArray;
@property(retain, nonatomic) NSArray *imageNameArray; // @synthesize imageNameArray=_imageNameArray;
@property(retain, nonatomic) UIButton *startButton; // @synthesize startButton=_startButton;
@property(retain, nonatomic) FMTakePhotoPageControl *pageControl; // @synthesize pageControl=_pageControl;
@property(retain, nonatomic) UIScrollView *fmScrollView; // @synthesize fmScrollView=_fmScrollView;
@property(nonatomic) long long takePhotoWay; // @synthesize takePhotoWay=_takePhotoWay;
- (void).cxx_destruct;
- (void)beginFeetMessureClick:(id)arg1;
- (void)startButtonAction;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)createSubView;
- (void)commonInit;
- (void)initData;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithView:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

