//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UIScrollViewDelegate-Protocol.h"

@class NSArray, NSString, UILabel, UIScrollView;

@interface FSHotTagView : UIView <UIScrollViewDelegate>
{
    CDUnknownBlockType _hotItemsClicked;
    UIScrollView *_scrollView;
    NSArray *_keysArr;
    NSString *_title;
    UILabel *_labTitle;
}

+ (int)hotTagWithTitleViewHeight;
+ (int)hotTagViewHeight;
@property(retain, nonatomic) UILabel *labTitle; // @synthesize labTitle=_labTitle;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSArray *keysArr; // @synthesize keysArr=_keysArr;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(copy, nonatomic) CDUnknownBlockType hotItemsClicked; // @synthesize hotItemsClicked=_hotItemsClicked;
- (void).cxx_destruct;
- (void)btnAction:(id)arg1;
- (void)drawScrollBtns:(id)arg1;
- (void)drawTitle:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 withArray:(id)arg2 title:(id)arg3;
- (id)initWithFrame:(struct CGRect)arg1 withArray:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

