//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSString, UIButton, UIImageView, UITextField;
@protocol FSSPromSearchBarDelegate;

@interface FSSPromSearchBar : UIView
{
    _Bool _showShareButton;
    id <FSSPromSearchBarDelegate> _delegate;
    UITextField *_searTextField;
    UIImageView *_searchBg;
    UIButton *_shareButton;
    NSString *_placeholderTxt;
}

@property(copy, nonatomic) NSString *placeholderTxt; // @synthesize placeholderTxt=_placeholderTxt;
@property(nonatomic) _Bool showShareButton; // @synthesize showShareButton=_showShareButton;
@property(retain, nonatomic) UIButton *shareButton; // @synthesize shareButton=_shareButton;
@property(retain, nonatomic) UIImageView *searchBg; // @synthesize searchBg=_searchBg;
@property(retain, nonatomic) UITextField *searTextField; // @synthesize searTextField=_searTextField;
@property(nonatomic) __weak id <FSSPromSearchBarDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
@property(copy, nonatomic) NSString *searchText;
- (void)gotoSearchPage:(id)arg1;
- (void)showSearchField:(_Bool)arg1;
- (struct CGRect)getTopTagFrame;
- (void)configPlaceholder:(id)arg1;
- (_Bool)textFieldShouldBeginEditing:(id)arg1;
- (void)shareButtonClicked:(id)arg1;
- (void)initSubViews;
- (id)initWithFrame:(struct CGRect)arg1 placeholderText:(id)arg2 showShareButton:(_Bool)arg3;

@end

