//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

#import "FSSearchResultCollectionCellProtocol-Protocol.h"

@class FSSHotTagViewModel, NSArray, NSString, UILabel, UIView;

@interface FSSWaterFallHotTagCell : UICollectionViewCell <FSSearchResultCollectionCellProtocol>
{
    FSSHotTagViewModel *_viewModel;
    UIView *_tagContainerView;
    NSArray *_arrTags;
    UIView *_lineTitleLeft;
    UIView *_lineTitleRight;
    UILabel *_labTitle;
}

+ (double)cellHeightWithVM:(id)arg1;
@property(retain, nonatomic) UILabel *labTitle; // @synthesize labTitle=_labTitle;
@property(retain, nonatomic) UIView *lineTitleRight; // @synthesize lineTitleRight=_lineTitleRight;
@property(retain, nonatomic) UIView *lineTitleLeft; // @synthesize lineTitleLeft=_lineTitleLeft;
@property(retain, nonatomic) NSArray *arrTags; // @synthesize arrTags=_arrTags;
@property(retain, nonatomic) UIView *tagContainerView; // @synthesize tagContainerView=_tagContainerView;
@property(retain, nonatomic) FSSHotTagViewModel *viewModel; // @synthesize viewModel=_viewModel;
- (void).cxx_destruct;
- (void)btnAction:(id)arg1;
- (void)drawTagBtns;
- (void)drawTitle;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

