//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

#import "FSSearchResultCollectionCellProtocol-Protocol.h"

@class FSSBeltShopViewModel, JDImageView, NSArray, NSString, UIButton, UIImageView, UILabel;

@interface FSSWaterFallBeltShopCell : UICollectionViewCell <FSSearchResultCollectionCellProtocol>
{
    FSSBeltShopViewModel *_viewModel;
    UIImageView *_imgBackground;
    JDImageView *_imgShopLogo;
    UILabel *_labShopName;
    UILabel *_labShopFocus;
    UIButton *_btnGoToShop;
    NSArray *_arrShopItemsBtn;
    NSArray *_arrShopItemsPic;
    NSArray *_arrShopItemsPrice;
    UIImageView *_adIcon;
}

+ (double)cellHeightWithVM:(id)arg1;
@property(retain, nonatomic) UIImageView *adIcon; // @synthesize adIcon=_adIcon;
@property(retain, nonatomic) NSArray *arrShopItemsPrice; // @synthesize arrShopItemsPrice=_arrShopItemsPrice;
@property(retain, nonatomic) NSArray *arrShopItemsPic; // @synthesize arrShopItemsPic=_arrShopItemsPic;
@property(retain, nonatomic) NSArray *arrShopItemsBtn; // @synthesize arrShopItemsBtn=_arrShopItemsBtn;
@property(nonatomic) __weak UIButton *btnGoToShop; // @synthesize btnGoToShop=_btnGoToShop;
@property(nonatomic) __weak UILabel *labShopFocus; // @synthesize labShopFocus=_labShopFocus;
@property(nonatomic) __weak UILabel *labShopName; // @synthesize labShopName=_labShopName;
@property(nonatomic) __weak JDImageView *imgShopLogo; // @synthesize imgShopLogo=_imgShopLogo;
@property(nonatomic) __weak UIImageView *imgBackground; // @synthesize imgBackground=_imgBackground;
@property(retain, nonatomic) FSSBeltShopViewModel *viewModel; // @synthesize viewModel=_viewModel;
- (void).cxx_destruct;
- (void)btnShopItemClicked:(id)arg1;
- (void)btnGoToShopClickd;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

