//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewLayout.h>

@class NSMutableArray;

@interface FSSWaterFallViewLayout : UICollectionViewLayout
{
    double _minimumLineSpacing;
    NSMutableArray *_columnHeightArray;
    NSMutableArray *_allAttributesArray;
    NSMutableArray *_sectionLayoutArray;
    double _contentHeight;
    struct CGSize _headerReferenceSize;
    struct CGSize _footerReferenceSize;
    struct UIEdgeInsets _sectionInset;
}

@property(nonatomic) double contentHeight; // @synthesize contentHeight=_contentHeight;
@property(retain, nonatomic) NSMutableArray *sectionLayoutArray; // @synthesize sectionLayoutArray=_sectionLayoutArray;
@property(retain, nonatomic) NSMutableArray *allAttributesArray; // @synthesize allAttributesArray=_allAttributesArray;
@property(retain, nonatomic) NSMutableArray *columnHeightArray; // @synthesize columnHeightArray=_columnHeightArray;
@property(nonatomic) struct UIEdgeInsets sectionInset; // @synthesize sectionInset=_sectionInset;
@property(nonatomic) struct CGSize footerReferenceSize; // @synthesize footerReferenceSize=_footerReferenceSize;
@property(nonatomic) struct CGSize headerReferenceSize; // @synthesize headerReferenceSize=_headerReferenceSize;
@property(nonatomic) double minimumLineSpacing; // @synthesize minimumLineSpacing=_minimumLineSpacing;
- (void).cxx_destruct;
- (double)getMaxColumnHeight;
- (void)getMinColumnHeight:(double *)arg1 currentIndex:(long long *)arg2;
- (id)layoutAttributesForSupplementaryViewOfKind:(id)arg1 atIndexPath:(id)arg2;
- (id)layoutAttributesForItemAtIndexPath:(id)arg1;
- (_Bool)shouldInvalidateLayoutForBoundsChange:(struct CGRect)arg1;
- (struct CGSize)collectionViewContentSize;
- (id)layoutAttributesForElementsInRect:(struct CGRect)arg1;
- (id)createLayoutWithSection:(long long)arg1;
- (void)prepareLayout;
- (id)init;
- (struct CGRect)cellFrameAtIndexPath:(id)arg1;

@end

