//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray, UIButton, UILabel, UIScrollView;

@interface FSTableHeaderView : UIView
{
    _Bool _isSelected;
    _Bool _isFilterConfigSelected;
    CDUnknownBlockType _tapHeaderTextLabel;
    CDUnknownBlockType _tapTiledImageView;
    CDUnknownBlockType _tapRedPackageButton;
    CDUnknownBlockType _tapFilterConfigButton;
    UILabel *_headerTextLabel;
    UIScrollView *_scrollView;
    NSArray *_tiledFilterTags;
    UIView *_redPackageView;
    UIButton *_redPackageButton;
    UIView *_filterConfigView;
    UIButton *_filterConfigButton;
    double _currentHeight;
}

@property(nonatomic) double currentHeight; // @synthesize currentHeight=_currentHeight;
@property(nonatomic) _Bool isFilterConfigSelected; // @synthesize isFilterConfigSelected=_isFilterConfigSelected;
@property(retain, nonatomic) UIButton *filterConfigButton; // @synthesize filterConfigButton=_filterConfigButton;
@property(retain, nonatomic) UIView *filterConfigView; // @synthesize filterConfigView=_filterConfigView;
@property(nonatomic) _Bool isSelected; // @synthesize isSelected=_isSelected;
@property(retain, nonatomic) UIButton *redPackageButton; // @synthesize redPackageButton=_redPackageButton;
@property(retain, nonatomic) UIView *redPackageView; // @synthesize redPackageView=_redPackageView;
@property(retain, nonatomic) NSArray *tiledFilterTags; // @synthesize tiledFilterTags=_tiledFilterTags;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(retain, nonatomic) UILabel *headerTextLabel; // @synthesize headerTextLabel=_headerTextLabel;
@property(copy, nonatomic) CDUnknownBlockType tapFilterConfigButton; // @synthesize tapFilterConfigButton=_tapFilterConfigButton;
@property(copy, nonatomic) CDUnknownBlockType tapRedPackageButton; // @synthesize tapRedPackageButton=_tapRedPackageButton;
@property(copy, nonatomic) CDUnknownBlockType tapTiledImageView; // @synthesize tapTiledImageView=_tapTiledImageView;
@property(copy, nonatomic) CDUnknownBlockType tapHeaderTextLabel; // @synthesize tapHeaderTextLabel=_tapHeaderTextLabel;
- (void).cxx_destruct;
- (void)removeAllHeaderSubViews;
- (void)layoutConfigButtonSelectedStyle;
- (void)filterConfigButtonClick;
- (void)layoutFilterConfigButtonWithTitle:(id)arg1;
- (void)layoutRedPackageSelectedStyle;
- (void)redPackageButtonClick;
- (void)addRedPackageView;
- (void)imageTaped:(id)arg1;
- (id)displayScrollView;
- (void)handleTapGesture:(id)arg1;
- (id)displayHeaderTextLabelWithAttributedText:(id)arg1;
- (void)addLineLayerWithSuperView:(id)arg1;
- (void)loadHeaderViewWithAttributedText:(id)arg1 tiledFilterTags:(id)arg2 isSelected:(_Bool)arg3 filterConfigTitle:(id)arg4 isFilterConfigSelected:(_Bool)arg5;

@end

