//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface FSTopTagModel : NSObject
{
    int _topTagType;
    NSString *_topTagTitle;
    NSString *_topTagFilterValue;
}

@property(copy, nonatomic) NSString *topTagFilterValue; // @synthesize topTagFilterValue=_topTagFilterValue;
@property(copy, nonatomic) NSString *topTagTitle; // @synthesize topTagTitle=_topTagTitle;
@property(nonatomic) int topTagType; // @synthesize topTagType=_topTagType;
- (void).cxx_destruct;
- (void)resetTokeyWordType;

@end

