//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class IABulletView, NSString;

@protocol IABulletViewDelegate <NSObject>

@optional
- (void)onFinished:(IABulletView *)arg1;
- (void)bulletItemClick:(IABulletView *)arg1 bulletItemIndex:(long long)arg2;
- (NSString *)contentOfBulletItem:(long long)arg1;
- (long long)numberOfBulleItem;
@end

