//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UIScrollViewDelegate-Protocol.h"

@class JDAdStarViewModel, JDPageControl, JDStartLoadingView, JDTimerWeakObject, NSString, OpertationPicModel, UIButton, UIImageView, UILabel, UIScrollView;
@protocol JDAdStartViewDelegate;

@interface JDAdStartView : UIView <UIScrollViewDelegate>
{
    UIScrollView *_scrollView;
    JDPageControl *_pageControl;
    UIButton *_removeButton;
    UIButton *_nextButton;
    UIImageView *_nextImageView;
    UIView *_singleNextBgView;
    UIImageView *_imageView;
    UILabel *_countLabel;
    UIImageView *_countDownBg;
    UIButton *_sanButton;
    JDStartLoadingView *_startLoadingView;
    _Bool _doAnimation;
    _Bool _isVisiable;
    UIView *_contentView;
    id <JDAdStartViewDelegate> _delegate;
    CDUnknownBlockType _dismissBlock;
    double _videoDuration;
    long long _dismissAnimation;
    double _dismissAnimationDuration;
    double _startDismissAnimationTime;
    JDAdStarViewModel *_startViewModel;
    JDTimerWeakObject *_timer;
    long long _currentIndex;
    NSString *_clp;
    OpertationPicModel *_curentPicModel;
}

@property(retain, nonatomic) OpertationPicModel *curentPicModel; // @synthesize curentPicModel=_curentPicModel;
@property(nonatomic) _Bool isVisiable; // @synthesize isVisiable=_isVisiable;
@property(retain, nonatomic) NSString *clp; // @synthesize clp=_clp;
@property(nonatomic) long long currentIndex; // @synthesize currentIndex=_currentIndex;
@property(retain, nonatomic) JDTimerWeakObject *timer; // @synthesize timer=_timer;
@property(retain, nonatomic) JDAdStarViewModel *startViewModel; // @synthesize startViewModel=_startViewModel;
@property(nonatomic) double startDismissAnimationTime; // @synthesize startDismissAnimationTime=_startDismissAnimationTime;
@property(nonatomic) double dismissAnimationDuration; // @synthesize dismissAnimationDuration=_dismissAnimationDuration;
@property(nonatomic) long long dismissAnimation; // @synthesize dismissAnimation=_dismissAnimation;
@property(nonatomic) double videoDuration; // @synthesize videoDuration=_videoDuration;
@property(copy, nonatomic) CDUnknownBlockType dismissBlock; // @synthesize dismissBlock=_dismissBlock;
@property(nonatomic) __weak id <JDAdStartViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
- (void).cxx_destruct;
- (_Bool)shouldAutoDismiss;
- (void)reportEnterBackgroundMta;
- (void)reportStartViewRenderPerformance;
- (void)reportCloseButtonWithModel:(id)arg1;
- (void)reportViewClickedWithModel:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)sanButtonPressed;
- (void)topHalfViewCloseButtonAction:(id)arg1;
- (void)singleFloatViewClosedButtonAction:(id)arg1;
- (void)skipButtonAction:(id)arg1;
- (void)redirectToWebView:(id)arg1;
- (id)event_paramaValue2WithModel:(id)arg1;
- (id)event_paramaValueWithModel:(id)arg1;
- (void)doCounting;
- (_Bool)isNeedCount;
- (_Bool)checkLocalImagesIsAvailable;
- (void)checkSkipButtonIsAvailable;
- (void)disMissCurrentView;
- (void)startCounting;
- (void)startSkipAnimation;
- (void)readytoPlay;
- (void)playVideoIfNeed;
- (void)hidenHalfView;
- (void)startHalfViewAnimation;
- (void)start;
- (_Bool)configAdStartViewWithData:(id)arg1 isFromBg:(_Bool)arg2;
- (void)createHalfAdStartImageView;
- (void)createMutabelAdStartImageView;
- (void)createFloatAdStartImageView;
- (void)createSigleAdStartImageView;
- (void)beginAnimation;
- (void)removeAllSubviews;
- (void)initTimer;
- (id)init;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

