//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class JDPayMemberCodeNavigationController, JDPayMemberCodeResultModel, JDPayMemberCustomerCodeVerifyInfoModel, NSArray, NSMutableArray, NSString, UINavigationController, UIViewController;

@interface JDPayMemberCodeManager : NSObject
{
    _Bool _fingerToPwd;
    _Bool _isOpen;
    _Bool _orginalNaviStatus;
    NSString *_queryResultType;
    NSString *_secretKey;
    NSString *_sessionKey;
    NSString *_bizSource;
    NSString *_pin;
    NSString *_token;
    NSString *_appSource;
    NSString *_mode;
    NSArray *_couponIds;
    NSString *_bizTokenKey;
    NSString *_openResult;
    NSString *_code;
    NSString *_deviceToken;
    long long _originalBarStyle;
    UIViewController *_topViewController;
    UIViewController *_startViewController;
    CDUnknownBlockType _payCallback;
    UINavigationController *_appNavigationController;
    JDPayMemberCodeResultModel *_memberCodeModel;
    JDPayMemberCustomerCodeVerifyInfoModel *_verifyInfoModel;
    CDUnknownBlockType _memberCodeOpenResult;
    CDUnknownBlockType _verifyResult;
    CDUnknownBlockType _closeMemberCode;
    CDUnknownBlockType _handleAlertUrl;
    CDUnknownBlockType _hanleOpenStatus;
    JDPayMemberCodeNavigationController *_presentedNavigationController;
    UIViewController *_appRootViewController;
    NSMutableArray *_dispatchTable;
    NSString *_tdSignedData;
    NSString *_buryData;
    NSString *_uuid;
    NSString *_modifyPwdUrl;
}

+ (id)sharedManager;
@property(retain, nonatomic) NSString *modifyPwdUrl; // @synthesize modifyPwdUrl=_modifyPwdUrl;
@property(copy, nonatomic) NSString *uuid; // @synthesize uuid=_uuid;
@property(copy, nonatomic) NSString *buryData; // @synthesize buryData=_buryData;
@property(retain, nonatomic) NSString *tdSignedData; // @synthesize tdSignedData=_tdSignedData;
@property(retain, nonatomic) NSMutableArray *dispatchTable; // @synthesize dispatchTable=_dispatchTable;
@property(retain, nonatomic) UIViewController *appRootViewController; // @synthesize appRootViewController=_appRootViewController;
@property(retain, nonatomic) JDPayMemberCodeNavigationController *presentedNavigationController; // @synthesize presentedNavigationController=_presentedNavigationController;
@property(copy, nonatomic) CDUnknownBlockType hanleOpenStatus; // @synthesize hanleOpenStatus=_hanleOpenStatus;
@property(copy, nonatomic) CDUnknownBlockType handleAlertUrl; // @synthesize handleAlertUrl=_handleAlertUrl;
@property(copy, nonatomic) CDUnknownBlockType closeMemberCode; // @synthesize closeMemberCode=_closeMemberCode;
@property(copy, nonatomic) CDUnknownBlockType verifyResult; // @synthesize verifyResult=_verifyResult;
@property(copy, nonatomic) CDUnknownBlockType memberCodeOpenResult; // @synthesize memberCodeOpenResult=_memberCodeOpenResult;
@property(retain, nonatomic) JDPayMemberCustomerCodeVerifyInfoModel *verifyInfoModel; // @synthesize verifyInfoModel=_verifyInfoModel;
@property(retain, nonatomic) JDPayMemberCodeResultModel *memberCodeModel; // @synthesize memberCodeModel=_memberCodeModel;
@property(nonatomic) __weak UINavigationController *appNavigationController; // @synthesize appNavigationController=_appNavigationController;
@property(copy, nonatomic) CDUnknownBlockType payCallback; // @synthesize payCallback=_payCallback;
@property(nonatomic) __weak UIViewController *startViewController; // @synthesize startViewController=_startViewController;
@property(retain, nonatomic) UIViewController *topViewController; // @synthesize topViewController=_topViewController;
@property(nonatomic) long long originalBarStyle; // @synthesize originalBarStyle=_originalBarStyle;
@property(nonatomic) _Bool orginalNaviStatus; // @synthesize orginalNaviStatus=_orginalNaviStatus;
@property(copy, nonatomic) NSString *deviceToken; // @synthesize deviceToken=_deviceToken;
@property(copy, nonatomic) NSString *code; // @synthesize code=_code;
@property(copy, nonatomic) NSString *openResult; // @synthesize openResult=_openResult;
@property(copy, nonatomic) NSString *bizTokenKey; // @synthesize bizTokenKey=_bizTokenKey;
@property(retain, nonatomic) NSArray *couponIds; // @synthesize couponIds=_couponIds;
@property(copy, nonatomic) NSString *mode; // @synthesize mode=_mode;
@property(copy, nonatomic) NSString *appSource; // @synthesize appSource=_appSource;
@property(copy, nonatomic) NSString *token; // @synthesize token=_token;
@property(copy, nonatomic) NSString *pin; // @synthesize pin=_pin;
@property(copy, nonatomic) NSString *bizSource; // @synthesize bizSource=_bizSource;
@property(copy, nonatomic) NSString *sessionKey; // @synthesize sessionKey=_sessionKey;
@property(copy, nonatomic) NSString *secretKey; // @synthesize secretKey=_secretKey;
@property(nonatomic) _Bool isOpen; // @synthesize isOpen=_isOpen;
@property(copy, nonatomic) NSString *queryResultType; // @synthesize queryResultType=_queryResultType;
@property(nonatomic) _Bool fingerToPwd; // @synthesize fingerToPwd=_fingerToPwd;
- (void).cxx_destruct;
- (void)queryPaymentResultCompletion:(CDUnknownBlockType)arg1 showDialog:(_Bool)arg2;
- (void)paycodePushData:(id)arg1;
- (void)paycodePushData:(id)arg1 Completion:(CDUnknownBlockType)arg2 showDialog:(_Bool)arg3;
- (void)signAgreementWithCompletion:(CDUnknownBlockType)arg1 showDialog:(_Bool)arg2;
- (void)getTDFingerprintStrWithData:(id)arg1 Completion:(CDUnknownBlockType)arg2;
- (void)verifyPay:(id)arg1 Completion:(CDUnknownBlockType)arg2;
- (void)queryVerifyPayWayWithParams:(id)arg1 Completion:(CDUnknownBlockType)arg2;
- (void)repeatSmsCodeWithCompletion:(CDUnknownBlockType)arg1 showDialog:(_Bool)arg2;
- (void)closePaymentCodeCompletion:(CDUnknownBlockType)arg1 showDialog:(_Bool)arg2;
- (void)open:(id)arg1 Completion:(CDUnknownBlockType)arg2;
- (void)refreshMemberCodeWithCompletion:(CDUnknownBlockType)arg1 showDialog:(_Bool)arg2;
- (void)getEntranceWithTdSignData:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)getTDRishkDataWithCallBack:(CDUnknownBlockType)arg1;
- (void)getEntranceWithCompletion:(CDUnknownBlockType)arg1 showDialog:(_Bool)arg2;
- (id)deviceInfoDict;
- (id)baseParams;
- (void)showControlListsWithContrlModel:(id)arg1 buttonClick:(CDUnknownBlockType)arg2;
- (void)closePaymentWithCompletion:(CDUnknownBlockType)arg1;
- (id)init;
- (void)clearContext;

@end

