//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class JDPCEntranceReturnModel, JDPayClosePayCodeModel, JDPayCodeNavigationController, JDPayPausePageInfoModel, JDPayPaymentCodeModel, NSArray, NSMutableArray, NSString, UINavigationController, UIViewController;

@interface JDPayPaymentCodeManager : NSObject
{
    _Bool _isFirstUnfinishedOrder;
    _Bool _isRunning;
    _Bool _orginalNaviStatus;
    _Bool _isCacheOffLineSeed;
    _Bool _isCertExists;
    _Bool _isUnionCodeByModifyPayWay;
    _Bool _isEnterBackground;
    _Bool _pauseUse;
    int _needAgreeCount;
    int _verifyCount;
    int _finishOrCtrlCount;
    int _offlineCount;
    UIViewController *_topViewController;
    double _brightness;
    NSString *_pin;
    NSString *_token;
    NSString *_appSource;
    NSString *_mode;
    NSString *_extraInfo;
    NSString *_bizTokenKey;
    NSString *_openResult;
    NSString *_modifyPwdUrl;
    NSString *_protocolUrl;
    JDPayPaymentCodeModel *_paymentCodeModel;
    JDPayPaymentCodeModel *_paymentWLCodeModel;
    JDPayPaymentCodeModel *_openVerifyCodeModel;
    NSString *_code;
    long long _originalBarStyle;
    JDPayCodeNavigationController *_presentedNavigationController;
    UIViewController *_startViewController;
    CDUnknownBlockType _payCallback;
    UINavigationController *_appNavigationController;
    UIViewController *_appRootViewController;
    NSString *_openTitleDesc;
    NSString *_commonTip;
    NSString *_payUseDesc;
    NSString *_payChannelTitle;
    NSArray *_payChannels;
    NSArray *_payWLChannels;
    NSString *_deductionDesc;
    NSString *_tdSignedData;
    JDPCEntranceReturnModel *_entranceReturnModel;
    NSArray *_showCodeList;
    NSString *_codeType;
    NSArray *_linkResourceList;
    NSString *_phoneDesc;
    JDPayPausePageInfoModel *_pausePageInfo;
    JDPayClosePayCodeModel *_closePayCodeModel;
    NSMutableArray *_dispatchTable;
}

+ (id)sharedManager;
@property(retain, nonatomic) NSMutableArray *dispatchTable; // @synthesize dispatchTable=_dispatchTable;
@property(retain, nonatomic) JDPayClosePayCodeModel *closePayCodeModel; // @synthesize closePayCodeModel=_closePayCodeModel;
@property(retain, nonatomic) JDPayPausePageInfoModel *pausePageInfo; // @synthesize pausePageInfo=_pausePageInfo;
@property(nonatomic) _Bool pauseUse; // @synthesize pauseUse=_pauseUse;
@property(copy, nonatomic) NSString *phoneDesc; // @synthesize phoneDesc=_phoneDesc;
@property(retain, nonatomic) NSArray *linkResourceList; // @synthesize linkResourceList=_linkResourceList;
@property(nonatomic) _Bool isEnterBackground; // @synthesize isEnterBackground=_isEnterBackground;
@property(nonatomic) _Bool isUnionCodeByModifyPayWay; // @synthesize isUnionCodeByModifyPayWay=_isUnionCodeByModifyPayWay;
@property(retain, nonatomic) NSString *codeType; // @synthesize codeType=_codeType;
@property(retain, nonatomic) NSArray *showCodeList; // @synthesize showCodeList=_showCodeList;
@property(nonatomic) _Bool isCertExists; // @synthesize isCertExists=_isCertExists;
@property(nonatomic) _Bool isCacheOffLineSeed; // @synthesize isCacheOffLineSeed=_isCacheOffLineSeed;
@property(retain, nonatomic) JDPCEntranceReturnModel *entranceReturnModel; // @synthesize entranceReturnModel=_entranceReturnModel;
@property(retain, nonatomic) NSString *tdSignedData; // @synthesize tdSignedData=_tdSignedData;
@property(copy, nonatomic) NSString *deductionDesc; // @synthesize deductionDesc=_deductionDesc;
@property(copy, nonatomic) NSArray *payWLChannels; // @synthesize payWLChannels=_payWLChannels;
@property(copy, nonatomic) NSArray *payChannels; // @synthesize payChannels=_payChannels;
@property(copy, nonatomic) NSString *payChannelTitle; // @synthesize payChannelTitle=_payChannelTitle;
@property(copy, nonatomic) NSString *payUseDesc; // @synthesize payUseDesc=_payUseDesc;
@property(copy, nonatomic) NSString *commonTip; // @synthesize commonTip=_commonTip;
@property(copy, nonatomic) NSString *openTitleDesc; // @synthesize openTitleDesc=_openTitleDesc;
@property(retain, nonatomic) UIViewController *appRootViewController; // @synthesize appRootViewController=_appRootViewController;
@property(nonatomic) __weak UINavigationController *appNavigationController; // @synthesize appNavigationController=_appNavigationController;
@property(copy, nonatomic) CDUnknownBlockType payCallback; // @synthesize payCallback=_payCallback;
@property(nonatomic) __weak UIViewController *startViewController; // @synthesize startViewController=_startViewController;
@property(retain, nonatomic) JDPayCodeNavigationController *presentedNavigationController; // @synthesize presentedNavigationController=_presentedNavigationController;
@property(nonatomic) long long originalBarStyle; // @synthesize originalBarStyle=_originalBarStyle;
@property(nonatomic) _Bool orginalNaviStatus; // @synthesize orginalNaviStatus=_orginalNaviStatus;
@property(copy, nonatomic) NSString *code; // @synthesize code=_code;
@property(retain, nonatomic) JDPayPaymentCodeModel *openVerifyCodeModel; // @synthesize openVerifyCodeModel=_openVerifyCodeModel;
@property(retain, nonatomic) JDPayPaymentCodeModel *paymentWLCodeModel; // @synthesize paymentWLCodeModel=_paymentWLCodeModel;
@property(retain, nonatomic) JDPayPaymentCodeModel *paymentCodeModel; // @synthesize paymentCodeModel=_paymentCodeModel;
@property(copy, nonatomic) NSString *protocolUrl; // @synthesize protocolUrl=_protocolUrl;
@property(copy, nonatomic) NSString *modifyPwdUrl; // @synthesize modifyPwdUrl=_modifyPwdUrl;
@property(copy, nonatomic) NSString *openResult; // @synthesize openResult=_openResult;
@property(copy, nonatomic) NSString *bizTokenKey; // @synthesize bizTokenKey=_bizTokenKey;
@property(copy, nonatomic) NSString *extraInfo; // @synthesize extraInfo=_extraInfo;
@property(copy, nonatomic) NSString *mode; // @synthesize mode=_mode;
@property(copy, nonatomic) NSString *appSource; // @synthesize appSource=_appSource;
@property(copy, nonatomic) NSString *token; // @synthesize token=_token;
@property(copy, nonatomic) NSString *pin; // @synthesize pin=_pin;
@property(nonatomic) double brightness; // @synthesize brightness=_brightness;
@property(retain, nonatomic) UIViewController *topViewController; // @synthesize topViewController=_topViewController;
@property(nonatomic) _Bool isRunning; // @synthesize isRunning=_isRunning;
@property(nonatomic) _Bool isFirstUnfinishedOrder; // @synthesize isFirstUnfinishedOrder=_isFirstUnfinishedOrder;
@property(nonatomic) int offlineCount; // @synthesize offlineCount=_offlineCount;
@property(nonatomic) int finishOrCtrlCount; // @synthesize finishOrCtrlCount=_finishOrCtrlCount;
@property(nonatomic) int verifyCount; // @synthesize verifyCount=_verifyCount;
@property(nonatomic) int needAgreeCount; // @synthesize needAgreeCount=_needAgreeCount;
- (void).cxx_destruct;
- (void)verifyTryOpenPaymentCodeWithCompletion:(CDUnknownBlockType)arg1;
- (void)verifyOpenPaymentCodeWithCompletion:(CDUnknownBlockType)arg1;
- (void)getServerTimeWithCompletion:(CDUnknownBlockType)arg1 showDialog:(_Bool)arg2;
- (void)getTDFingerprintStrWithData:(id)arg1 Completion:(CDUnknownBlockType)arg2;
- (void)verifyPay:(id)arg1 Completion:(CDUnknownBlockType)arg2;
- (id)getPaySetInfoListByArr:(id)arg1;
- (void)open:(id)arg1 Completion:(CDUnknownBlockType)arg2;
- (void)setPassword:(id)arg1 Completion:(CDUnknownBlockType)arg2;
- (void)authConfirm:(id)arg1 Completion:(CDUnknownBlockType)arg2;
- (void)auth:(id)arg1 Completion:(CDUnknownBlockType)arg2;
- (void)verifyCardNo:(id)arg1 Completion:(CDUnknownBlockType)arg2;
- (void)authBindCard:(id)arg1 Completion:(CDUnknownBlockType)arg2;
- (void)authVerify:(id)arg1 Completion:(CDUnknownBlockType)arg2;
- (void)queryUserInfo:(id)arg1 Completion:(CDUnknownBlockType)arg2;
- (void)aucSendMsg:(id)arg1 Completion:(CDUnknownBlockType)arg2;
- (id)dictByBankCardInfoModel:(id)arg1;
- (void)aucConfirm:(id)arg1 Completion:(CDUnknownBlockType)arg2;
- (id)certInfoModelByDict:(id)arg1;
- (void)verifyCardBin:(id)arg1 Completion:(CDUnknownBlockType)arg2;
- (void)binCard:(id)arg1 Completion:(CDUnknownBlockType)arg2;
- (void)getLatestCode:(id)arg1 completion:(CDUnknownBlockType)arg2 showDialog:(_Bool)arg3;
- (void)paycodePushData:(id)arg1 Completion:(CDUnknownBlockType)arg2 showDialog:(_Bool)arg3;
- (void)closeTryPaymentCodeCompletion:(CDUnknownBlockType)arg1;
- (void)closePaymentCodeCompletion:(CDUnknownBlockType)arg1 showDialog:(_Bool)arg2;
- (void)getPayChannelsWithCompletion:(CDUnknownBlockType)arg1 showDialog:(_Bool)arg2;
- (void)queryPaymentResultByCode:(id)arg1 Completion:(CDUnknownBlockType)arg2 showDialog:(_Bool)arg3;
- (void)modiyPayWayWith:(id)arg1 completion:(CDUnknownBlockType)arg2 showDialog:(_Bool)arg3;
- (void)repeatSmsCodeWithCompletion:(CDUnknownBlockType)arg1 showDialog:(_Bool)arg2;
- (void)setPaymentCodeStatus:(id)arg1 withCompletion:(CDUnknownBlockType)arg2 showDialog:(_Bool)arg3;
- (void)signAgreementWithCompletion:(CDUnknownBlockType)arg1 showDialog:(_Bool)arg2;
- (void)getTDRishkDataWithCallBack:(CDUnknownBlockType)arg1;
- (void)setDataWithDict:(id)arg1;
- (void)getEntranceWithTdSignData:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)getEntranceWithCompletion:(CDUnknownBlockType)arg1 showDialog:(_Bool)arg2;
- (void)showControlListsWithContrlModel:(id)arg1 buttonClick:(CDUnknownBlockType)arg2;
- (id)baseParamsExceptIosDeviceId;
- (id)deviceInfoDict;
- (id)codeInfoDict;
- (id)baseParams;
- (void)closePaymentWithCompletion:(CDUnknownBlockType)arg1;
- (void)cachePaymentCodeModel;
- (id)paymentCodeModelFromCache;
- (id)generatePaymentCode:(id)arg1;
- (id)generateNewPaymentCode:(id)arg1;
- (id)timeDifferenceWithServerTime:(id)arg1;
- (id)divideGroup:(id)arg1;
- (void)paycodePushData:(id)arg1;
- (id)init;
- (void)clearBizContext;
- (void)clearContext;

@end

