//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class JDPayBusNoUrlModel, JDPayPausePageInfoModel, JDPayTipInfoModel, NSArray, NSString;

@interface JDPayClosePayCodeModel : NSObject
{
    _Bool _pauseUse;
    NSString *_bizTokenKey;
    NSString *_topTipUrl;
    JDPayPausePageInfoModel *_pausePageInfo;
    NSArray *_linkResourceList;
    JDPayBusNoUrlModel *_url;
    JDPayTipInfoModel *_tipInfo;
}

@property(retain, nonatomic) JDPayTipInfoModel *tipInfo; // @synthesize tipInfo=_tipInfo;
@property(retain, nonatomic) JDPayBusNoUrlModel *url; // @synthesize url=_url;
@property(nonatomic) _Bool pauseUse; // @synthesize pauseUse=_pauseUse;
@property(retain, nonatomic) NSArray *linkResourceList; // @synthesize linkResourceList=_linkResourceList;
@property(retain, nonatomic) JDPayPausePageInfoModel *pausePageInfo; // @synthesize pausePageInfo=_pausePageInfo;
@property(retain, nonatomic) NSString *topTipUrl; // @synthesize topTipUrl=_topTipUrl;
@property(retain, nonatomic) NSString *bizTokenKey; // @synthesize bizTokenKey=_bizTokenKey;
- (void).cxx_destruct;

@end

