//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JDPQBaseReturnModel.h"

@class NSString;

@interface JDPQRiskReportReturnModel : JDPQBaseReturnModel
{
    NSString *_process;
    NSString *_riskCheck;
    NSString *_riskPhoneEnd;
    NSString *_riskTip;
    NSString *_openResult;
}

@property(copy, nonatomic) NSString *openResult; // @synthesize openResult=_openResult;
@property(copy, nonatomic) NSString *riskTip; // @synthesize riskTip=_riskTip;
@property(copy, nonatomic) NSString *riskPhoneEnd; // @synthesize riskPhoneEnd=_riskPhoneEnd;
@property(copy, nonatomic) NSString *riskCheck; // @synthesize riskCheck=_riskCheck;
@property(copy, nonatomic) NSString *process; // @synthesize process=_process;
- (void).cxx_destruct;

@end

