//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JDPQBaseReturnModel.h"

@class NSString;

@interface JDPQVisitReturnModel : JDPQBaseReturnModel
{
    NSString *_homeUrl;
    NSString *_connectErrorUrl;
    NSString *_buryData;
}

@property(copy, nonatomic) NSString *buryData; // @synthesize buryData=_buryData;
@property(copy, nonatomic) NSString *connectErrorUrl; // @synthesize connectErrorUrl=_connectErrorUrl;
@property(copy, nonatomic) NSString *homeUrl; // @synthesize homeUrl=_homeUrl;
- (void).cxx_destruct;

@end

