//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class JDCheckLogin, JDOpenURLModel;

@interface JDProtocolHandleManager : NSObject
{
    JDCheckLogin *_checkLogin;
    JDOpenURLModel *_currentOpenURLModel;
}

+ (void)checkLoginStateFinished:(long long)arg1 openURLModel:(id)arg2;
+ (_Bool)handleOpenURL:(id)arg1 sourceApplication:(id)arg2 webView:(id)arg3 completion:(CDUnknownBlockType)arg4 checkedLoginState:(_Bool)arg5;
+ (_Bool)handleOpenURL:(id)arg1 sourceApplication:(id)arg2 webView:(id)arg3 completion:(CDUnknownBlockType)arg4;
+ (_Bool)handleOpenURL:(id)arg1 webView:(id)arg2 completion:(CDUnknownBlockType)arg3;
+ (_Bool)handleOpenURL:(id)arg1 completion:(CDUnknownBlockType)arg2;
+ (_Bool)handleOpenURL:(id)arg1 sourceApplication:(id)arg2;
+ (_Bool)handleOpenURL:(id)arg1;
+ (id)sharedInstance;
@property(retain, nonatomic) JDOpenURLModel *currentOpenURLModel; // @synthesize currentOpenURLModel=_currentOpenURLModel;
- (void).cxx_destruct;
- (void)didFinishInToastView:(id)arg1;
- (void)didCancelInToastView:(id)arg1;
- (void)showAlert;
- (_Bool)reopenURL:(id)arg1 checkedLoginState:(_Bool)arg2;
- (_Bool)reopenURL:(id)arg1;
- (id)checkLoginDAO;

@end

