//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "RCTBridgeModule-Protocol.h"

@class JDSHUnplGenerator, NSString, RCTBridge;
@protocol OS_dispatch_queue;

@interface JDReactNativeMtaReportModule : NSObject <RCTBridgeModule>
{
}

+ (id)__rct_export__1416;
+ (id)__rct_export__1335;
+ (id)__rct_export__1144;
+ (id)__rct_export__953;
+ (id)__rct_export__802;
+ (id)__rct_export__541;
+ (id)__rct_export__340;
+ (void)load;
+ (id)moduleName;
- (void)sendVirtualOrder:(id)arg1;
- (void)sendPvData:(id)arg1 successCB:(CDUnknownBlockType)arg2 errorCB:(CDUnknownBlockType)arg3;
- (void)sendClickDataWithExt:(id)arg1 successCB:(CDUnknownBlockType)arg2 errorCB:(CDUnknownBlockType)arg3;
- (void)sendClickData:(id)arg1 successCB:(CDUnknownBlockType)arg2 errorCB:(CDUnknownBlockType)arg3;
- (void)startUnplRequestWithSKU:(id)arg1 successCB:(CDUnknownBlockType)arg2 errorCB:(CDUnknownBlockType)arg3;
@property(retain, nonatomic) JDSHUnplGenerator *unplGenerator;
- (void)savePageInfoWithSKU:(id)arg1 successCB:(CDUnknownBlockType)arg2 errorCB:(CDUnknownBlockType)arg3;
- (void)sendOrderData:(id)arg1 successCB:(CDUnknownBlockType)arg2 errorCB:(CDUnknownBlockType)arg3;
- (id)init;

// Remaining properties
@property(readonly, nonatomic) __weak RCTBridge *bridge;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *methodQueue;
@property(readonly) Class superclass;

@end

