//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "RCTBridgeModule-Protocol.h"

@class JDBaseToastView, NSString, RCTBridge;
@protocol OS_dispatch_queue;

@interface JDReactNativePayModule : NSObject <RCTBridgeModule>
{
    JDBaseToastView *_toast;
    CDUnknownBlockType _noPwdSucBlock;
    CDUnknownBlockType _noPwdErrorBlock;
}

+ (id)__rct_export__2794;
+ (id)__rct_export__2543;
+ (id)__rct_export__2362;
+ (id)__rct_export__1961;
+ (id)__rct_export__1720;
+ (void)load;
+ (id)moduleName;
@property(copy, nonatomic) CDUnknownBlockType noPwdErrorBlock; // @synthesize noPwdErrorBlock=_noPwdErrorBlock;
@property(copy, nonatomic) CDUnknownBlockType noPwdSucBlock; // @synthesize noPwdSucBlock=_noPwdSucBlock;
- (void).cxx_destruct;
- (void)wxFreePay:(id)arg1 successCB:(CDUnknownBlockType)arg2 errorCB:(CDUnknownBlockType)arg3;
- (void)getAccountDictWithPin:(id)arg1 successCB:(CDUnknownBlockType)arg2 errorCB:(CDUnknownBlockType)arg3;
- (void)thirdPay:(id)arg1 successCB:(CDUnknownBlockType)arg2 errorCB:(CDUnknownBlockType)arg3;
- (void)startPay:(id)arg1 successCB:(CDUnknownBlockType)arg2 errorCB:(CDUnknownBlockType)arg3;
- (void)wxCheck:(CDUnknownBlockType)arg1 errorCB:(CDUnknownBlockType)arg2;
- (void)didWxPayFaild:(id)arg1;
- (void)didWxPayCancel:(id)arg1;
- (void)didWxPaySuccess:(id)arg1;
- (id)convertBaseReqToDic:(id)arg1;
- (id)init;
- (void)dealloc;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *methodQueue;

// Remaining properties
@property(readonly, nonatomic) __weak RCTBridge *bridge;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

