//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "RCTBridgeModule-Protocol.h"

@class JDSHAudioController, NSString, RCTBridge;
@protocol OS_dispatch_queue;

@interface JDReactNativeMultiMediaModule : NSObject <RCTBridgeModule>
{
    JDSHAudioController *_audioController;
}

+ (id)__rct_export__3168;
+ (id)__rct_export__2847;
+ (id)__rct_export__2406;
+ (id)__rct_export__2015;
+ (id)__rct_export__1884;
+ (id)__rct_export__1603;
+ (id)__rct_export__1402;
+ (id)__rct_export__1261;
+ (id)__rct_export__920;
+ (void)load;
+ (id)moduleName;
@property(retain, nonatomic) JDSHAudioController *audioController; // @synthesize audioController=_audioController;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *methodQueue;
- (void)pickPhoto:(id)arg1 successBlock:(CDUnknownBlockType)arg2 responseError:(CDUnknownBlockType)arg3;
- (void)showFullScreenVideoView:(id)arg1 successBlock:(CDUnknownBlockType)arg2 responseError:(CDUnknownBlockType)arg3;
- (void)captureVideo:(id)arg1 successBlock:(CDUnknownBlockType)arg2 responseError:(CDUnknownBlockType)arg3;
- (void)scanCode:(id)arg1 successBlock:(CDUnknownBlockType)arg2 responseError:(CDUnknownBlockType)arg3;
- (void)stopPlaying:(CDUnknownBlockType)arg1 responseError:(CDUnknownBlockType)arg2;
- (void)startPlaying:(id)arg1 successBlock:(CDUnknownBlockType)arg2 responseError:(CDUnknownBlockType)arg3;
- (void)deleteRecordingFile:(id)arg1 successBlock:(CDUnknownBlockType)arg2 responseError:(CDUnknownBlockType)arg3;
- (void)stopRecording:(CDUnknownBlockType)arg1 responseError:(CDUnknownBlockType)arg2;
- (void)startRecording:(id)arg1 successBlock:(CDUnknownBlockType)arg2 responseError:(CDUnknownBlockType)arg3;
- (_Bool)canRecord;
- (void)showToast;
- (void)executeBlockOnMainQueue:(CDUnknownBlockType)arg1;
- (id)init;

// Remaining properties
@property(readonly, nonatomic) __weak RCTBridge *bridge;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

