//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "RCTBridgeModule-Protocol.h"

@class NSString, RCTBridge;
@protocol OS_dispatch_queue;

@interface JDReactRNFloorModule : NSObject <RCTBridgeModule>
{
}

+ (id)__rct_export__261;
+ (id)__rct_export__170;
+ (void)load;
+ (id)moduleName;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *methodQueue;
- (id)constantsToExport;
- (void)invokeNativeMethod:(id)arg1 methodId:(id)arg2 params:(id)arg3 resolver:(CDUnknownBlockType)arg4 rejecter:(CDUnknownBlockType)arg5;
- (void)setFloorHeight:(id)arg1 width:(int)arg2 height:(int)arg3;

// Remaining properties
@property(readonly, nonatomic) __weak RCTBridge *bridge;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

