//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@protocol OS_dispatch_queue, OS_dispatch_semaphore;

@interface JDSCUID : NSObject
{
    NSObject<OS_dispatch_semaphore> *_sema;
    NSObject<OS_dispatch_queue> *_syncQueue;
}

+ (id)SDKVersion;
+ (id)bundleSeedID;
+ (id)groupID;
+ (void)getCuidOnComplete:(CDUnknownBlockType)arg1;
+ (void)getCuidOnLocal:(_Bool)arg1 OnComplete:(CDUnknownBlockType)arg2;
+ (void)addRequestToQueueWithGetCuidOnLocal:(_Bool)arg1 requestComplete:(CDUnknownBlockType)arg2;
+ (id)getCachedCUID;
+ (id)sharedInstance;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *syncQueue; // @synthesize syncQueue=_syncQueue;
@property(retain, nonatomic) NSObject<OS_dispatch_semaphore> *sema; // @synthesize sema=_sema;
- (void).cxx_destruct;
- (void)initSemaphore;

@end

