//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class JDImageView, JDShopModel, NSMutableArray, UIScrollView;

@interface JDShopHeaderTagView : UIView
{
    _Bool _isHasBigPromotion;
    NSMutableArray *_arrayTagItem;
    long long _currentTag;
    JDImageView *_backImgView;
    UIScrollView *_tagItemScrollView;
    UIView *_bottomLine;
    double _currentItemWidth;
    JDShopModel *_shopModel;
}

@property(retain, nonatomic) JDShopModel *shopModel; // @synthesize shopModel=_shopModel;
@property(nonatomic) double currentItemWidth; // @synthesize currentItemWidth=_currentItemWidth;
@property(retain, nonatomic) UIView *bottomLine; // @synthesize bottomLine=_bottomLine;
@property(nonatomic) _Bool isHasBigPromotion; // @synthesize isHasBigPromotion=_isHasBigPromotion;
@property(retain, nonatomic) UIScrollView *tagItemScrollView; // @synthesize tagItemScrollView=_tagItemScrollView;
@property(retain, nonatomic) JDImageView *backImgView; // @synthesize backImgView=_backImgView;
@property(nonatomic) long long currentTag; // @synthesize currentTag=_currentTag;
@property(retain, nonatomic) NSMutableArray *arrayTagItem; // @synthesize arrayTagItem=_arrayTagItem;
- (void).cxx_destruct;
- (id)getHeaderItenNameByIndex:(long long)arg1;
- (void)setSubViewDelegate:(id)arg1;
- (void)setBottomLineWithSelectedTag:(long long)arg1 animation:(_Bool)arg2;
- (void)setBigPromotionFaceHidden:(_Bool)arg1 imageUrl:(id)arg2;
- (void)setCurrentSelectedTag:(long long)arg1;
- (void)setHeaderTagNumData:(id)arg1;
- (void)setHeaderTagData:(id)arg1 isHasBigPromotion:(_Bool)arg2;
- (void)initSubViews;
- (void)layoutHeaderTagView;
- (id)initWithFrame:(struct CGRect)arg1 withType:(long long)arg2;

@end

