//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <JDDBaseModule/JDModel.h>

@class NSArray, NSNumber, NSString;

@interface JDShopInSearchCategoryInfoModel : JDModel
{
    _Bool _isOpen;
    NSNumber *_categoryId;
    NSNumber *_shopId;
    NSString *_title;
    NSArray *_subCategories;
}

@property(retain, nonatomic) NSArray *subCategories; // @synthesize subCategories=_subCategories;
@property(nonatomic) _Bool isOpen; // @synthesize isOpen=_isOpen;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSNumber *shopId; // @synthesize shopId=_shopId;
@property(retain, nonatomic) NSNumber *categoryId; // @synthesize categoryId=_categoryId;
- (void).cxx_destruct;
- (void)encodeModelWithDic:(id)arg1;

@end

