//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class JDStoreNetwork, JDThemeModel, NSDate;

@interface JDThemeDAO : NSObject
{
    JDStoreNetwork *_network;
    NSDate *_requestTime;
    long long _version;
    JDThemeModel *_model;
    CDUnknownBlockType _successBlock;
    long long _times;
}

+ (void)willEnterForeground:(id)arg1;
+ (void)switchTabbar:(id)arg1;
+ (void)requestData:(CDUnknownBlockType)arg1;
+ (void)load;
+ (id)sharedInstance;
@property(nonatomic) long long times; // @synthesize times=_times;
@property(copy, nonatomic) CDUnknownBlockType successBlock; // @synthesize successBlock=_successBlock;
@property(retain, nonatomic) JDThemeModel *model; // @synthesize model=_model;
@property(nonatomic) long long version; // @synthesize version=_version;
@property(retain, nonatomic) NSDate *requestTime; // @synthesize requestTime=_requestTime;
@property(retain, nonatomic) JDStoreNetwork *network; // @synthesize network=_network;
- (void).cxx_destruct;
- (void)callBack;
- (void)downLoadImage:(id)arg1;
- (void)requestFailed;
- (void)requestFinished:(id)arg1;
- (void)requestNavigationBarInfo;
- (void)dealloc;

@end

