//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface JDThemeModule : NSObject
{
}

+ (id)routerHandle_JDThemeModule_navigationBarTitleColorType:(id)arg1 callback:(CDUnknownBlockType)arg2;
+ (id)routerHandle_JDThemeModule_navigationBarIcon:(id)arg1 callback:(CDUnknownBlockType)arg2;
+ (id)routerHandle_JDThemeModule_navigationBarBackgroundImage:(id)arg1 callback:(CDUnknownBlockType)arg2;
+ (id)routerHandle_JDThemeModule_navigationBarSwitchStatus:(id)arg1 callback:(CDUnknownBlockType)arg2;
+ (id)routerHandle_JDThemeModule_releaseNavigationBarBlock:(id)arg1 callback:(CDUnknownBlockType)arg2;

@end

