//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JDUGCNewInterlocutionContentAllTextCell.h"

@class JDUGCNewInterlocutionContentOnePicModel, JDUGCNewInterlocutionImageView;

@interface JDUGCNewInterlocutionContentOnePicCell : JDUGCNewInterlocutionContentAllTextCell
{
    JDUGCNewInterlocutionImageView *_rightImageView;
    JDUGCNewInterlocutionContentOnePicModel *_model;
}

@property(retain, nonatomic) JDUGCNewInterlocutionContentOnePicModel *model; // @synthesize model=_model;
- (void).cxx_destruct;
- (void)assignValue:(id)arg1;
- (void)layoutSubviews;
- (void)setupViews;

@end

