//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"

@class JDVFSettingItemCollectionViewCell, NSMutableArray, NSString, UIButton, UICollectionView;
@protocol JDVFSettingHairAndFaceDelegate;

@interface JDVFSettingHairAndFaceView : UIView <UICollectionViewDataSource, UICollectionViewDelegate>
{
    UIView *headView;
    UIButton *hairButton;
    UIButton *faceButton;
    UIView *buttonLine;
    NSMutableArray *faceList;
    UIView *hairView;
    UIView *faceView;
    UICollectionView *hairCollectionView;
    UIButton *storeHair;
    UIButton *storeFace;
    UICollectionView *faceCollectionView;
    unsigned long long faceGap;
    JDVFSettingItemCollectionViewCell *selectedFaceCell;
    int hairIndex;
    int faceIndex;
    int _genderType;
    NSMutableArray *hairList;
    id <JDVFSettingHairAndFaceDelegate> _delegate;
    long long _currentHaidIndex;
}

@property(nonatomic) long long currentHaidIndex; // @synthesize currentHaidIndex=_currentHaidIndex;
@property(nonatomic) int genderType; // @synthesize genderType=_genderType;
@property(nonatomic) __weak id <JDVFSettingHairAndFaceDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSMutableArray *hairList; // @synthesize hairList;
- (void).cxx_destruct;
- (_Bool)unzipAndDeleteHairFile:(id)arg1 andIndex:(long long)arg2;
- (void)downloadHairZipDataFailed:(long long)arg1;
- (void)downLoadHairFile:(id)arg1 andPath:(id)arg2 andIndex:(long long)arg3;
- (void)downLoadHairIndex:(long long)arg1;
- (void)reloadHairAfterDownload;
- (void)resetClickCellIndex;
- (void)reloadHair:(int)arg1 andFace:(int)arg2 andGender:(int)arg3;
- (void)setHeadViewShow:(_Bool)arg1;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (void)onClickStoreHair:(id)arg1;
- (void)onClickStoreFace:(id)arg1;
- (void)onClickFaceButton:(id)arg1;
- (void)onClickHairButton:(id)arg1;
- (void)setFace;
- (void)setHair;
- (void)initViews;
- (id)initWithFrame:(struct CGRect)arg1 andGender:(int)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

