//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class AVAssetWriter, AVAssetWriterInput, NSDictionary, NSURL;
@protocol JDVideoWriterDelegate, OS_dispatch_queue;

@interface JDVideoWriter : NSObject
{
    _Bool _writing;
    id <JDVideoWriterDelegate> _delegate;
    long long _videoOrientation;
    long long _writeState;
    NSURL *_videoUrl;
    NSObject<OS_dispatch_queue> *_writeQueue;
    AVAssetWriter *_assetWriter;
    AVAssetWriterInput *_assetWriterVideoInput;
    AVAssetWriterInput *_assetWriterAudioInput;
    NSDictionary *_videoCompressionSettings;
    NSDictionary *_audioCompressionSettings;
}

@property(nonatomic) _Bool writing; // @synthesize writing=_writing;
@property(retain, nonatomic) NSDictionary *audioCompressionSettings; // @synthesize audioCompressionSettings=_audioCompressionSettings;
@property(retain, nonatomic) NSDictionary *videoCompressionSettings; // @synthesize videoCompressionSettings=_videoCompressionSettings;
@property(retain, nonatomic) AVAssetWriterInput *assetWriterAudioInput; // @synthesize assetWriterAudioInput=_assetWriterAudioInput;
@property(retain, nonatomic) AVAssetWriterInput *assetWriterVideoInput; // @synthesize assetWriterVideoInput=_assetWriterVideoInput;
@property(retain, nonatomic) AVAssetWriter *assetWriter; // @synthesize assetWriter=_assetWriter;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *writeQueue; // @synthesize writeQueue=_writeQueue;
@property(retain, nonatomic) NSURL *videoUrl; // @synthesize videoUrl=_videoUrl;
@property(nonatomic) long long writeState; // @synthesize writeState=_writeState;
@property(nonatomic) long long videoOrientation; // @synthesize videoOrientation=_videoOrientation;
@property(nonatomic) __weak id <JDVideoWriterDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)appendSampleBuffer:(struct opaqueCMSampleBuffer *)arg1 ofMediaType:(id)arg2;
- (void)outputSampleBuffer:(struct opaqueCMSampleBuffer *)arg1 ofMediaType:(id)arg2;
- (void)creatWriter;
- (void)fail;
- (void)cancelWriting;
- (void)stopWriting;
- (void)startWriting;
- (struct CGAffineTransform)videoTramsformWithOrientation:(long long)arg1;
- (void)configParameterWithSize:(struct CGSize)arg1;
- (id)initWithURL:(id)arg1 outputSize:(struct CGSize)arg2;
- (void)dealloc;
- (void)destroy;

@end

