//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSString;

@interface JDViewKitEventModel : NSObject
{
    NSString *_eventType;
    NSDictionary *_eventJumpParams;
    NSDictionary *_extMtaParams;
    NSString *_eventKey;
}

@property(copy, nonatomic) NSString *eventKey; // @synthesize eventKey=_eventKey;
@property(retain, nonatomic) NSDictionary *extMtaParams; // @synthesize extMtaParams=_extMtaParams;
@property(copy, nonatomic) NSDictionary *eventJumpParams; // @synthesize eventJumpParams=_eventJumpParams;
@property(copy, nonatomic) NSString *eventType; // @synthesize eventType=_eventType;
- (void).cxx_destruct;
- (id)initWithEventDict:(id)arg1 dataItem:(id)arg2;

@end

