//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UIWebViewDelegate-Protocol.h"
#import "WKNavigationDelegate-Protocol.h"
#import "WKScriptMessageHandler-Protocol.h"
#import "WKUIDelegate-Protocol.h"

@class JDWebViewAudioSessionManager, JDWebViewJSBridge, NSString, NSURL, NSURLRequest, UIAlertController, UILabel, UIScrollView, WKProcessPool, WebViewJavascriptBridge;
@protocol JDWebViewDelegate, JDWebViewJSBridgeProtocol;

@interface JDWebView : UIView <UIWebViewDelegate, WKNavigationDelegate, WKUIDelegate, WKScriptMessageHandler>
{
    id _webView;
    WebViewJavascriptBridge *_bridge;
    UILabel *label;
    NSString *_callerType;
    long long _historyLength;
    JDWebViewJSBridge *_jsBridge;
    _Bool _scalesPageToFit;
    _Bool _usedUIWebView;
    _Bool _isWKBelow9;
    _Bool _debugEnable;
    id <JDWebViewDelegate> _delegate;
    id <JDWebViewDelegate> _delegateProxy;
    id <JDWebViewJSBridgeProtocol> _customJsDelegate;
    NSString *_title;
    double _estimatedProgress;
    NSURL *_URL;
    NSString *_customUserAgent;
    NSURLRequest *_request;
    UIAlertController *_alertCtrl;
    CDUnknownBlockType _alertBlock;
    CDUnknownBlockType _confirmBlock;
    CDUnknownBlockType _textInputBlock;
    WKProcessPool *_processPool;
}

+ (void)initialize;
@property(retain, nonatomic) WKProcessPool *processPool; // @synthesize processPool=_processPool;
@property(nonatomic) _Bool debugEnable; // @synthesize debugEnable=_debugEnable;
@property(copy, nonatomic) CDUnknownBlockType textInputBlock; // @synthesize textInputBlock=_textInputBlock;
@property(copy, nonatomic) CDUnknownBlockType confirmBlock; // @synthesize confirmBlock=_confirmBlock;
@property(copy, nonatomic) CDUnknownBlockType alertBlock; // @synthesize alertBlock=_alertBlock;
@property(retain, nonatomic) UIAlertController *alertCtrl; // @synthesize alertCtrl=_alertCtrl;
@property(retain, nonatomic) NSURLRequest *request; // @synthesize request=_request;
@property(copy, nonatomic) NSString *customUserAgent; // @synthesize customUserAgent=_customUserAgent;
@property(readonly, nonatomic) JDWebViewJSBridge *jsBridge; // @synthesize jsBridge=_jsBridge;
@property(retain, nonatomic) NSURL *URL; // @synthesize URL=_URL;
@property(nonatomic) double estimatedProgress; // @synthesize estimatedProgress=_estimatedProgress;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(readonly, nonatomic) _Bool isWKBelow9; // @synthesize isWKBelow9=_isWKBelow9;
@property(readonly, nonatomic, getter=isUsingUIWebView) _Bool usedUIWebView; // @synthesize usedUIWebView=_usedUIWebView;
@property(nonatomic) __weak id <JDWebViewJSBridgeProtocol> customJsDelegate; // @synthesize customJsDelegate=_customJsDelegate;
@property(retain, nonatomic) id <JDWebViewDelegate> delegateProxy; // @synthesize delegateProxy=_delegateProxy;
@property(nonatomic) __weak id <JDWebViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)webView:(id)arg1 createWebViewWithConfiguration:(id)arg2 forNavigationAction:(id)arg3 windowFeatures:(id)arg4;
- (void)webView:(id)arg1 runJavaScriptTextInputPanelWithPrompt:(id)arg2 defaultText:(id)arg3 initiatedByFrame:(id)arg4 completionHandler:(CDUnknownBlockType)arg5;
- (void)webView:(id)arg1 runJavaScriptConfirmPanelWithMessage:(id)arg2 initiatedByFrame:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)webView:(id)arg1 runJavaScriptAlertPanelWithMessage:(id)arg2 initiatedByFrame:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)webViewDidFinishLoad:(id)arg1;
- (void)webViewDidStartLoad:(id)arg1;
- (_Bool)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3;
- (void)webView:(id)arg1 decidePolicyForNavigationResponse:(id)arg2 decisionHandler:(CDUnknownBlockType)arg3;
- (void)webView:(id)arg1 didReceiveServerRedirectForProvisionalNavigation:(id)arg2;
- (void)webViewWebContentProcessDidTerminate:(id)arg1;
- (void)webView:(id)arg1 didCommitNavigation:(id)arg2;
- (void)webView:(id)arg1 didFailProvisionalNavigation:(id)arg2 withError:(id)arg3;
- (void)webView:(id)arg1 didFailNavigation:(id)arg2 withError:(id)arg3;
- (void)webView:(id)arg1 didFinishNavigation:(id)arg2;
- (void)webView:(id)arg1 didStartProvisionalNavigation:(id)arg2;
- (void)webView:(id)arg1 decidePolicyForNavigationAction:(id)arg2 decisionHandler:(CDUnknownBlockType)arg3;
- (_Bool)jdWebViewShouldStartLoadWithRequest:(id)arg1 navigationType:(long long)arg2;
- (void)jdWebViewDidFailLoadWithError:(id)arg1;
- (void)jdWebViewDidStartLoad;
- (void)jdWebViewDidFinishLoad;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)injectedExclusiveMediaJS;
- (void)setWebViewDelegate:(id)arg1;
- (id)wkWebView;
- (id)uiWebView;
- (void)setupSubViews;
- (void)debugEnable:(_Bool)arg1;
- (void)registerHandler:(id)arg1 handler:(CDUnknownBlockType)arg2;
- (id)stringByEvaluatingJavaScriptFromString:(id)arg1;
- (void)evaluateJavaScript:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)goForward;
- (_Bool)canGoForward;
- (void)goBack;
- (_Bool)canGoBack;
@property(readonly, nonatomic, getter=isLoading) _Bool loading;
- (void)stopLoading;
- (void)reload;
- (void)loadHTMLString:(id)arg1 baseURL:(id)arg2;
- (void)loadRequest:(id)arg1;
- (void)userContentController:(id)arg1 didReceiveScriptMessage:(id)arg2;
- (void)p_specialHandlingOfFurtherRequestsForWk:(id)arg1;
- (id)p_specialHandlingOfIntialReuqestForWk:(id)arg1;
@property(readonly, nonatomic) long long historyLength;
@property(readonly, nonatomic) id realWebView;
@property(readonly, nonatomic) UIScrollView *scrollView;
@property(nonatomic) _Bool scalesPageToFit; // @synthesize scalesPageToFit=_scalesPageToFit;
- (id)initWithFrame:(struct CGRect)arg1 htmlString:(id)arg2 UIWebViewUsed:(_Bool)arg3;
- (id)initWithFrame:(struct CGRect)arg1 callerType:(id)arg2 urlString:(id)arg3 wkSwitchProvider:(id)arg4;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)doJavaScriptPannelCompletionBlock;
- (void)remove;
- (void)dealloc;
@property(retain, nonatomic) JDWebViewAudioSessionManager *audioSessionManager;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

