//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JDViewController.h"

#import "JDFooterRefreshViewDelegate-Protocol.h"
#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"

@class JDXFanFooterRefreshView, JDXFanHomeFeedsListView, JDXFanHomeViewDataService, NSMutableDictionary, NSString, UIScrollView;
@protocol JDXFanHomeFeedsListViewControllerDelegate;

@interface JDXFanHomeFeedsListViewController : JDViewController <UICollectionViewDataSource, UICollectionViewDelegate, JDFooterRefreshViewDelegate>
{
    _Bool _hasNoMoreData;
    JDXFanHomeViewDataService *_dataService;
    UIScrollView *_scrollV;
    long long _pageIndex;
    id <JDXFanHomeFeedsListViewControllerDelegate> _delegate;
    JDXFanHomeFeedsListView *_vcView;
    JDXFanFooterRefreshView *_loadingFooterView;
    NSMutableDictionary *_exposeContentID_ExposeModelDic;
    CDUnknownBlockType _scrollToTopCompleteBlock;
}

@property(copy, nonatomic) CDUnknownBlockType scrollToTopCompleteBlock; // @synthesize scrollToTopCompleteBlock=_scrollToTopCompleteBlock;
@property(retain, nonatomic) NSMutableDictionary *exposeContentID_ExposeModelDic; // @synthesize exposeContentID_ExposeModelDic=_exposeContentID_ExposeModelDic;
@property(retain, nonatomic) JDXFanFooterRefreshView *loadingFooterView; // @synthesize loadingFooterView=_loadingFooterView;
@property(retain, nonatomic) JDXFanHomeFeedsListView *vcView; // @synthesize vcView=_vcView;
@property(nonatomic) _Bool hasNoMoreData; // @synthesize hasNoMoreData=_hasNoMoreData;
@property(nonatomic) id <JDXFanHomeFeedsListViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) long long pageIndex; // @synthesize pageIndex=_pageIndex;
@property(nonatomic) __weak UIScrollView *scrollV; // @synthesize scrollV=_scrollV;
@property(nonatomic) __weak JDXFanHomeViewDataService *dataService; // @synthesize dataService=_dataService;
- (void).cxx_destruct;
- (_Bool)isCurrentSelectedTab;
- (_Bool)isParentScrollToFixedSectionHeader;
- (CDUnknownBlockType)similarJumpBlock;
- (CDUnknownBlockType)authorJumpBlock;
- (CDUnknownBlockType)subContentClickCallBack;
- (_Bool)footerRefreshViewDataSourceIsLoading:(id)arg1;
- (void)footerRefreshViewDidTriggerRefresh;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (void)collectionView:(id)arg1 willDisplayCell:(id)arg2 forItemAtIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)homeMainScrollLessFixedLocationNotify:(id)arg1;
- (void)onButtonScrollToTop:(id)arg1;
- (void)exposeContents;
- (void)exposeContent:(id)arg1 atIndex:(long long)arg2;
- (id)popExposeContents;
- (void)failLoadDataWithError:(id)arg1;
- (void)reloadData;
- (void)successLoadData;
- (void)reconnect;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)didEndScrollOut;
- (void)didEndScrollIn;
- (void)willDisappear;
- (void)didDisappear;
- (void)didAppear;
- (void)scrollToTopWithCompleteBlock:(CDUnknownBlockType)arg1;
- (void)updateFootViewFrame;
- (void)loadView;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)addObservers;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

