//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewFlowLayout.h>

@class NSArray;

@interface JDXFANCardFlowCollectionViewFlowLayout : UICollectionViewFlowLayout
{
    long long _selectedIndex;
    NSArray *_twoItemMoveMinimumToMaxLocation;
    double _itemSpaceBuf;
    double _leftInsetBuf;
    double _rightInsetBuf;
    double _centerYOffsetBuf;
    long long _itemCountBuf;
    double _normalItemAppendSpaceWidthBuf;
    struct CGSize _normalSizeBuf;
    struct CGSize _maxScaleSizeBuf;
    struct CGSize _footerSizeBuf;
}

@property(nonatomic) double normalItemAppendSpaceWidthBuf; // @synthesize normalItemAppendSpaceWidthBuf=_normalItemAppendSpaceWidthBuf;
@property(nonatomic) long long itemCountBuf; // @synthesize itemCountBuf=_itemCountBuf;
@property(nonatomic) double centerYOffsetBuf; // @synthesize centerYOffsetBuf=_centerYOffsetBuf;
@property(nonatomic) double rightInsetBuf; // @synthesize rightInsetBuf=_rightInsetBuf;
@property(nonatomic) double leftInsetBuf; // @synthesize leftInsetBuf=_leftInsetBuf;
@property(nonatomic) double itemSpaceBuf; // @synthesize itemSpaceBuf=_itemSpaceBuf;
@property(nonatomic) struct CGSize footerSizeBuf; // @synthesize footerSizeBuf=_footerSizeBuf;
@property(nonatomic) struct CGSize maxScaleSizeBuf; // @synthesize maxScaleSizeBuf=_maxScaleSizeBuf;
@property(nonatomic) struct CGSize normalSizeBuf; // @synthesize normalSizeBuf=_normalSizeBuf;
@property(retain, nonatomic) NSArray *twoItemMoveMinimumToMaxLocation; // @synthesize twoItemMoveMinimumToMaxLocation=_twoItemMoveMinimumToMaxLocation;
@property(readonly, nonatomic) long long selectedIndex; // @synthesize selectedIndex=_selectedIndex;
- (void).cxx_destruct;
- (void)scrollToMaxLocationForIndex:(long long)arg1 animated:(_Bool)arg2;
- (id)maxItemMoveToMaxLocationModelWithOne:(id)arg1 anotherOne:(id)arg2;
- (void)resetSelectedIndex;
- (id)myLayoutAttributesForElementsInRect:(struct CGRect)arg1 isCurrentDisplayRect:(_Bool)arg2;
- (_Bool)shouldInvalidateLayoutForBoundsChange;
- (id)layoutAttributesForElementsInRect:(struct CGRect)arg1;
- (struct CGPoint)targetContentOffsetForProposedContentOffset:(struct CGPoint)arg1 withScrollingVelocity:(struct CGPoint)arg2;
- (struct CGSize)collectionViewContentSize;
- (void)prepareLayout;
- (long long)itemCount;
- (double)rightInset;
- (double)leftInset;
- (double)itemSpace;
- (struct CGSize)footerSize;
- (struct CGSize)maxScaleSize;
- (struct CGSize)normalSize;
- (double)centerYOffset;
- (double)screenWidth;
- (id)delegate;
- (void)preReload;
- (id)init;

@end

