//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JDXFanHomeCell_Base.h"

@class JDXFanPageSegmentView;

@interface JDXFanHomeCell_Tabbar : JDXFanHomeCell_Base
{
    JDXFanPageSegmentView *_segV;
}

+ (struct CGSize)fixedSize;
@property(retain, nonatomic) JDXFanPageSegmentView *segV; // @synthesize segV=_segV;
- (void).cxx_destruct;
- (void)setXfanHomeDataService:(id)arg1;
- (void)setDataModel:(id)arg1;
- (void)layoutSubviews;
- (void)initSubViews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

