//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class JDStoreNetwork, JDXFanCardCollectionResponseDataModel, NSOperationQueue, NSString;

@interface JDXFanCardCollectionViewDataService : NSObject
{
    JDXFanCardCollectionResponseDataModel *_responseM;
    NSString *_channelId;
    JDStoreNetwork *_network;
    NSOperationQueue *_queueNetwork;
}

@property(retain, nonatomic) NSOperationQueue *queueNetwork; // @synthesize queueNetwork=_queueNetwork;
@property(retain, nonatomic) JDStoreNetwork *network; // @synthesize network=_network;
@property(retain, nonatomic) NSString *channelId; // @synthesize channelId=_channelId;
@property(retain, nonatomic) JDXFanCardCollectionResponseDataModel *responseM; // @synthesize responseM=_responseM;
- (void).cxx_destruct;
- (id)themeColor;
- (void)requestCardCollectionWithPage:(long long)arg1 completeBlock:(CDUnknownBlockType)arg2;
- (id)initWithChannelId:(id)arg1;
- (void)dealloc;

@end

