//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;

@interface JZGuessYouWantRequestParam : NSObject
{
    long long _page;
    long long _pageSize;
    NSArray *_allGoodsSkuId;
}

@property(copy, nonatomic) NSArray *allGoodsSkuId; // @synthesize allGoodsSkuId=_allGoodsSkuId;
@property(nonatomic) long long pageSize; // @synthesize pageSize=_pageSize;
@property(nonatomic) long long page; // @synthesize page=_page;
- (void).cxx_destruct;
- (id)requestDic;

@end

