//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface JZHomeSingleGoodGroupModel : NSObject
{
    NSString *_groupTime;
    long long _timeRemain;
    long long _startTime;
    NSString *_srv;
    NSArray *_skuList;
}

+ (id)objectClassInArray;
@property(retain, nonatomic) NSArray *skuList; // @synthesize skuList=_skuList;
@property(copy, nonatomic) NSString *srv; // @synthesize srv=_srv;
@property(nonatomic) long long startTime; // @synthesize startTime=_startTime;
@property(nonatomic) long long timeRemain; // @synthesize timeRemain=_timeRemain;
@property(copy, nonatomic) NSString *groupTime; // @synthesize groupTime=_groupTime;
- (void).cxx_destruct;

@end

