//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class JDImageView, JZHomeThemeInfoModel, UIImageView, UILabel;

@interface JZHomeCategoryThemeView : UIView
{
    UIView *_whiteView;
    UILabel *_titleLbl;
    UIImageView *_icon;
    UIImageView *_bgTopImg;
    UIImageView *_bgBottomImg;
    UILabel *_sloganLbl;
    JDImageView *_mainImg;
    JZHomeThemeInfoModel *_model;
}

@property(retain, nonatomic) JZHomeThemeInfoModel *model; // @synthesize model=_model;
@property(retain, nonatomic) JDImageView *mainImg; // @synthesize mainImg=_mainImg;
@property(retain, nonatomic) UILabel *sloganLbl; // @synthesize sloganLbl=_sloganLbl;
@property(retain, nonatomic) UIImageView *bgBottomImg; // @synthesize bgBottomImg=_bgBottomImg;
@property(retain, nonatomic) UIImageView *bgTopImg; // @synthesize bgTopImg=_bgTopImg;
@property(retain, nonatomic) UIImageView *icon; // @synthesize icon=_icon;
@property(retain, nonatomic) UILabel *titleLbl; // @synthesize titleLbl=_titleLbl;
@property(retain, nonatomic) UIView *whiteView; // @synthesize whiteView=_whiteView;
- (void).cxx_destruct;
- (void)bindData:(id)arg1;
- (id)init;

@end

