//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray, UIButton, UILabel;
@protocol JZHomeSingleGoodsToggleViewDelegate;

@interface JZHomeSingleGoodsToggleView : UIView
{
    UIButton *_firstSession;
    UILabel *_sepLabel;
    UIButton *_lastSession;
    UIView *_bottomLine;
    NSArray *_titles;
    id <JZHomeSingleGoodsToggleViewDelegate> _delegate;
}

@property(nonatomic) __weak id <JZHomeSingleGoodsToggleViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSArray *titles; // @synthesize titles=_titles;
@property(retain, nonatomic) UIView *bottomLine; // @synthesize bottomLine=_bottomLine;
@property(retain, nonatomic) UIButton *lastSession; // @synthesize lastSession=_lastSession;
@property(retain, nonatomic) UILabel *sepLabel; // @synthesize sepLabel=_sepLabel;
@property(retain, nonatomic) UIButton *firstSession; // @synthesize firstSession=_firstSession;
- (void).cxx_destruct;
- (void)lastSessionTapped;
- (void)firstSessionTapped;
- (void)setSelectedWithIndex:(long long)arg1;
- (void)setupUI;
- (id)initWithCoder:(id)arg1;
- (id)init;
- (id)initWithFrame:(struct CGRect)arg1;

@end

