//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

#import "UIGestureRecognizerDelegate-Protocol.h"

@class NSString, UIButton, UIImageView, UILabel, UIView;
@protocol MessageBaseCellDelegate;

@interface MessageBaseCell : UITableViewCell <UIGestureRecognizerDelegate>
{
    _Bool _editable;
    _Bool _opened;
    id <MessageBaseCellDelegate> _delegate;
    long long _pattern;
    long long _numPattern;
    long long _ddEnable;
    UIImageView *_iconImageView;
    UIImageView *_tagImageView;
    UILabel *_titleLabel;
    UILabel *_contentLabel;
    UIImageView *_muteImageV;
    UILabel *_timeLabel;
    UIButton *_deleButton;
    UIView *_messageListLine;
    UIView *_containView;
    long long _showStyle;
    UIImageView *_redDot;
    UILabel *_numLabel;
    UIImageView *_numBackImg;
    UIImageView *_clearAnimationView;
    UIView *_frameView;
}

@property(retain, nonatomic) UIView *frameView; // @synthesize frameView=_frameView;
@property(retain, nonatomic) UIImageView *clearAnimationView; // @synthesize clearAnimationView=_clearAnimationView;
@property(retain, nonatomic) UIImageView *numBackImg; // @synthesize numBackImg=_numBackImg;
@property(retain, nonatomic) UILabel *numLabel; // @synthesize numLabel=_numLabel;
@property(retain, nonatomic) UIImageView *redDot; // @synthesize redDot=_redDot;
@property(nonatomic) long long showStyle; // @synthesize showStyle=_showStyle;
@property(retain, nonatomic) UIView *containView; // @synthesize containView=_containView;
@property(retain, nonatomic) UIView *messageListLine; // @synthesize messageListLine=_messageListLine;
@property(retain, nonatomic) UIButton *deleButton; // @synthesize deleButton=_deleButton;
@property(retain, nonatomic) UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(retain, nonatomic) UIImageView *muteImageV; // @synthesize muteImageV=_muteImageV;
@property(retain, nonatomic) UILabel *contentLabel; // @synthesize contentLabel=_contentLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIImageView *tagImageView; // @synthesize tagImageView=_tagImageView;
@property(retain, nonatomic) UIImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
@property(nonatomic, getter=isOpened) _Bool opened; // @synthesize opened=_opened;
@property(nonatomic) _Bool editable; // @synthesize editable=_editable;
@property(nonatomic) long long ddEnable; // @synthesize ddEnable=_ddEnable;
@property(nonatomic) long long numPattern; // @synthesize numPattern=_numPattern;
@property(nonatomic) long long pattern; // @synthesize pattern=_pattern;
@property(nonatomic) __weak id <MessageBaseCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)clearRedDotAnimate:(_Bool)arg1;
- (void)setCornerRadius:(unsigned long long)arg1;
- (id)getCellSupViewTableView;
- (void)setHighlighted:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)closeSwipe;
- (void)swipe:(id)arg1;
- (void)tapDeleteButton:(id)arg1;
- (void)setRedDotStyleWithUnreadCount:(long long)arg1 pattern:(long long)arg2 numPattern:(long long)arg3 redPoint:(_Bool)arg4;
- (void)setContentWithTitle:(id)arg1 content:(id)arg2 time:(double)arg3 mute:(_Bool)arg4 type:(id)arg5;
- (void)setWithModel:(id)arg1;
- (void)layoutAllFrame;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

