//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JDCoreCouponBaseModel.h"

@class NSString;

@interface MyCouponGetingModel : JDCoreCouponBaseModel
{
    _Bool _hasGot;
    NSString *_roleId;
    NSString *_key;
    NSString *_category;
    NSString *_limit;
    long long _jumpFlag;
    NSString *_jumpOpenAppUrl;
    NSString *_jumpCodeUrl;
    NSString *_leftImgUrl;
    NSString *_rightImgUrl;
    NSString *_jumpTip;
}

@property(copy, nonatomic) NSString *jumpTip; // @synthesize jumpTip=_jumpTip;
@property(copy, nonatomic) NSString *rightImgUrl; // @synthesize rightImgUrl=_rightImgUrl;
@property(copy, nonatomic) NSString *leftImgUrl; // @synthesize leftImgUrl=_leftImgUrl;
@property(copy, nonatomic) NSString *jumpCodeUrl; // @synthesize jumpCodeUrl=_jumpCodeUrl;
@property(copy, nonatomic) NSString *jumpOpenAppUrl; // @synthesize jumpOpenAppUrl=_jumpOpenAppUrl;
@property(nonatomic) long long jumpFlag; // @synthesize jumpFlag=_jumpFlag;
@property(nonatomic) _Bool hasGot; // @synthesize hasGot=_hasGot;
@property(copy, nonatomic) NSString *limit; // @synthesize limit=_limit;
@property(copy, nonatomic) NSString *category; // @synthesize category=_category;
@property(copy, nonatomic) NSString *key; // @synthesize key=_key;
@property(copy, nonatomic) NSString *roleId; // @synthesize roleId=_roleId;
- (void).cxx_destruct;
- (void)setDataWithDic:(id)arg1;
- (void)dealloc;

@end

