//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;

@interface MyJdFloorFactory : NSObject
{
    NSMutableDictionary *_floorsByFid;
    NSMutableDictionary *_floorsByFidPrefix;
}

+ (void)registerPrefixModeFloorClass:(Class)arg1 withPrefixFid:(id)arg2;
+ (Class)getPrefixModeFloorClassWithFid:(id)arg1;
+ (void)registerFloorClass:(Class)arg1 withFid:(id)arg2;
+ (Class)getFloorClassWithFid:(id)arg1;
+ (id)sharedInstance;
@property(retain, nonatomic) NSMutableDictionary *floorsByFidPrefix; // @synthesize floorsByFidPrefix=_floorsByFidPrefix;
@property(retain, nonatomic) NSMutableDictionary *floorsByFid; // @synthesize floorsByFid=_floorsByFid;
- (void).cxx_destruct;
- (id)init;

@end

