//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class MyJdCardFooterModel, MyJdCardHeaderModel;

@interface MyJdCardExtendInfoModel : NSObject
{
    MyJdCardHeaderModel *_header;
    MyJdCardFooterModel *_footer;
}

@property(retain, nonatomic) MyJdCardFooterModel *footer; // @synthesize footer=_footer;
@property(retain, nonatomic) MyJdCardHeaderModel *header; // @synthesize header=_header;
- (void).cxx_destruct;

@end

