//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JDContentItem.h"

@class FeedBackOptimizeReminderView, FeedBackRecentOptimizeModel, JDImageView, MyJdHomeModel, UIButton, UILabel, UIView;
@protocol MyJdAdViewDelegate;

@interface MyJdAdView : JDContentItem
{
    JDImageView *_adView;
    _Bool _isPraise;
    MyJdHomeModel *_myHomeModel;
    unsigned long long _praiseNum;
    id <MyJdAdViewDelegate> _adViewdelegate;
    FeedBackRecentOptimizeModel *_recentOptimizeModel;
    UIButton *_praiseButton;
    UILabel *_praiseLabel;
    FeedBackOptimizeReminderView *_reminderView;
    UIView *_bottomMaskView;
}

@property(retain, nonatomic) UIView *bottomMaskView; // @synthesize bottomMaskView=_bottomMaskView;
@property(retain, nonatomic) FeedBackOptimizeReminderView *reminderView; // @synthesize reminderView=_reminderView;
@property(retain, nonatomic) UILabel *praiseLabel; // @synthesize praiseLabel=_praiseLabel;
@property(retain, nonatomic) UIButton *praiseButton; // @synthesize praiseButton=_praiseButton;
@property(retain, nonatomic) FeedBackRecentOptimizeModel *recentOptimizeModel; // @synthesize recentOptimizeModel=_recentOptimizeModel;
@property(nonatomic) _Bool isPraise; // @synthesize isPraise=_isPraise;
@property(nonatomic) __weak id <MyJdAdViewDelegate> adViewdelegate; // @synthesize adViewdelegate=_adViewdelegate;
@property(nonatomic) unsigned long long praiseNum; // @synthesize praiseNum=_praiseNum;
@property(retain, nonatomic) MyJdHomeModel *myHomeModel; // @synthesize myHomeModel=_myHomeModel;
- (void).cxx_destruct;
- (void)beginAnimation;
- (void)tapReminderView;
- (void)praiseButtonClick:(id)arg1;
- (void)resumeTimer;
- (void)pauseTimer;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

