//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableDictionary;
@protocol JDBPCommonComponentInteractor, MyJdFloorInteractorProtocol, MyJdFloorManagerDelegate;

@interface MyJdFloorManager : NSObject
{
    id <MyJdFloorInteractorProtocol> _ccInteractor;
    id <JDBPCommonComponentInteractor> _platformInteractor;
    id <MyJdFloorManagerDelegate> _delegate;
    NSArray *_floors;
    NSMutableDictionary *_floorsByLevel;
}

@property(retain, nonatomic) NSMutableDictionary *floorsByLevel; // @synthesize floorsByLevel=_floorsByLevel;
@property(retain, nonatomic) NSArray *floors; // @synthesize floors=_floors;
@property(nonatomic) __weak id <MyJdFloorManagerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak id <JDBPCommonComponentInteractor> platformInteractor; // @synthesize platformInteractor=_platformInteractor;
@property(nonatomic) __weak id <MyJdFloorInteractorProtocol> ccInteractor; // @synthesize ccInteractor=_ccInteractor;
- (void).cxx_destruct;
- (_Bool)containsFloorWithID:(id)arg1;
- (id)platformFloorByRefId:(id)arg1;
- (id)floorById:(id)arg1 level:(long long)arg2;
- (id)floorById:(id)arg1;
- (id)idFromMId:(id)arg1 bId:(id)arg2;
- (id)idForFloor:(id)arg1;
- (id)floorAtIndex:(long long)arg1;
- (long long)indexOfFloor:(id)arg1;
- (id)floorItemsByLevel:(long long)arg1;
- (id)floorItems;
- (id)splFloorFidOfRelatedFloor:(id)arg1;
- (id)createSplFloorRelateToFloor:(id)arg1;
- (id)createPlatformFloorWithMId:(id)arg1 bId:(id)arg2;
- (id)createAdminFloorWithMId:(id)arg1 bId:(id)arg2;
- (id)createFloorWithMId:(id)arg1 bId:(id)arg2;
- (void)checkSplConflictWithFloor:(id)arg1 startIndex:(long long)arg2;
- (void)resolveSplFloorConflicts;
- (void)updateFloors;
- (void)addFloorWithMId:(id)arg1 bId:(id)arg2 level:(long long)arg3 configuration:(CDUnknownBlockType)arg4;
- (void)createFloorsWithData:(id)arg1 mIdKeyPath:(id)arg2 bIdKeyPath:(id)arg3 level:(long long)arg4 configuration:(CDUnknownBlockType)arg5;
- (id)init;

@end

