//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class JDStoreNetwork, NSMutableArray, NSMutableDictionary;
@protocol OS_dispatch_queue;

@interface MyJdFloorDataManager : NSObject
{
    JDStoreNetwork *_menuNetWork;
    NSObject<OS_dispatch_queue> *_menuConfigCacheIOQueue;
    long long _menuConfigCacheVersion;
    _Bool _shouldCacheMenu;
    NSMutableArray *_menuList;
    NSMutableArray *_headInfoArr;
    NSMutableDictionary *_otherConfigDic;
    NSMutableArray *_keyArr;
    NSMutableArray *_walletMenu;
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)sharedMyJdFloorDataManager;
@property(retain, nonatomic) NSMutableArray *walletMenu; // @synthesize walletMenu=_walletMenu;
@property(retain, nonatomic) NSMutableArray *keyArr; // @synthesize keyArr=_keyArr;
@property(retain, nonatomic) NSMutableDictionary *otherConfigDic; // @synthesize otherConfigDic=_otherConfigDic;
@property(retain, nonatomic) NSMutableArray *headInfoArr; // @synthesize headInfoArr=_headInfoArr;
@property(retain, nonatomic) NSMutableArray *menuList; // @synthesize menuList=_menuList;
- (void).cxx_destruct;
- (id)readLocalCacheConfig;
- (id)configCacheIOQueue;
- (id)cacheFilePath;
- (id)cacheDirectory;
- (void)sortMenuListWithModel:(id)arg1;
- (id)modelListWithConfig:(id)arg1;
- (id)otherConfigInfoFromCache:(id)arg1;
- (id)menuListWithMenuConfigs:(id)arg1;
- (id)menuListFromLocalCacheConfig:(id)arg1;
- (void)handleVersionNotification:(id)arg1;
- (id)getConfigInfoFromNet:(id)arg1 forKey:(id)arg2;
- (id)getMenuAndHeadInfoFromNet:(id)arg1;
- (void)showMyJdHome:(id)arg1 components:(id)arg2 error:(id)arg3;
- (void)loadMenuConfig;
- (void)checkLocalCacheConfigVersion;
- (void)checkAPPVersion;
- (void)loadMenuList:(id)arg1;
- (void)cancelRequest;
- (void)dealloc;
- (id)init;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

