//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MyJdBaseFloor.h"

#import "MyJdPromotionFloorViewDelegate-Protocol.h"

@class NSString;

@interface MyJdPromotionFloor : MyJdBaseFloor <MyJdPromotionFloorViewDelegate>
{
}

+ (void)load;
- (void)didPromotionItemTappedWithModel:(id)arg1;
- (id)myjd_renderViewForRow:(long long)arg1 reusingView:(id)arg2;
- (id)myjd_reuseIdentifierForRow:(long long)arg1;
- (double)myjd_heightForRow:(long long)arg1;
- (long long)myjd_numberOfRows;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

