//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class MyJdNetworkManager, NSDictionary, NSError, NSMutableArray, NSMutableDictionary, NSString;
@protocol MyJdHomeViewControllerProtocol;

@interface MyJdBusinessManager : NSObject
{
    _Bool _isNeedUndo;
    _Bool _financeRequestFinished;
    _Bool _personalinfoRequestFinished;
    id <MyJdHomeViewControllerProtocol> _delegate;
    NSMutableDictionary *_numberMessageDic;
    NSMutableDictionary *_historyParamDic;
    NSMutableArray *_channelArr;
    NSMutableArray *_activityArr;
    NSDictionary *_extUserInfo;
    NSString *_channelTestId;
    id _financeFloorData;
    NSError *_financeFloorError;
    MyJdNetworkManager *_networkManager;
    NSMutableDictionary *_buryPointHasReportDic;
    NSString *_SubscriptExpoStr;
}

@property(copy, nonatomic) NSString *SubscriptExpoStr; // @synthesize SubscriptExpoStr=_SubscriptExpoStr;
@property(retain, nonatomic) NSMutableDictionary *buryPointHasReportDic; // @synthesize buryPointHasReportDic=_buryPointHasReportDic;
@property(retain, nonatomic) MyJdNetworkManager *networkManager; // @synthesize networkManager=_networkManager;
@property(retain, nonatomic) NSError *financeFloorError; // @synthesize financeFloorError=_financeFloorError;
@property(retain, nonatomic) id financeFloorData; // @synthesize financeFloorData=_financeFloorData;
@property(nonatomic) _Bool personalinfoRequestFinished; // @synthesize personalinfoRequestFinished=_personalinfoRequestFinished;
@property(nonatomic) _Bool financeRequestFinished; // @synthesize financeRequestFinished=_financeRequestFinished;
@property(nonatomic) _Bool isNeedUndo; // @synthesize isNeedUndo=_isNeedUndo;
@property(retain, nonatomic) NSString *channelTestId; // @synthesize channelTestId=_channelTestId;
@property(retain, nonatomic) NSDictionary *extUserInfo; // @synthesize extUserInfo=_extUserInfo;
@property(retain, nonatomic) NSMutableArray *activityArr; // @synthesize activityArr=_activityArr;
@property(retain, nonatomic) NSMutableArray *channelArr; // @synthesize channelArr=_channelArr;
@property(retain, nonatomic) NSMutableDictionary *historyParamDic; // @synthesize historyParamDic=_historyParamDic;
@property(retain, nonatomic) NSMutableDictionary *numberMessageDic; // @synthesize numberMessageDic=_numberMessageDic;
@property(nonatomic) __weak id <MyJdHomeViewControllerProtocol> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)addAdjectiveBuryPointWithInfo;
- (void)requestLogisticsinformationWithDict:(id)arg1;
- (void)resetBuryPointHasReportDic;
- (void)firstbuyBannerExpo;
- (void)plusBannerExpo;
- (void)enterpriseExpo;
- (void)xiaobaiExpo:(long long)arg1;
- (void)faceLoginExpo;
- (void)twoLevelPageExpo:(id)arg1;
- (void)shimingrenzhengExpo;
- (void)walletEnterExpo;
- (void)forCommentExpo;
- (void)updateActivityData:(id)arg1;
- (void)updateChannelMenu:(id)arg1;
- (void)updateHistoryNumber:(id)arg1;
- (void)updateAccountInfo:(id)arg1;
- (void)updateExtraNumber:(id)arg1;
- (void)requestHistoryState;
- (void)channelTappedRequest:(id)arg1 type:(long long)arg2;
- (void)myjd_uniformJumpHandle:(id)arg1;
- (void)myjd_mtaHandle:(id)arg1;
- (void)gotoNextPageWithModel:(id)arg1;
- (void)cancelRequest;
- (void)cleanup;
- (_Bool)isNeedPullAnimation:(long long)arg1;
- (void)updateUserAccount:(id)arg1;
- (void)praiseRequset:(id)arg1;
- (void)handleCCFinanceFloorData;
- (void)loadMainData;
- (_Bool)getMessageState;
- (void)preLoadDefaultImage;
- (id)init;

@end

