//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JDViewController.h"

#import "MyBlankNoteViewDelegate-Protocol.h"
#import "MyWalletAdCellDelegate-Protocol.h"
#import "MyWalletHeadViewDelegate-Protocol.h"
#import "MyWalletItemViewDelegate-Protocol.h"
#import "MyWalletNotifiViewDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class JDStoreNetwork, MyBlankNoteView, MyWalletHeadView, NSArray, NSMutableDictionary, NSString, UILabel, UITableView, UIView;

@interface MyWalletViewController : JDViewController <UITableViewDataSource, UITableViewDelegate, MyWalletHeadViewDelegate, MyWalletItemViewDelegate, MyWalletNotifiViewDelegate, MyBlankNoteViewDelegate, MyWalletAdCellDelegate>
{
    UITableView *_myWalletTable;
    MyWalletHeadView *_headView;
    MyBlankNoteView *_blankNoteView;
    UIView *_lifeTripView;
    UILabel *_lifeTripLabel;
    JDStoreNetwork *_netWork;
    NSArray *_menuArr;
    NSMutableDictionary *_menuViewDic;
    NSMutableDictionary *_numberMessageDic;
    _Bool _hasNotifi;
    _Bool _isDegrade;
    _Bool _kabaoIsDegrade;
    _Bool _isShowRedDotInZhanghuyue;
    _Bool _isLoadMenuSuccess;
    NSArray *_menuArrData;
}

@property(retain, nonatomic) NSArray *menuArrData; // @synthesize menuArrData=_menuArrData;
- (void).cxx_destruct;
- (void)updateRedPointVersion:(id)arg1;
- (void)checkWalletItemView:(id)arg1 RedPoint:(id)arg2;
- (void)checkHeadConfigRedPoint:(id)arg1;
- (id)modelListWithConfig:(id)arg1;
- (void)gotoNextPageWithModel:(id)arg1;
- (void)MyWalletNotifiViewDidClickedClose:(id)arg1;
- (void)MyWalletNotifiViewDidClickedContent:(id)arg1;
- (void)didAdCellTappedWithModel:(id)arg1;
- (void)didMyWalletItemViewTapped:(id)arg1 WithModel:(id)arg2;
- (void)didBlankItemTappedWithModel:(id)arg1;
- (void)didWalletItemTappedWithModel:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (_Bool)isSpecialFoor:(id)arg1;
- (void)updateExtraNumber:(id)arg1;
- (void)loadData;
- (void)setMainUI;
- (void)readMenuFromLocal;
- (void)saveMenuData;
- (void)reconnect;
- (void)loadMenuConfig;
- (void)initLifeTripView;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

