//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JDFinderTableViewCell.h"

@class NewFinderImageView, NewFinderLivingStatusView, UIImageView, UILabel, UIView;

@interface NewFinderLiveCell : JDFinderTableViewCell
{
    UIView *_dotView;
    struct CGSize _titleLabelSize;
    struct CGSize _authorLabelSize;
    struct CGSize _locationLabelSize;
    NewFinderImageView *_liveImageView;
    UILabel *_titleLabel;
    NewFinderImageView *_authorImageView;
    UILabel *_authorLabel;
    UILabel *_locationLabel;
    NewFinderLivingStatusView *_statusView;
    UIImageView *_vrImageView;
}

@property(retain, nonatomic) UIImageView *vrImageView; // @synthesize vrImageView=_vrImageView;
@property(retain, nonatomic) NewFinderLivingStatusView *statusView; // @synthesize statusView=_statusView;
@property(retain, nonatomic) UILabel *locationLabel; // @synthesize locationLabel=_locationLabel;
@property(retain, nonatomic) UILabel *authorLabel; // @synthesize authorLabel=_authorLabel;
@property(retain, nonatomic) NewFinderImageView *authorImageView; // @synthesize authorImageView=_authorImageView;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) NewFinderImageView *liveImageView; // @synthesize liveImageView=_liveImageView;
- (void).cxx_destruct;
- (void)refresh:(id)arg1;
- (void)cellWillEndDisPlay;
- (void)cellWillDisPlay;
- (void)assignValue:(id)arg1;
- (void)layoutSubviews;
- (void)setupViews;

@end

