//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "FinderCellModelProtocol-Protocol.h"
#import "NSCoding-Protocol.h"

@class FinderJumpModel, NSString;

@interface NewFinderArticleDetailPicModel : NSObject <FinderCellModelProtocol, NSCoding>
{
    _Bool _searchFlag;
    NSString *_imgUrl;
    FinderJumpModel *_jump;
    double _imgHeight;
}

@property(nonatomic) double imgHeight; // @synthesize imgHeight=_imgHeight;
@property(retain, nonatomic) FinderJumpModel *jump; // @synthesize jump=_jump;
@property(nonatomic) _Bool searchFlag; // @synthesize searchFlag=_searchFlag;
@property(copy, nonatomic) NSString *imgUrl; // @synthesize imgUrl=_imgUrl;
- (void).cxx_destruct;
- (_Bool)isValidModel;
@property(readonly, nonatomic) double cellHeight;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

