//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "OrderDetailFloorBaseView.h"

@class JDOrderTraceAttributedLabel, UIImageView, UILabel, UIView;

@interface OrderDetailFloorView_Trace : OrderDetailFloorBaseView
{
    UIImageView *_loc1_ImageView;
    JDOrderTraceAttributedLabel *_loc2_Label;
    UILabel *_loc3_Label;
    UIImageView *_loc4_ImageView;
    UIImageView *_loc5_ImgView;
    UILabel *_loc5_Label;
    UIView *_midView;
    UIView *_rightView;
}

@property(retain, nonatomic) UIView *rightView; // @synthesize rightView=_rightView;
@property(retain, nonatomic) UIView *midView; // @synthesize midView=_midView;
@property(retain, nonatomic) UILabel *loc5_Label; // @synthesize loc5_Label=_loc5_Label;
@property(retain, nonatomic) UIImageView *loc5_ImgView; // @synthesize loc5_ImgView=_loc5_ImgView;
@property(retain, nonatomic) UIImageView *loc4_ImageView; // @synthesize loc4_ImageView=_loc4_ImageView;
@property(retain, nonatomic) UILabel *loc3_Label; // @synthesize loc3_Label=_loc3_Label;
@property(retain, nonatomic) JDOrderTraceAttributedLabel *loc2_Label; // @synthesize loc2_Label=_loc2_Label;
@property(retain, nonatomic) UIImageView *loc1_ImageView; // @synthesize loc1_ImageView=_loc1_ImageView;
- (void).cxx_destruct;
- (void)traceTap:(id)arg1;
- (void)jumpToOrderTrace;
- (void)didTapText:(id)arg1;
- (void)textNumberClick:(id)arg1;
- (void)loc5Taped;
- (double)getViewHeight;
- (void)setViewWithModel:(id)arg1;
- (void)dealloc;

@end

