//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface PDBPClothesColorItemModel : NSObject
{
    _Bool _stockEnable;
    NSString *_skuId;
    NSString *_image;
}

@property(nonatomic) _Bool stockEnable; // @synthesize stockEnable=_stockEnable;
@property(copy, nonatomic) NSString *image; // @synthesize image=_image;
@property(copy, nonatomic) NSString *skuId; // @synthesize skuId=_skuId;
- (void).cxx_destruct;

@end

