//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface PDBPWhiteBarModel : NSObject
{
    _Bool _ava;
    _Bool _btUser;
    _Bool _login;
    NSString *_marketingText;
    NSArray *_planInfos;
    NSString *_url;
    long long _whiteBarSelected;
}

+ (id)objectClassInArray;
@property(nonatomic) long long whiteBarSelected; // @synthesize whiteBarSelected=_whiteBarSelected;
@property(copy, nonatomic) NSString *url; // @synthesize url=_url;
@property(retain, nonatomic) NSArray *planInfos; // @synthesize planInfos=_planInfos;
@property(copy, nonatomic) NSString *marketingText; // @synthesize marketingText=_marketingText;
@property(nonatomic) _Bool login; // @synthesize login=_login;
@property(nonatomic) _Bool btUser; // @synthesize btUser=_btUser;
@property(nonatomic) _Bool ava; // @synthesize ava=_ava;
- (void).cxx_destruct;

@end

