//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PDFloorBaseView.h"

@class JDImageView, PDBPIconModel, UILabel;
@protocol PDBPIconViewDelegate;

@interface PDBPIconNormalView : PDFloorBaseView
{
    id <PDBPIconViewDelegate> _delegate;
    PDBPIconModel *_model;
    JDImageView *_trustworthyIcon;
    UILabel *_trustworthyLabel;
}

@property(retain, nonatomic) UILabel *trustworthyLabel; // @synthesize trustworthyLabel=_trustworthyLabel;
@property(retain, nonatomic) JDImageView *trustworthyIcon; // @synthesize trustworthyIcon=_trustworthyIcon;
@property(retain, nonatomic) PDBPIconModel *model; // @synthesize model=_model;
@property(nonatomic) __weak id <PDBPIconViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (double)tryLayoutIconListWithArray:(id)arg1 exclamationCount:(long long)arg2 locationY:(double)arg3;
- (void)renderBasicServiceRegion:(double *)arg1;
- (void)renderTrustworthyRegion:(double *)arg1;
- (void)renderWithData:(id)arg1;
- (void)resetState;
- (void)floorTap:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

