//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PDFloorBaseViewModel.h"

@class PDBPClothesColorFloorView, PDBPClothesColorModel;

@interface PDBPClothesColorFloor : PDFloorBaseViewModel
{
    PDBPClothesColorModel *_model;
    PDBPClothesColorFloorView *_colorView;
}

@property(retain, nonatomic) PDBPClothesColorFloorView *colorView; // @synthesize colorView=_colorView;
@property(retain, nonatomic) PDBPClothesColorModel *model; // @synthesize model=_model;
- (void).cxx_destruct;
- (void)render;
- (void)resetState;

@end

