//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JDView.h"

#import "PDViewProtocol-Protocol.h"

@class JDIconLabel, NSString, PDBPContainerDataModel, PDBPPlusMemberView, PDBPPriceRegionModel, PDBPPriceView, PDBPSamPricePartView, PDBPSkyEyePricePromotView, PDBPTokenPriceView, PDFSPricePartView, UIButton, UIImageView, UILabel, UIView, VerticalButton;
@protocol PDBPPriceRegionViewDelegate;

@interface PDBPPriceRegionView : JDView <PDViewProtocol>
{
    _Bool _isAddFavariteAnimating;
    id <PDBPPriceRegionViewDelegate> _priceDelegate;
    PDBPPriceView *_jdPriceView;
    VerticalButton *_priceNotificeButton;
    VerticalButton *_bargainButton;
    PDBPSamPricePartView *_samPricePartView;
    PDBPPlusMemberView *_plusMemberView;
    UIImageView *_dingZhiIcon;
    PDBPPriceRegionModel *_model;
    PDBPContainerDataModel *_containerDataModel;
    PDBPTokenPriceView *_tokenPriceView;
    UIView *_promotionPriceView;
    UILabel *_promotiomPriceLabel;
    UIButton *_promotionIcon;
    VerticalButton *_favoriteButton;
    JDIconLabel *_clothIcon;
    UILabel *_skyEyeCutDownPrice;
    PDBPSkyEyePricePromotView *_skyEyePromptView;
    PDFSPricePartView *_fsPricePartView;
}

@property(retain, nonatomic) PDFSPricePartView *fsPricePartView; // @synthesize fsPricePartView=_fsPricePartView;
@property(retain, nonatomic) PDBPSkyEyePricePromotView *skyEyePromptView; // @synthesize skyEyePromptView=_skyEyePromptView;
@property(retain, nonatomic) UILabel *skyEyeCutDownPrice; // @synthesize skyEyeCutDownPrice=_skyEyeCutDownPrice;
@property(retain, nonatomic) JDIconLabel *clothIcon; // @synthesize clothIcon=_clothIcon;
@property(retain, nonatomic) VerticalButton *favoriteButton; // @synthesize favoriteButton=_favoriteButton;
@property(retain, nonatomic) UIButton *promotionIcon; // @synthesize promotionIcon=_promotionIcon;
@property(retain, nonatomic) UILabel *promotiomPriceLabel; // @synthesize promotiomPriceLabel=_promotiomPriceLabel;
@property(retain, nonatomic) UIView *promotionPriceView; // @synthesize promotionPriceView=_promotionPriceView;
@property(retain, nonatomic) PDBPTokenPriceView *tokenPriceView; // @synthesize tokenPriceView=_tokenPriceView;
@property(retain, nonatomic) PDBPContainerDataModel *containerDataModel; // @synthesize containerDataModel=_containerDataModel;
@property(retain, nonatomic) PDBPPriceRegionModel *model; // @synthesize model=_model;
@property(retain, nonatomic) UIImageView *dingZhiIcon; // @synthesize dingZhiIcon=_dingZhiIcon;
@property(retain, nonatomic) PDBPPlusMemberView *plusMemberView; // @synthesize plusMemberView=_plusMemberView;
@property(retain, nonatomic) PDBPSamPricePartView *samPricePartView; // @synthesize samPricePartView=_samPricePartView;
@property(retain, nonatomic) VerticalButton *bargainButton; // @synthesize bargainButton=_bargainButton;
@property(retain, nonatomic) VerticalButton *priceNotificeButton; // @synthesize priceNotificeButton=_priceNotificeButton;
@property(retain, nonatomic) PDBPPriceView *jdPriceView; // @synthesize jdPriceView=_jdPriceView;
@property(nonatomic) __weak id <PDBPPriceRegionViewDelegate> priceDelegate; // @synthesize priceDelegate=_priceDelegate;
- (void).cxx_destruct;
- (void)productdetailbargainingExpoMTA;
- (void)favoriteButtonAction:(id)arg1;
- (void)showTokenPriceInfoPopupView;
- (void)priceNotificeButtonTapped:(id)arg1;
- (void)bargainButtonTapped:(id)arg1;
- (void)setFavoriteButtonState:(_Bool)arg1 animate:(_Bool)arg2;
- (void)resetFavoriteButton:(_Bool)arg1;
- (void)layoutPromotionView;
- (void)renderUIWithData:(id)arg1 containerDataModel:(id)arg2;
- (void)resetState;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

