//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface PDBPPropertyModel : NSObject
{
    _Bool _isJx;
    _Bool _isOP;
    _Bool _isPop;
    _Bool _isEasyBuyPrice;
    _Bool _isRegularPrice;
    NSString *_virtualCardUrl;
}

@property(nonatomic) _Bool isRegularPrice; // @synthesize isRegularPrice=_isRegularPrice;
@property(nonatomic) _Bool isEasyBuyPrice; // @synthesize isEasyBuyPrice=_isEasyBuyPrice;
@property(copy, nonatomic) NSString *virtualCardUrl; // @synthesize virtualCardUrl=_virtualCardUrl;
@property(nonatomic) _Bool isPop; // @synthesize isPop=_isPop;
@property(nonatomic) _Bool isOP; // @synthesize isOP=_isOP;
@property(nonatomic) _Bool isJx; // @synthesize isJx=_isJx;
- (void).cxx_destruct;

@end

