//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PDFloorBaseView.h"

@class PDBPEntityStoreModel, UIButton, UIImageView, UILabel, UIView;
@protocol PDFloorViewProtocol;

@interface PDBPEntityStoreFloorView : PDFloorBaseView
{
    id <PDFloorViewProtocol> _delegate;
    PDBPEntityStoreModel *_model;
    UIView *_redLineView;
    UILabel *_titleLabel;
    UILabel *_distanceLabel;
    UILabel *_addressLabel;
    UILabel *_shopNameLabel;
    UIButton *_moreShopButton;
    UIImageView *_addressIcon;
}

@property(retain, nonatomic) UIImageView *addressIcon; // @synthesize addressIcon=_addressIcon;
@property(retain, nonatomic) UIButton *moreShopButton; // @synthesize moreShopButton=_moreShopButton;
@property(retain, nonatomic) UILabel *shopNameLabel; // @synthesize shopNameLabel=_shopNameLabel;
@property(retain, nonatomic) UILabel *addressLabel; // @synthesize addressLabel=_addressLabel;
@property(retain, nonatomic) UILabel *distanceLabel; // @synthesize distanceLabel=_distanceLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIView *redLineView; // @synthesize redLineView=_redLineView;
@property(retain, nonatomic) PDBPEntityStoreModel *model; // @synthesize model=_model;
@property(nonatomic) __weak id <PDFloorViewProtocol> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)pressMoreShopButton;
- (void)renderWithData:(id)arg1;
- (void)resetState;
- (id)initWithFrame:(struct CGRect)arg1;

@end

