//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PDFloorBaseViewModel.h"

#import "PDFloorViewProtocol-Protocol.h"

@class NSString, NewProductModel, PDCommonGModel, PDCommonGView;

@interface PDCommonGViewModel : PDFloorBaseViewModel <PDFloorViewProtocol>
{
    NewProductModel *_model;
    PDCommonGView *_commonView;
    PDCommonGModel *_dataModel;
}

+ (void)load;
@property(retain, nonatomic) PDCommonGModel *dataModel; // @synthesize dataModel=_dataModel;
@property(retain, nonatomic) PDCommonGView *commonView; // @synthesize commonView=_commonView;
@property(retain, nonatomic) NewProductModel *model; // @synthesize model=_model;
- (void).cxx_destruct;
- (void)jumpWithUrl:(id)arg1 jumpType:(long long)arg2;
- (void)floorTapped:(id)arg1;
- (void)renderUIWithProductModel:(id)arg1;
- (void)refreshViewForFloorTemplate;
- (void)resetState;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

