//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface PDFSignInfo : NSObject
{
    NSString *_orderId;
    NSString *_bizType;
    NSString *_fileUrl;
    NSString *_signedHtmlUrl;
    NSString *_signedItrusname;
}

@property(copy, nonatomic) NSString *signedItrusname; // @synthesize signedItrusname=_signedItrusname;
@property(copy, nonatomic) NSString *signedHtmlUrl; // @synthesize signedHtmlUrl=_signedHtmlUrl;
@property(copy, nonatomic) NSString *fileUrl; // @synthesize fileUrl=_fileUrl;
@property(copy, nonatomic) NSString *bizType; // @synthesize bizType=_bizType;
@property(copy, nonatomic) NSString *orderId; // @synthesize orderId=_orderId;
- (void).cxx_destruct;

@end

