//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "PDViewProtocol-Protocol.h"

@class JDImageView, NSString, NewProductModel, PDMainImagePlayVideoHelper, PDNetworkAccessManager, UIButton, UIImageView;
@protocol PDMainImageMarkViewDelegate;

@interface PDMainImageMarkView : UIView <PDViewProtocol>
{
    _Bool _breathAnimateCanShow;
    _Bool _breathAnimateShowed;
    _Bool _isHavePanorama;
    NewProductModel *_model;
    id <PDMainImageMarkViewDelegate> _delegate;
    JDImageView *_paperImageView;
    PDNetworkAccessManager *_networkManager;
    PDMainImagePlayVideoHelper *_playHelper;
    UIButton *_playButton;
    JDImageView *_leftBottomImgView;
    JDImageView *_rightTopImgView;
    JDImageView *_middleImgView;
    UIImageView *_bubbleImgView;
    UIButton *_animateButton;
    UIButton *_panoramaIconButton;
    UIImageView *_panoramaTipbubble;
}

@property(nonatomic) _Bool isHavePanorama; // @synthesize isHavePanorama=_isHavePanorama;
@property(retain, nonatomic) UIImageView *panoramaTipbubble; // @synthesize panoramaTipbubble=_panoramaTipbubble;
@property(retain, nonatomic) UIButton *panoramaIconButton; // @synthesize panoramaIconButton=_panoramaIconButton;
@property(nonatomic) _Bool breathAnimateShowed; // @synthesize breathAnimateShowed=_breathAnimateShowed;
@property(nonatomic) _Bool breathAnimateCanShow; // @synthesize breathAnimateCanShow=_breathAnimateCanShow;
@property(retain, nonatomic) UIButton *animateButton; // @synthesize animateButton=_animateButton;
@property(retain, nonatomic) UIImageView *bubbleImgView; // @synthesize bubbleImgView=_bubbleImgView;
@property(retain, nonatomic) JDImageView *middleImgView; // @synthesize middleImgView=_middleImgView;
@property(retain, nonatomic) JDImageView *rightTopImgView; // @synthesize rightTopImgView=_rightTopImgView;
@property(retain, nonatomic) JDImageView *leftBottomImgView; // @synthesize leftBottomImgView=_leftBottomImgView;
@property(retain, nonatomic) UIButton *playButton; // @synthesize playButton=_playButton;
@property(retain, nonatomic) PDMainImagePlayVideoHelper *playHelper; // @synthesize playHelper=_playHelper;
@property(retain, nonatomic) PDNetworkAccessManager *networkManager; // @synthesize networkManager=_networkManager;
@property(retain, nonatomic) JDImageView *paperImageView; // @synthesize paperImageView=_paperImageView;
@property(nonatomic) __weak id <PDMainImageMarkViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NewProductModel *model; // @synthesize model=_model;
- (void).cxx_destruct;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)pressBtnType:(long long)arg1 withObject:(id)arg2;
- (void)panoramaIconButtonTapped:(id)arg1;
- (void)paperImageViewDidTapped;
- (void)arMarkupOpenApp;
- (void)arMakeupButtonTapped:(id)arg1;
- (void)animateButtonTapped:(id)arg1;
- (id)getVideoExpoMTAParamValue;
- (void)playVideo;
- (void)panoramaTipbubbleHidden;
- (void)show3DDisplayIcon:(_Bool)arg1;
- (void)tryStartBreathAnimate;
- (void)hiddenBubbleView;
- (void)renderBubbleViewUI;
- (void)prepareMarkButtons;
- (void)prepareVideoPlay;
- (void)adjustSubsViewLocation:(double)arg1;
- (void)renderUIWithProductModel:(id)arg1;
- (void)resetState;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

