//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray, NSNumber, NSString;

@interface PDPackModel : NSObject
{
    _Bool _isPop;
    NSString *_packListPrice;
    NSString *_packPrice;
    NSNumber *_mainSkuId;
    NSString *_mainSkuPrice;
    NSNumber *_packId;
    NSString *_discount;
    NSString *_packName;
    NSString *_packType;
    NSString *_mainSkuName;
    NSMutableArray *_productList;
    NSString *_domain;
    NSString *_buyCount;
    NSString *_productCount;
    NSString *_sourceType;
    NSString *_sourceValue;
    NSString *_mainSkuPicUrl;
}

+ (id)objectClassInArray;
@property(copy, nonatomic) NSString *mainSkuPicUrl; // @synthesize mainSkuPicUrl=_mainSkuPicUrl;
@property(nonatomic) _Bool isPop; // @synthesize isPop=_isPop;
@property(copy, nonatomic) NSString *sourceValue; // @synthesize sourceValue=_sourceValue;
@property(copy, nonatomic) NSString *sourceType; // @synthesize sourceType=_sourceType;
@property(copy, nonatomic) NSString *productCount; // @synthesize productCount=_productCount;
@property(copy, nonatomic) NSString *buyCount; // @synthesize buyCount=_buyCount;
@property(copy, nonatomic) NSString *domain; // @synthesize domain=_domain;
@property(retain, nonatomic) NSMutableArray *productList; // @synthesize productList=_productList;
@property(copy, nonatomic) NSString *mainSkuName; // @synthesize mainSkuName=_mainSkuName;
@property(copy, nonatomic) NSString *packType; // @synthesize packType=_packType;
@property(copy, nonatomic) NSString *packName; // @synthesize packName=_packName;
@property(copy, nonatomic) NSString *discount; // @synthesize discount=_discount;
@property(retain, nonatomic) NSNumber *packId; // @synthesize packId=_packId;
@property(copy, nonatomic) NSString *mainSkuPrice; // @synthesize mainSkuPrice=_mainSkuPrice;
@property(retain, nonatomic) NSNumber *mainSkuId; // @synthesize mainSkuId=_mainSkuId;
@property(copy, nonatomic) NSString *packPrice; // @synthesize packPrice=_packPrice;
@property(copy, nonatomic) NSString *packListPrice; // @synthesize packListPrice=_packListPrice;
- (void).cxx_destruct;

@end

