//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PDFloorBaseView.h"

#import "PDViewProtocol-Protocol.h"

@class NSString, NewProductModel, PDIconLabel, VerticalButton;
@protocol PDTitleInfoFloorViewDelegate;

@interface PDTitleInfoFloorView : PDFloorBaseView <PDViewProtocol>
{
    _Bool _isAddFavariteAnimating;
    id <PDTitleInfoFloorViewDelegate> _delegate;
    NewProductModel *_model;
    PDIconLabel *_iconTitleLabel;
    VerticalButton *_favoriteButton;
}

@property(retain, nonatomic) VerticalButton *favoriteButton; // @synthesize favoriteButton=_favoriteButton;
@property(retain, nonatomic) PDIconLabel *iconTitleLabel; // @synthesize iconTitleLabel=_iconTitleLabel;
@property(retain, nonatomic) NewProductModel *model; // @synthesize model=_model;
@property(nonatomic) __weak id <PDTitleInfoFloorViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)setFavoriteButtonState:(_Bool)arg1 animate:(_Bool)arg2;
- (void)resetFavoriteButton:(_Bool)arg1;
- (void)buttonAction:(id)arg1;
- (void)floorTap:(id)arg1;
- (void)configGesture;
- (void)renderUIView;
- (void)renderUIWithProductModel:(id)arg1;
- (void)resetState;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

