//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PDFloorBaseViewModel.h"

#import "PDFloorViewProtocol-Protocol.h"

@class NSString, NewProductModel, PDNetworkAccessManager, WareInfoWhitePlanInfo, WhiteBar;

@interface PDWhiteBarViewModel : PDFloorBaseViewModel <PDFloorViewProtocol>
{
    WhiteBar *_whiteBar_Normal;
    NewProductModel *_model;
    WareInfoWhitePlanInfo *_planInfoSelected;
    PDNetworkAccessManager *_networkManager;
}

+ (void)load;
@property(retain, nonatomic) PDNetworkAccessManager *networkManager; // @synthesize networkManager=_networkManager;
@property(retain, nonatomic) WareInfoWhitePlanInfo *planInfoSelected; // @synthesize planInfoSelected=_planInfoSelected;
@property(retain, nonatomic) NewProductModel *model; // @synthesize model=_model;
@property(retain, nonatomic) WhiteBar *whiteBar_Normal; // @synthesize whiteBar_Normal=_whiteBar_Normal;
- (void).cxx_destruct;
- (void)whiteBarOpenUrl;
- (void)productGotoOrder;
- (void)showAddCartToast:(long long)arg1 msg:(id)arg2;
- (void)InternationalAuthFinish:(_Bool)arg1;
- (void)whiteBarIntoOrder;
- (void)whiteBarpay:(id)arg1;
- (void)whiteBarFinishLogin;
- (void)whiteBarpopupSelector;
- (void)floorTapped:(id)arg1;
- (void)renderUIWithProductModel:(id)arg1;
- (void)refreshViewForFloorTemplate;
- (void)resetState;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

