//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RCTView.h"

@class JDTemplatePlusPriceView, JDTemplatePriceLabel, JDTemplateSamPriceView, NSDictionary, RCTBridge;

@interface RCTJDPriceView : RCTView
{
    RCTBridge *_bridge;
    NSDictionary *_source;
    CDUnknownBlockType _onContentSizeChange;
    JDTemplatePriceLabel *_priceLabel;
    JDTemplateSamPriceView *_samPriceLabel;
    JDTemplatePlusPriceView *_plusPriceLabel;
    struct CGSize _previousContentSize;
}

@property(nonatomic) struct CGSize previousContentSize; // @synthesize previousContentSize=_previousContentSize;
@property(retain, nonatomic) JDTemplatePlusPriceView *plusPriceLabel; // @synthesize plusPriceLabel=_plusPriceLabel;
@property(retain, nonatomic) JDTemplateSamPriceView *samPriceLabel; // @synthesize samPriceLabel=_samPriceLabel;
@property(retain, nonatomic) JDTemplatePriceLabel *priceLabel; // @synthesize priceLabel=_priceLabel;
@property(copy, nonatomic) CDUnknownBlockType onContentSizeChange; // @synthesize onContentSizeChange=_onContentSizeChange;
@property(retain, nonatomic) NSDictionary *source; // @synthesize source=_source;
- (void).cxx_destruct;
- (id)customDirectEventTypes;
- (void)invalidateContentSize;
- (void)invalidPriceView;
- (void)reactSetFrame:(struct CGRect)arg1;
- (id)initWithBridge:(id)arg1;

@end

