//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JDWebViewLoadPolicyHandler.h"

@class NSString;

@interface RegisterPolicyHandler : JDWebViewLoadPolicyHandler
{
    _Bool _isRegisterFromWeb;
    NSString *_returnURL;
}

@property(nonatomic) _Bool isRegisterFromWeb; // @synthesize isRegisterFromWeb=_isRegisterFromWeb;
@property(copy, nonatomic) NSString *returnURL; // @synthesize returnURL=_returnURL;
- (void).cxx_destruct;
- (void)afterRegisterAction;
- (void)registerAction;
- (long long)webViewController:(id)arg1 webView:(id)arg2 decidePolicyForStartLoad:(id)arg3 navigationType:(long long)arg4 completion:(CDUnknownBlockType)arg5;

@end

