//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface ScanSearchResultMainBodyPoint : NSObject
{
    NSString *_top;
    NSString *_left;
    NSString *_bottom;
    NSString *_right;
    struct CGSize _size;
    struct CGRect _rectValue;
}

@property(nonatomic) struct CGRect rectValue; // @synthesize rectValue=_rectValue;
@property(nonatomic) struct CGSize size; // @synthesize size=_size;
@property(copy, nonatomic) NSString *right; // @synthesize right=_right;
@property(copy, nonatomic) NSString *bottom; // @synthesize bottom=_bottom;
@property(copy, nonatomic) NSString *left; // @synthesize left=_left;
@property(copy, nonatomic) NSString *top; // @synthesize top=_top;
- (void).cxx_destruct;

@end

