//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <JDDBaseModule/JDModel.h>

@class NSArray, NSNumber, NSString;

@interface SCShopCartProductModel : JDModel
{
    _Bool _tideUp;
    NSString *_name;
    NSString *_productCode;
    NSString *_buyCount;
    NSString *_productImageUrl;
    NSNumber *_suitsID;
    NSString *_SourceType;
    NSString *_SourceValue;
    NSString *_sType;
    NSString *_deliveryId;
    NSString *_locShopId;
    NSString *_activePromotionId;
    NSString *_dist;
    NSString *_jdPrice;
    NSString *_imgUrl;
    NSArray *_fsSkuIds;
}

@property(retain, nonatomic) NSArray *fsSkuIds; // @synthesize fsSkuIds=_fsSkuIds;
@property(copy, nonatomic) NSString *imgUrl; // @synthesize imgUrl=_imgUrl;
@property(copy, nonatomic) NSString *jdPrice; // @synthesize jdPrice=_jdPrice;
@property(copy, nonatomic) NSString *dist; // @synthesize dist=_dist;
@property(copy, nonatomic) NSString *activePromotionId; // @synthesize activePromotionId=_activePromotionId;
@property(nonatomic) _Bool tideUp; // @synthesize tideUp=_tideUp;
@property(copy, nonatomic) NSString *locShopId; // @synthesize locShopId=_locShopId;
@property(copy, nonatomic) NSString *deliveryId; // @synthesize deliveryId=_deliveryId;
@property(copy, nonatomic) NSString *sType; // @synthesize sType=_sType;
@property(copy, nonatomic) NSString *SourceValue; // @synthesize SourceValue=_SourceValue;
@property(copy, nonatomic) NSString *SourceType; // @synthesize SourceType=_SourceType;
@property(retain, nonatomic) NSNumber *suitsID; // @synthesize suitsID=_suitsID;
@property(copy, nonatomic) NSString *productImageUrl; // @synthesize productImageUrl=_productImageUrl;
@property(copy, nonatomic) NSString *buyCount; // @synthesize buyCount=_buyCount;
@property(copy, nonatomic) NSString *productCode; // @synthesize productCode=_productCode;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (void)setDataWithDic:(id)arg1;
- (id)init;
- (void)dealloc;

@end

