//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface SCShopCartClearDataModel : NSObject
{
    NSString *_imageDomain;
    NSString *_mainTitle;
    NSString *_subTitle;
    NSString *_resultCode;
    NSString *_code;
    NSArray *_groupData;
}

@property(copy, nonatomic) NSArray *groupData; // @synthesize groupData=_groupData;
@property(copy, nonatomic) NSString *code; // @synthesize code=_code;
@property(copy, nonatomic) NSString *resultCode; // @synthesize resultCode=_resultCode;
@property(copy, nonatomic) NSString *subTitle; // @synthesize subTitle=_subTitle;
@property(copy, nonatomic) NSString *mainTitle; // @synthesize mainTitle=_mainTitle;
@property(copy, nonatomic) NSString *imageDomain; // @synthesize imageDomain=_imageDomain;
- (void).cxx_destruct;

@end

