//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSOperationQueue;

@interface SDWebImageExceptionManager : NSObject
{
    NSOperationQueue *_queue;
}

+ (void)SDWebImageDecodeImageFails:(id)arg1;
+ (void)SDWebImageDPGImage:(id)arg1;
+ (void)SDWebImageDNSIPFails:(id)arg1;
+ (void)load;
+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)sharedSDWebImageExceptionManager;
@property(retain, nonatomic) NSOperationQueue *queue; // @synthesize queue=_queue;
- (void)sdWebImageError:(id)arg1 error:(id)arg2;
- (void)webpDocodeError:(id)arg1;
- (void)illegalUrl:(id)arg1;
- (id)init;
- (id)autorelease;
- (oneway void)release;
- (unsigned long long)retainCount;
- (id)retain;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

