//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JDViewController.h"

#import "JDBaseToastViewDelegate-Protocol.h"
#import "JDImageEditorControllerDelegate-Protocol.h"
#import "JDPhotoViewDelegate-Protocol.h"
#import "JDVideoEditorControllerDelegate-Protocol.h"
#import "SOZoomOutTransitionAnimationContextDelegate-Protocol.h"
#import "ShareOrderAlbumBottomViewDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"

@class NSMutableArray, NSMutableSet, NSString, ShareOrderAlbumBottomView, ShareOrderAssetProduct, ShareOrderPalletView, ShareOrderVideoEditButtonView, UIButton, UIImageView, UIScrollView, UIView;
@protocol ShareOrderAblumImageViewProtocol;

@interface ShareOrderAblumImageViewController : JDViewController <JDBaseToastViewDelegate, UIScrollViewDelegate, JDPhotoViewDelegate, ShareOrderAlbumBottomViewDelegate, JDVideoEditorControllerDelegate, SOZoomOutTransitionAnimationContextDelegate, JDImageEditorControllerDelegate>
{
    UIButton *checkButton;
    _Bool isInit;
    _Bool viewDisappear;
    ShareOrderPalletView *palletView;
    long long _reportIndex;
    _Bool _needReCaptureZommInContainer;
    UIView *_topBackView;
    _Bool _isShowDragImageIntrol;
    _Bool _isFormPreview;
    _Bool _videoClippingSwitch;
    _Bool _videoFilterSwitch;
    _Bool _imageFilterSwitch;
    _Bool _imageAnimationSwitch;
    _Bool _isSelectItem;
    _Bool _isChange;
    _Bool _isAutoPlayVedio;
    _Bool _editIsMainShow;
    float _heightToTop;
    float _heightToBottom;
    long long _selectedIndex;
    NSMutableArray *_items;
    long long _initIndex;
    UIImageView *_smallImageView;
    double _takeVideoMaxTime;
    double _takeVideoMinTime;
    id <ShareOrderAblumImageViewProtocol> _delegate;
    NSMutableSet *_visibleImageViews;
    NSMutableSet *_reusedImageViews;
    UIScrollView *_scrollView;
    ShareOrderAlbumBottomView *_bottomPalletView;
    ShareOrderVideoEditButtonView *_editButton;
    long long _reloadImageCount;
    ShareOrderAssetProduct *_tempFilterAsset;
}

@property(retain, nonatomic) ShareOrderAssetProduct *tempFilterAsset; // @synthesize tempFilterAsset=_tempFilterAsset;
@property(nonatomic) long long reloadImageCount; // @synthesize reloadImageCount=_reloadImageCount;
@property(nonatomic) _Bool editIsMainShow; // @synthesize editIsMainShow=_editIsMainShow;
@property(nonatomic) _Bool isAutoPlayVedio; // @synthesize isAutoPlayVedio=_isAutoPlayVedio;
@property(nonatomic) _Bool isChange; // @synthesize isChange=_isChange;
@property(retain, nonatomic) ShareOrderVideoEditButtonView *editButton; // @synthesize editButton=_editButton;
@property(nonatomic) _Bool isSelectItem; // @synthesize isSelectItem=_isSelectItem;
@property(retain, nonatomic) ShareOrderAlbumBottomView *bottomPalletView; // @synthesize bottomPalletView=_bottomPalletView;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(retain, nonatomic) NSMutableSet *reusedImageViews; // @synthesize reusedImageViews=_reusedImageViews;
@property(retain, nonatomic) NSMutableSet *visibleImageViews; // @synthesize visibleImageViews=_visibleImageViews;
@property(nonatomic) id <ShareOrderAblumImageViewProtocol> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool imageAnimationSwitch; // @synthesize imageAnimationSwitch=_imageAnimationSwitch;
@property(nonatomic) _Bool imageFilterSwitch; // @synthesize imageFilterSwitch=_imageFilterSwitch;
@property(nonatomic) _Bool videoFilterSwitch; // @synthesize videoFilterSwitch=_videoFilterSwitch;
@property(nonatomic) _Bool videoClippingSwitch; // @synthesize videoClippingSwitch=_videoClippingSwitch;
@property(nonatomic) _Bool isFormPreview; // @synthesize isFormPreview=_isFormPreview;
@property(nonatomic) double takeVideoMinTime; // @synthesize takeVideoMinTime=_takeVideoMinTime;
@property(nonatomic) double takeVideoMaxTime; // @synthesize takeVideoMaxTime=_takeVideoMaxTime;
@property(nonatomic) float heightToBottom; // @synthesize heightToBottom=_heightToBottom;
@property(nonatomic) float heightToTop; // @synthesize heightToTop=_heightToTop;
@property(retain, nonatomic) UIImageView *smallImageView; // @synthesize smallImageView=_smallImageView;
@property(nonatomic) long long initIndex; // @synthesize initIndex=_initIndex;
@property(retain, nonatomic) NSMutableArray *items; // @synthesize items=_items;
@property(nonatomic) long long selectedIndex; // @synthesize selectedIndex=_selectedIndex;
- (void).cxx_destruct;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)jd_imageEditorControllerDidCancel:(id)arg1;
- (void)jd_imageEditorController:(id)arg1 didSaveEditedImageToPath:(id)arg2 filterType:(id)arg3;
- (id)getCurrentVisibleAlbumImageView;
- (void)so_zoomTransitionAnimationContextEndAnimation:(id)arg1;
- (void)so_zoomTransitionAnimationContextCancelAnimationCompletion:(id)arg1;
- (_Bool)so_zoomOutTransitionAnimationShouldReCaptureZoomInContainerSnapshot:(id)arg1;
- (_Bool)so_zoomOutTransitionAnimationContextShouldEnableDropGesture:(id)arg1;
- (void)so_zoomOutTransitionAnimationContextBeginDrag:(id)arg1;
- (id)so_zoomOutTransitionAnimationContextGetStartLocationView:(id)arg1;
- (void)so_zoomOutTransitionAnimationContextEndDrag:(id)arg1;
- (void)uploadCloseMTAWithCloseType:(long long)arg1 eventName:(id)arg2;
- (id)so_zoomTransitionAnimationContextGetEndLocationView:(id)arg1 transferInfo:(id)arg2 startImage:(id)arg3;
- (id)so_zoomTransitionAnimationContextPrepareAnimationTransferInfo:(id)arg1;
- (void)reloadView:(id)arg1;
- (void)popToShareorder:(id)arg1;
- (void)popCurrentViewControllerWithCloseType:(long long)arg1;
- (void)popCurrentViewController;
- (void)didTapPhotoView:(id)arg1;
- (void)didTapCheckButton;
- (void)reloadImageWithIndex;
- (void)showImageViewAtIndex:(long long)arg1;
- (void)checkVideoDuration;
- (void)showImages;
- (void)checkButtonSelect;
- (void)didSelectItem:(long long)arg1 product:(id)arg2;
- (void)didPreviewTap:(long long)arg1;
- (void)editVideo;
- (void)checkEditButtonStatus;
- (void)jd_videoEditorController:(id)arg1 didChangeEditor:(long long)arg2;
- (void)jd_videoEditorController:(id)arg1 didEnterEditor:(long long)arg2;
- (void)jd_videoEditorControllerDidCancel:(id)arg1;
- (void)jd_videoEditorController:(id)arg1 didSaveEditedVideoToPath:(id)arg2 filterType:(id)arg3 isTrimmed:(_Bool)arg4;
- (void)ayncDeactiveAudioSession;
- (void)stopVideo;
- (void)autoPlayVideo;
- (void)stopAllVideo;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)popiCloudMsg;
- (void)scrollViewDidScroll:(id)arg1;
- (void)viewWillLayoutSubviews;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)setupScrollView;
- (id)init;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

