//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JDPhotoView.h"

#import "JDBaseToastViewDelegate-Protocol.h"
#import "JDVideoPlayerViewDelegate-Protocol.h"

@class JDVideoPlayerView, NSString, UIImageView;

@interface ShareOrderAlbumImageView : JDPhotoView <JDVideoPlayerViewDelegate, JDBaseToastViewDelegate>
{
    _Bool _isVideo;
    NSString *_localIdentifier;
    CDUnknownBlockType _closeView;
    UIImageView *_playIcon;
    JDVideoPlayerView *_videoPlayer;
}

@property(retain, nonatomic) JDVideoPlayerView *videoPlayer; // @synthesize videoPlayer=_videoPlayer;
@property(retain, nonatomic) UIImageView *playIcon; // @synthesize playIcon=_playIcon;
@property(copy, nonatomic) CDUnknownBlockType closeView; // @synthesize closeView=_closeView;
@property(copy, nonatomic) NSString *localIdentifier; // @synthesize localIdentifier=_localIdentifier;
@property(nonatomic) _Bool isVideo; // @synthesize isVideo=_isVideo;
- (void).cxx_destruct;
- (void)playerView:(id)arg1 eventChanged:(unsigned long long)arg2 info:(id)arg3;
- (void)hideImg;
- (void)stop;
- (void)playVideo;
- (void)play;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

