//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class LOTAnimationView, NSArray, NSMutableArray, UIImage, UIPanGestureRecognizer, UITapGestureRecognizer;
@protocol ShareOrderCommentRateViewDelegate;

@interface ShareOrderCommentRateView : UIView
{
    UIImage *_notSelectedImage;
    UIImage *_halfSelectedImage;
    UIImage *_fullSelectedImage;
    NSMutableArray *_imageViews;
    struct CGSize _minImageSize;
    float _rating;
    _Bool _editable;
    int _maxRating;
    int _midMargin;
    int _leftMargin;
    UIPanGestureRecognizer *_pan;
    UITapGestureRecognizer *_tap;
    _Bool _canCallDelegate;
    int _minRating;
    NSArray *_imageArray;
    id <ShareOrderCommentRateViewDelegate> _delegate;
    LOTAnimationView *_lottieView;
}

+ (id)getAnGradientRateViewWithFrame:(struct CGRect)arg1 WithNotSelectedImageName:(id)arg2 WithHalfSelectedImageName:(id)arg3;
@property(nonatomic, getter=isCanCallDelegate) _Bool canCallDelegate; // @synthesize canCallDelegate=_canCallDelegate;
@property(retain, nonatomic) LOTAnimationView *lottieView; // @synthesize lottieView=_lottieView;
@property(nonatomic) int minRating; // @synthesize minRating=_minRating;
@property(nonatomic) int midMargin; // @synthesize midMargin=_midMargin;
@property(nonatomic) int leftMargin; // @synthesize leftMargin=_leftMargin;
@property(nonatomic) __weak id <ShareOrderCommentRateViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) int maxRating; // @synthesize maxRating=_maxRating;
@property(nonatomic) _Bool editable; // @synthesize editable=_editable;
@property(nonatomic) float rating; // @synthesize rating=_rating;
@property(retain, nonatomic) NSArray *imageArray; // @synthesize imageArray=_imageArray;
@property(retain, nonatomic) UIImage *fullSelectedImage; // @synthesize fullSelectedImage=_fullSelectedImage;
@property(retain, nonatomic) UIImage *halfSelectedImage; // @synthesize halfSelectedImage=_halfSelectedImage;
@property(retain, nonatomic) UIImage *notSelectedImage; // @synthesize notSelectedImage=_notSelectedImage;
- (void).cxx_destruct;
- (void)pan:(id)arg1;
- (void)tap:(id)arg1;
- (void)handleTouchAtLocation:(struct CGPoint)arg1;
- (void)layoutSubviews;
- (void)refresh;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)baseInit;

@end

