//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ShareOrderCarServiceBaseProtocol-Protocol.h"

@class ShareOrderCarServicePhotoModel, ShareOrderProduct, UIImageView;

@protocol ShareOrderCarServicePhotoCellDelegate <ShareOrderCarServiceBaseProtocol>

@optional
- (void)openImageWithProductInfo:(ShareOrderProduct *)arg1 WithModel:(ShareOrderCarServicePhotoModel *)arg2 WithImageView:(UIImageView *)arg3;
- (void)openVideoWithProductInfo:(ShareOrderProduct *)arg1;
- (void)delegatePhotoWithProductInfo:(ShareOrderProduct *)arg1;
- (void)clickAddPhotoWithModel:(ShareOrderCarServicePhotoModel *)arg1;
@end

