//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIPageControl.h>

@class UIImage;

@interface ShareOrderPageControl : UIPageControl
{
    UIImage *_pageStateNormalImage;
    UIImage *_pageStateHighlightedImage;
    double _pageMargin;
}

@property(nonatomic) double pageMargin; // @synthesize pageMargin=_pageMargin;
@property(retain, nonatomic) UIImage *pageStateHighlightedImage; // @synthesize pageStateHighlightedImage=_pageStateHighlightedImage;
@property(retain, nonatomic) UIImage *pageStateNormalImage; // @synthesize pageStateNormalImage=_pageStateNormalImage;
- (void).cxx_destruct;
- (void)setCurrentPage:(long long)arg1;
- (void)updateDots;
- (id)init;

@end

