//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray, NSString, NSTimer;

@interface SHAVPlayerBuryData : NSObject
{
    NSString *_playerInitTime;
    NSString *_sessionId;
    NSMutableArray *_performInfoArray;
    double _sessionStartTime;
    double _sessionEndTime;
    _Bool _isPerforming;
    _Bool _hasInitPlayer;
    _Bool _hasUploadInitTime;
    NSString *_roomId;
    NSString *_playType;
    NSString *_videoType;
    NSString *_source;
    NSString *_roomNum;
    NSString *_typeId;
    NSString *_chId;
    NSString *_sku;
    NSString *_videoDuration;
    NSString *_playDuration;
    NSString *_status;
    NSString *_isError;
    NSString *_occurTime;
    NSString *_dockingId;
    NSString *_storageSource;
    NSString *_videoInitTime;
    NSString *_playTimes;
    NSString *_playTypeEx;
    NSString *_videoTypeEx;
    NSString *_sourceEx;
    NSTimer *_collectTimer;
    NSTimer *_uploadTimer;
}

@property(retain, nonatomic) NSTimer *uploadTimer; // @synthesize uploadTimer=_uploadTimer;
@property(retain, nonatomic) NSTimer *collectTimer; // @synthesize collectTimer=_collectTimer;
@property(copy, nonatomic) NSString *sourceEx; // @synthesize sourceEx=_sourceEx;
@property(copy, nonatomic) NSString *videoTypeEx; // @synthesize videoTypeEx=_videoTypeEx;
@property(copy, nonatomic) NSString *playTypeEx; // @synthesize playTypeEx=_playTypeEx;
@property(copy, nonatomic) NSString *playTimes; // @synthesize playTimes=_playTimes;
@property(copy, nonatomic) NSString *videoInitTime; // @synthesize videoInitTime=_videoInitTime;
@property(copy, nonatomic) NSString *storageSource; // @synthesize storageSource=_storageSource;
@property(copy, nonatomic) NSString *dockingId; // @synthesize dockingId=_dockingId;
@property(copy, nonatomic) NSString *occurTime; // @synthesize occurTime=_occurTime;
@property(copy, nonatomic) NSString *isError; // @synthesize isError=_isError;
@property(copy, nonatomic) NSString *status; // @synthesize status=_status;
@property(copy, nonatomic) NSString *playDuration; // @synthesize playDuration=_playDuration;
@property(copy, nonatomic) NSString *videoDuration; // @synthesize videoDuration=_videoDuration;
@property(copy, nonatomic) NSString *sku; // @synthesize sku=_sku;
@property(copy, nonatomic) NSString *chId; // @synthesize chId=_chId;
@property(copy, nonatomic) NSString *typeId; // @synthesize typeId=_typeId;
@property(copy, nonatomic) NSString *roomNum; // @synthesize roomNum=_roomNum;
@property(copy, nonatomic) NSString *source; // @synthesize source=_source;
@property(copy, nonatomic) NSString *videoType; // @synthesize videoType=_videoType;
@property(copy, nonatomic) NSString *playType; // @synthesize playType=_playType;
@property(copy, nonatomic) NSString *roomId; // @synthesize roomId=_roomId;
- (void).cxx_destruct;
- (id)p_getInitTime;
- (void)p_releaseTimer;
- (void)p_getRandomSession;
- (void)p_uploadData;
- (void)p_addPerformData:(id)arg1;
- (void)p_collectData;
- (id)getURLParameters:(id)arg1;
- (void)newUploadBuryData;
- (void)newSetBuryNecessaryPara:(id)arg1 playType:(id)arg2 videotype:(id)arg3 source:(id)arg4 initTime:(id)arg5 typeId:(id)arg6 chId:(id)arg7 sku:(id)arg8 videoDuration:(id)arg9;
- (void)setBuryNecessaryPara:(id)arg1 playType:(id)arg2 videotype:(id)arg3 source:(id)arg4 initTime:(id)arg5;
- (void)resetSessionId;
- (void)setInitTime:(id)arg1;
- (void)stopBury;
- (void)startBury;
- (id)init;

@end

