//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface SHVPPortraitSmallVideoListModel : NSObject
{
    NSArray *_list;
    NSString *_offset;
    NSString *_tagTitle;
    long long _pvSize;
    NSString *_code;
    long long _subCode;
}

+ (id)objectClassInArray;
@property(nonatomic) long long subCode; // @synthesize subCode=_subCode;
@property(copy, nonatomic) NSString *code; // @synthesize code=_code;
@property(nonatomic) long long pvSize; // @synthesize pvSize=_pvSize;
@property(copy, nonatomic) NSString *tagTitle; // @synthesize tagTitle=_tagTitle;
@property(copy, nonatomic) NSString *offset; // @synthesize offset=_offset;
@property(retain, nonatomic) NSArray *list; // @synthesize list=_list;
- (void).cxx_destruct;

@end

