//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FinderVideoBuyAVPlayer, NSString, SHVPPortraitSmallVideoItemModel, SHVPPortraitSmallVideoListPlayView, UIView;

@interface SHVPPortraitSmallVideoPlayerManager : NSObject
{
    _Bool _isFullScreen;
    _Bool _isPlayBeforePause;
    _Bool _isResignActive;
    _Bool _noNeedMonitorOrientation;
    _Bool _shouldResetPlayerView;
    _Bool _isReplay;
    _Bool _isAnimationing;
    SHVPPortraitSmallVideoItemModel *_model;
    FinderVideoBuyAVPlayer *_FVBPlayer;
    SHVPPortraitSmallVideoListPlayView *_videoView;
    double _currentPlayDuration;
    double _totalDuration;
    long long _originDeviceOrientation;
    NSString *_transitionViewOriginalFrame;
    NSString *_viewOriginalFrame;
    UIView *_verticalSuperView;
    UIView *_markView;
    NSString *_currentShowingItemId;
}

+ (id)sharedManager;
@property(nonatomic) _Bool isAnimationing; // @synthesize isAnimationing=_isAnimationing;
@property(copy, nonatomic) NSString *currentShowingItemId; // @synthesize currentShowingItemId=_currentShowingItemId;
@property(retain, nonatomic) UIView *markView; // @synthesize markView=_markView;
@property(nonatomic) __weak UIView *verticalSuperView; // @synthesize verticalSuperView=_verticalSuperView;
@property(retain, nonatomic) NSString *viewOriginalFrame; // @synthesize viewOriginalFrame=_viewOriginalFrame;
@property(retain, nonatomic) NSString *transitionViewOriginalFrame; // @synthesize transitionViewOriginalFrame=_transitionViewOriginalFrame;
@property(nonatomic) long long originDeviceOrientation; // @synthesize originDeviceOrientation=_originDeviceOrientation;
@property(nonatomic) _Bool isReplay; // @synthesize isReplay=_isReplay;
@property(nonatomic) _Bool shouldResetPlayerView; // @synthesize shouldResetPlayerView=_shouldResetPlayerView;
@property(nonatomic) _Bool noNeedMonitorOrientation; // @synthesize noNeedMonitorOrientation=_noNeedMonitorOrientation;
@property(nonatomic) _Bool isResignActive; // @synthesize isResignActive=_isResignActive;
@property(nonatomic) double totalDuration; // @synthesize totalDuration=_totalDuration;
@property(nonatomic) double currentPlayDuration; // @synthesize currentPlayDuration=_currentPlayDuration;
@property(retain, nonatomic) SHVPPortraitSmallVideoListPlayView *videoView; // @synthesize videoView=_videoView;
@property(retain, nonatomic) FinderVideoBuyAVPlayer *FVBPlayer; // @synthesize FVBPlayer=_FVBPlayer;
@property(nonatomic) _Bool isPlayBeforePause; // @synthesize isPlayBeforePause=_isPlayBeforePause;
@property(nonatomic) _Bool isFullScreen; // @synthesize isFullScreen=_isFullScreen;
@property(retain, nonatomic) SHVPPortraitSmallVideoItemModel *model; // @synthesize model=_model;
- (void).cxx_destruct;
- (void)resetPlayerManager;
- (void)destoryFVBPlayer;
- (void)removePlayerViewFromSuperView;
- (void)resetPlayParam;
- (void)destoryCurrentPlayer;
- (struct CGRect)getPlayerViewVerticalFullScreenFrame;
- (struct CGRect)getPlayerViewFullScreenFrame;
- (void)transitionViewWhenPlayFinishedIfNeed;
- (void)transitionViewToVerticalScreen:(_Bool)arg1 needReport:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)transitionFullScreen180degrees:(long long)arg1;
- (void)transitionViewToFullScreenWithorientation:(long long)arg1;
- (void)transitionViewToVerticalSmallScreen;
- (void)transitionViewToVerticalFullScreen;
- (void)stopCoreMotion;
- (void)deviceOrientationDidChange:(id)arg1;
- (void)startUpdateMotion;
- (void)setPlayViewShow:(id)arg1;
- (void)listPlayViewBackVerticle:(id)arg1;
- (void)checkNetworkEnrimoentAndToastInfo;
- (void)listPlayViewReplay:(id)arg1;
- (void)listPlayView:(id)arg1 isFullScreen:(_Bool)arg2;
- (void)listPlayViewReloadPlayerData:(id)arg1;
- (void)p_prepareDoneEvent;
- (void)getPlayer:(id)arg1 event:(int)arg2;
- (void)applicationWillTerminateNotificationEvent:(id)arg1;
- (void)netwotkReachabilityChanged:(id)arg1;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)applicationWillResignActive:(id)arg1;
- (void)removeNotificationObservers;
- (void)addNotificationObservers;
- (void)recordVideoPlayCurrentDuration;
- (void)playerPosition:(double)arg1 duration:(double)arg2;
- (void)replay;
- (void)pause;
- (void)play;
- (void)setControlPlayerView;
- (void)setupPlayerView;
- (void)setUpPlayerParameter;
- (void)registerWithURLPlayBack:(id)arg1;

@end

