//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class SHVPActivityItemModel, SHVPCustomButton, UIImageView, UILabel;

@interface SHVPCouponItemCell : UICollectionViewCell
{
    UIImageView *_imageView;
    UILabel *_denominationLab;
    UILabel *_quotaLab;
    SHVPCustomButton *_getCoupondBtn;
    SHVPActivityItemModel *_model;
}

@property(retain, nonatomic) SHVPActivityItemModel *model; // @synthesize model=_model;
@property(retain, nonatomic) SHVPCustomButton *getCoupondBtn; // @synthesize getCoupondBtn=_getCoupondBtn;
@property(retain, nonatomic) UILabel *quotaLab; // @synthesize quotaLab=_quotaLab;
@property(retain, nonatomic) UILabel *denominationLab; // @synthesize denominationLab=_denominationLab;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
- (void).cxx_destruct;
- (void)changeConpondStatus:(long long)arg1;
- (void)setWillGetStatus;
- (void)setGetOutStatus;
- (void)assignValue:(id)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

