//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FinderArticleDetailCaptchaInfo, FinderArticleDetailFirstLevelCommentModel, NSMutableArray, NSString;

@interface SHVPPortraitSmallVideoCommentModel : NSObject
{
    NSMutableArray *_hotCommentsData;
    NSMutableArray *_totalCommentsData;
    FinderArticleDetailCaptchaInfo *_captchaInfo;
    FinderArticleDetailFirstLevelCommentModel *_praiseCommentModel;
    long long _commentCount;
    NSString *_offset;
}

@property(copy, nonatomic) NSString *offset; // @synthesize offset=_offset;
@property(nonatomic) long long commentCount; // @synthesize commentCount=_commentCount;
@property(retain, nonatomic) FinderArticleDetailFirstLevelCommentModel *praiseCommentModel; // @synthesize praiseCommentModel=_praiseCommentModel;
@property(retain, nonatomic) FinderArticleDetailCaptchaInfo *captchaInfo; // @synthesize captchaInfo=_captchaInfo;
@property(retain, nonatomic) NSMutableArray *totalCommentsData; // @synthesize totalCommentsData=_totalCommentsData;
@property(retain, nonatomic) NSMutableArray *hotCommentsData; // @synthesize hotCommentsData=_hotCommentsData;
- (void).cxx_destruct;
- (void)refreshPraiseCommentState;
- (void)refreshCommentState:(id)arg1;
- (void)appendNoCommentModel;
- (void)updateDeleteComment:(id)arg1;
- (void)updateAddComment:(id)arg1;
- (void)commentData:(id)arg1;
- (id)fetchModel:(id)arg1;
- (long long)numberOfRowInSection:(long long)arg1;
- (double)heightForHeaderInSection:(long long)arg1;
- (long long)numberOfSection;
- (id)init;

@end

