//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"
#import "UICollectionViewDelegateFlowLayout-Protocol.h"

@class NSMutableArray, NSString, UICollectionView;
@protocol SingleKillSpikeGoodsCardViewDataSource, SingleKillSpikeGoodsCardViewDelegate;

@interface SingleKillSpikeGoodsCardView : UIView <UICollectionViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout>
{
    double _dragStartX;
    double _dragEndX;
    _Bool _isDragScroll;
    _Bool _isNeedRegisterCell;
    NSMutableArray *_datas;
    id <SingleKillSpikeGoodsCardViewDelegate> _delegate;
    id <SingleKillSpikeGoodsCardViewDataSource> _dataSource;
    UICollectionView *_collectionView;
    long long _selectedIndex;
    long long _showCardNumber;
}

@property(nonatomic) _Bool isNeedRegisterCell; // @synthesize isNeedRegisterCell=_isNeedRegisterCell;
@property(nonatomic) long long showCardNumber; // @synthesize showCardNumber=_showCardNumber;
@property(nonatomic) long long selectedIndex; // @synthesize selectedIndex=_selectedIndex;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(nonatomic) id <SingleKillSpikeGoodsCardViewDataSource> dataSource; // @synthesize dataSource=_dataSource;
@property(nonatomic) id <SingleKillSpikeGoodsCardViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSMutableArray *datas; // @synthesize datas=_datas;
- (void).cxx_destruct;
- (id)cellModelForIndex:(long long)arg1;
- (long long)numberOfCards;
- (_Bool)shouldLoop;
- (void)didSelectedCardAtIndex:(long long)arg1;
- (void)collectionView:(id)arg1 willDisplayCell:(id)arg2 forItemAtIndexPath:(id)arg3;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (void)p_scrollToCenter;
- (void)p_fixCellToCenter;
- (double)p_collectionInset;
- (double)p_cellMargin;
- (double)p_cellHeight;
- (double)p_cellWidth;
- (void)reloadCardView;
- (void)switchToIndex:(long long)arg1 animated:(_Bool)arg2;
- (void)congfigDatas;
- (void)registerCellClass;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

