//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionReusableView.h>

@class JDFooterLoadingView, UILabel;
@protocol SmallVideoFooterReloadDelegate;

@interface SmallVideoCollectionFooter : UICollectionReusableView
{
    JDFooterLoadingView *_loadingView;
    UILabel *_footReloadView;
    UILabel *_footNoMoreItemView;
    id <SmallVideoFooterReloadDelegate> _delegate;
}

@property(nonatomic) __weak id <SmallVideoFooterReloadDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UILabel *footNoMoreItemView; // @synthesize footNoMoreItemView=_footNoMoreItemView;
@property(retain, nonatomic) UILabel *footReloadView; // @synthesize footReloadView=_footReloadView;
@property(retain, nonatomic) JDFooterLoadingView *loadingView; // @synthesize loadingView=_loadingView;
- (void).cxx_destruct;
- (void)reloadTapped;
- (void)bindData:(long long)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

