//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class JDImageView, SSSBSKFloorModel;

@interface SSSBSKFloatView : UIView
{
    struct CGPoint beginPoint;
    JDImageView *_ivIcon;
    SSSBSKFloorModel *_floorModel;
}

@property(retain, nonatomic) SSSBSKFloorModel *floorModel; // @synthesize floorModel=_floorModel;
@property(retain, nonatomic) JDImageView *ivIcon; // @synthesize ivIcon=_ivIcon;
- (void).cxx_destruct;
- (void)fillData:(id)arg1;
- (void)tapFloatView:(id)arg1;
- (void)paned:(id)arg1;
- (void)initUI;
- (id)initWithFrame:(struct CGRect)arg1;

@end

