//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SSSBSKBaseModel.h"

@class NSArray, NSString;

@interface SSSBSKListItemModel : SSSBSKBaseModel
{
    NSString *_sourceValue;
    NSString *_brandWords;
    NSString *_brandImg;
    NSString *_logoImg;
    NSString *_brandImgHeight;
    NSString *_brandName;
    NSString *_startTimeRemain;
    NSString *_brandIdOld;
    NSString *_itemColor;
    NSString *_startTimeShow;
    NSString *_brandId;
    NSString *_subTitle;
    NSString *_title;
    NSString *_brandImgWidth;
    NSArray *_goodsList;
    NSString *_endTimeRemain;
    NSString *_clk;
}

+ (id)objectClassInArray;
+ (id)replacedKeyFromPropertyName;
@property(copy, nonatomic) NSString *clk; // @synthesize clk=_clk;
@property(copy, nonatomic) NSString *endTimeRemain; // @synthesize endTimeRemain=_endTimeRemain;
@property(retain, nonatomic) NSArray *goodsList; // @synthesize goodsList=_goodsList;
@property(copy, nonatomic) NSString *brandImgWidth; // @synthesize brandImgWidth=_brandImgWidth;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(copy, nonatomic) NSString *subTitle; // @synthesize subTitle=_subTitle;
@property(copy, nonatomic) NSString *brandId; // @synthesize brandId=_brandId;
@property(copy, nonatomic) NSString *startTimeShow; // @synthesize startTimeShow=_startTimeShow;
@property(copy, nonatomic) NSString *itemColor; // @synthesize itemColor=_itemColor;
@property(copy, nonatomic) NSString *brandIdOld; // @synthesize brandIdOld=_brandIdOld;
@property(copy, nonatomic) NSString *startTimeRemain; // @synthesize startTimeRemain=_startTimeRemain;
@property(copy, nonatomic) NSString *brandName; // @synthesize brandName=_brandName;
@property(copy, nonatomic) NSString *brandImgHeight; // @synthesize brandImgHeight=_brandImgHeight;
@property(copy, nonatomic) NSString *logoImg; // @synthesize logoImg=_logoImg;
@property(copy, nonatomic) NSString *brandImg; // @synthesize brandImg=_brandImg;
@property(copy, nonatomic) NSString *brandWords; // @synthesize brandWords=_brandWords;
@property(copy, nonatomic) NSString *sourceValue; // @synthesize sourceValue=_sourceValue;
- (void).cxx_destruct;

@end

