//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class JDImageView, UILabel;

@interface SSSBSKBrandTitleView : UIView
{
    JDImageView *_brandLogo;
    UILabel *_brandTitle;
    UILabel *_brandWord;
}

@property(retain, nonatomic) UILabel *brandWord; // @synthesize brandWord=_brandWord;
@property(retain, nonatomic) UILabel *brandTitle; // @synthesize brandTitle=_brandTitle;
@property(retain, nonatomic) JDImageView *brandLogo; // @synthesize brandLogo=_brandLogo;
- (void).cxx_destruct;
- (void)fillData:(id)arg1;
- (void)initUI;
- (id)initWithFrame:(struct CGRect)arg1;

@end

