//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class SSSGAggregateListModel, SSSGAggregateViewModel, SecKillRequestManager;

@interface SSSGAggregateDataProvider : NSObject
{
    SecKillRequestManager *_requestManager;
    SSSGAggregateListModel *_aggregateListModel;
    SSSGAggregateViewModel *_aggregateViewModel;
}

@property(retain, nonatomic) SSSGAggregateViewModel *aggregateViewModel; // @synthesize aggregateViewModel=_aggregateViewModel;
@property(retain, nonatomic) SSSGAggregateListModel *aggregateListModel; // @synthesize aggregateListModel=_aggregateListModel;
@property(retain, nonatomic) SecKillRequestManager *requestManager; // @synthesize requestManager=_requestManager;
- (void).cxx_destruct;
- (void)cleanCacheData;
- (_Bool)shouldToastAtIndex:(long long)arg1;
- (id)fetchShareModel;
- (void)requestDataWithParams:(id)arg1 callBack:(CDUnknownBlockType)arg2;
- (id)init;

@end

