//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SecKillBaseViewController.h"

#import "SSSShopTabItemDelegate-Protocol.h"
#import "SSSShopWareViewDelegate-Protocol.h"
#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"
#import "UICollectionViewDelegateFlowLayout-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"

@class NSIndexPath, NSString, SSSGroupShopDataManage, SSSShopTabItemView, SSSTableViewPositionHelper, SeckillTitleView, UICollectionView;

@interface SSSGroupShopViewController : SecKillBaseViewController <UICollectionViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout, UIScrollViewDelegate, SSSShopTabItemDelegate, SSSShopWareViewDelegate>
{
    NSString *_isFromGouShiHui;
    SSSShopTabItemView *_itemView;
    UICollectionView *_pagerView;
    SSSGroupShopDataManage *_dataManage;
    SSSTableViewPositionHelper *_positionHelper;
    NSIndexPath *_currentIndex;
    NSIndexPath *_preIndex;
    NSString *_tabPosNum;
    NSString *_innerLink;
    SeckillTitleView *_titleImageView;
}

@property(retain, nonatomic) SeckillTitleView *titleImageView; // @synthesize titleImageView=_titleImageView;
@property(copy, nonatomic) NSString *innerLink; // @synthesize innerLink=_innerLink;
@property(retain, nonatomic) NSString *tabPosNum; // @synthesize tabPosNum=_tabPosNum;
@property(retain, nonatomic) NSIndexPath *preIndex; // @synthesize preIndex=_preIndex;
@property(retain, nonatomic) NSIndexPath *currentIndex; // @synthesize currentIndex=_currentIndex;
@property(retain, nonatomic) SSSTableViewPositionHelper *positionHelper; // @synthesize positionHelper=_positionHelper;
@property(retain, nonatomic) SSSGroupShopDataManage *dataManage; // @synthesize dataManage=_dataManage;
@property(retain, nonatomic) UICollectionView *pagerView; // @synthesize pagerView=_pagerView;
@property(retain, nonatomic) SSSShopTabItemView *itemView; // @synthesize itemView=_itemView;
@property(retain, nonatomic) NSString *isFromGouShiHui; // @synthesize isFromGouShiHui=_isFromGouShiHui;
- (void).cxx_destruct;
- (struct CGRect)pagerViewFrame;
- (struct CGRect)itemViewFrame;
- (id)getTabPos;
- (void)reloadAllViews;
- (void)fetchData;
- (void)reconnect;
- (void)initData;
- (void)setupUI;
- (double)getInterval;
- (void)tabViewScrollsToTop;
- (void)shopWareViewReloadData:(id)arg1;
- (void)shopWareViewLoadNextData:(id)arg1;
- (void)showProductDetailWithSingleModel:(id)arg1;
- (void)shopWareView:(id)arg1 clickCell:(id)arg2;
- (id)creatIndexPath:(long long)arg1;
- (void)collectionView:(id)arg1 didEndDisplayingCell:(id)arg2 forItemAtIndexPath:(id)arg3;
- (void)sssShopChangeTabRecordDepth;
- (void)collectionView:(id)arg1 willDisplayCell:(id)arg2 forItemAtIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (void)shopViewDidSelectItemAtIndexPath:(id)arg1;
- (id)cateModelAtIndexPath:(id)arg1;
- (long long)numberOfItems;
- (void)JDScrollNavScreenDicCancleScroll:(id)arg1;
- (void)JDScrollNavScreenWillScroll:(id)arg1;
- (void)registerNotificationForCancleSwipeRight2Parent;
- (void)registerNotificationForSwipeRight2Parent;
- (void)dealloc;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithParam:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

