//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SecKillBaseViewController.h"

#import "JDBaseToastViewDelegate-Protocol.h"
#import "NewRefreshTableHeaderViewDelegate-Protocol.h"
#import "SSSNavgationViewDelegate-Protocol.h"

@class JDActivityIndicatorView, JDBaseToastView, JDImageView, JDStoreNetwork, NSMutableArray, NSNumber, NSString, NewRefreshTableHeaderView, SSSBaseAdapter, SSSNewBrandKillBrandWarpperModel, SSSNewBrandNavigationView, SSSNewBrandSecKillModel, SSSNewBrandSecKillTableView, SSSNewBrandTimerView, SSSpikeGoodsCouponModel, SecKillObserverModel, SecKillRequestManager, UIButton, UILabel, UIView;

@interface SSSNewBrandSeckillViewController : SecKillBaseViewController <SSSNavgationViewDelegate, NewRefreshTableHeaderViewDelegate, JDBaseToastViewDelegate>
{
    NewRefreshTableHeaderView *_freshHeaderView;
    _Bool _isScale;
    _Bool _isPullRefresh;
    _Bool _isFirstAppear;
    _Bool _isBackToFront;
    _Bool _toastViewNeedDelayShow;
    SecKillRequestManager *_requestManager;
    SSSNewBrandSecKillModel *_brandModel;
    SSSNewBrandKillBrandWarpperModel *_warpperModel;
    long long _brandMiddleFromType;
    JDActivityIndicatorView *_activityIndicatorView;
    CDUnknownBlockType _couponViewDidClick;
    SSSpikeGoodsCouponModel *_couponModels;
    JDStoreNetwork *_couponRequest;
    SSSNewBrandSecKillTableView *_tableView;
    SSSBaseAdapter *_adapter;
    long long _currentCouponPos;
    NSString *_innerLink;
    NSNumber *_brandId;
    CDUnknownBlockType _finishHandler;
    NSMutableArray *_arrayIdentifier;
    SSSNewBrandNavigationView *_navView;
    UIButton *_btnBack;
    UIButton *_btnBackOnMask;
    UIButton *_btnRightBar;
    UIButton *_btnShare;
    UILabel *_lblTitle;
    JDImageView *_ivLine;
    JDImageView *_ivIcon;
    SecKillObserverModel *_observerModel;
    double _currentInterval;
    SSSNewBrandTimerView *_remainingTimeView;
    NSString *_tabPosNum;
    NSString *_tabName;
    NSString *_tabCount;
    double _statusBarHeight;
    UIView *_loadMaskView;
    JDBaseToastView *_toastView;
}

@property(nonatomic) _Bool toastViewNeedDelayShow; // @synthesize toastViewNeedDelayShow=_toastViewNeedDelayShow;
@property(retain, nonatomic) JDBaseToastView *toastView; // @synthesize toastView=_toastView;
@property(retain, nonatomic) UIView *loadMaskView; // @synthesize loadMaskView=_loadMaskView;
@property(nonatomic) double statusBarHeight; // @synthesize statusBarHeight=_statusBarHeight;
@property(copy, nonatomic) NSString *tabCount; // @synthesize tabCount=_tabCount;
@property(copy, nonatomic) NSString *tabName; // @synthesize tabName=_tabName;
@property(copy, nonatomic) NSString *tabPosNum; // @synthesize tabPosNum=_tabPosNum;
@property(nonatomic) _Bool isBackToFront; // @synthesize isBackToFront=_isBackToFront;
@property(nonatomic) _Bool isFirstAppear; // @synthesize isFirstAppear=_isFirstAppear;
@property(nonatomic) _Bool isPullRefresh; // @synthesize isPullRefresh=_isPullRefresh;
@property(retain, nonatomic) SSSNewBrandTimerView *remainingTimeView; // @synthesize remainingTimeView=_remainingTimeView;
@property(nonatomic) double currentInterval; // @synthesize currentInterval=_currentInterval;
@property(retain, nonatomic) SecKillObserverModel *observerModel; // @synthesize observerModel=_observerModel;
@property(retain, nonatomic) JDImageView *ivIcon; // @synthesize ivIcon=_ivIcon;
@property(retain, nonatomic) JDImageView *ivLine; // @synthesize ivLine=_ivLine;
@property(nonatomic) _Bool isScale; // @synthesize isScale=_isScale;
@property(retain, nonatomic) UILabel *lblTitle; // @synthesize lblTitle=_lblTitle;
@property(retain, nonatomic) UIButton *btnShare; // @synthesize btnShare=_btnShare;
@property(retain, nonatomic) UIButton *btnRightBar; // @synthesize btnRightBar=_btnRightBar;
@property(retain, nonatomic) UIButton *btnBackOnMask; // @synthesize btnBackOnMask=_btnBackOnMask;
@property(retain, nonatomic) UIButton *btnBack; // @synthesize btnBack=_btnBack;
@property(retain, nonatomic) SSSNewBrandNavigationView *navView; // @synthesize navView=_navView;
@property(retain, nonatomic) NSMutableArray *arrayIdentifier; // @synthesize arrayIdentifier=_arrayIdentifier;
@property(copy, nonatomic) CDUnknownBlockType finishHandler; // @synthesize finishHandler=_finishHandler;
@property(retain, nonatomic) NSNumber *brandId; // @synthesize brandId=_brandId;
@property(copy, nonatomic) NSString *innerLink; // @synthesize innerLink=_innerLink;
@property(nonatomic) long long currentCouponPos; // @synthesize currentCouponPos=_currentCouponPos;
@property(retain, nonatomic) SSSBaseAdapter *adapter; // @synthesize adapter=_adapter;
@property(retain, nonatomic) SSSNewBrandSecKillTableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) JDStoreNetwork *couponRequest; // @synthesize couponRequest=_couponRequest;
@property(retain, nonatomic) SSSpikeGoodsCouponModel *couponModels; // @synthesize couponModels=_couponModels;
@property(copy, nonatomic) CDUnknownBlockType couponViewDidClick; // @synthesize couponViewDidClick=_couponViewDidClick;
@property(retain, nonatomic) JDActivityIndicatorView *activityIndicatorView; // @synthesize activityIndicatorView=_activityIndicatorView;
@property(nonatomic) long long brandMiddleFromType; // @synthesize brandMiddleFromType=_brandMiddleFromType;
@property(retain, nonatomic) SSSNewBrandKillBrandWarpperModel *warpperModel; // @synthesize warpperModel=_warpperModel;
@property(retain, nonatomic) SSSNewBrandSecKillModel *brandModel; // @synthesize brandModel=_brandModel;
@property(retain, nonatomic) SecKillRequestManager *requestManager; // @synthesize requestManager=_requestManager;
- (void).cxx_destruct;
- (void)dealloc;
- (void)didFinishInToastView:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)navgationViewIsShow:(_Bool)arg1 scrollView:(id)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)setImageWhite;
- (void)setImageBlack;
- (void)setBackButtonImage;
- (void)refreshCouponView:(id)arg1;
- (void)handlerWithError;
- (void)share;
- (void)goToRemindView;
- (void)backClicked;
- (void)refreshData;
- (void)addRefreshHeadView:(id)arg1;
- (void)timerFired;
- (void)stopTimer;
- (void)startTimer;
- (void)notiNewBrandSeckillVC;
- (void)requestListData:(_Bool)arg1;
- (void)loadDefaultData;
- (void)createBaseView;
- (void)reconnect;
- (void)applicationWillResignActive;
- (void)applicationDidBecomeActive;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)getTabCount;
- (id)getBrandId;
- (id)getTabName;
- (id)getTabPos;
- (id)initWithBrandId:(id)arg1 type:(long long)arg2;
- (id)initWithBrandId:(id)arg1;
- (id)initWithParam:(id)arg1;
- (void)receiveCouponResult:(id)arg1;
- (void)receiveCoupon:(id)arg1;
- (void)startReceiveCoupon:(id)arg1;
- (void)asignValueOfCouponViewClick;
- (void)startRequestCoupons;
- (void)requestListDataWithBrandId:(id)arg1 innerLink:(id)arg2 finishHandler:(CDUnknownBlockType)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

