//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SecKillBaseCell.h"

@class UIImageView, UILabel;

@interface SSSSingleKillHistoryHeadCell : SecKillBaseCell
{
    UILabel *_nameLabel;
    UIImageView *_leftIv;
    UIImageView *_ivLine;
}

@property(retain, nonatomic) UIImageView *ivLine; // @synthesize ivLine=_ivLine;
@property(retain, nonatomic) UIImageView *leftIv; // @synthesize leftIv=_leftIv;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
- (void).cxx_destruct;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

