//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UIImageView, UILabel, UIView;

@interface TTTAWAKeyAddCartCell : UITableViewCell
{
    UIImageView *_statusIcon;
    UILabel *_nameLabel;
    UILabel *_priceLabel;
    UIView *_bottomLine;
    long long _AKAccessoryType;
}

@property(nonatomic) long long AKAccessoryType; // @synthesize AKAccessoryType=_AKAccessoryType;
@property(retain, nonatomic) UIView *bottomLine; // @synthesize bottomLine=_bottomLine;
@property(retain, nonatomic) UILabel *priceLabel; // @synthesize priceLabel=_priceLabel;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) UIImageView *statusIcon; // @synthesize statusIcon=_statusIcon;
- (void).cxx_destruct;
- (struct CGRect)bottomLineFrame;
- (struct CGRect)priceLabelFrame;
- (struct CGRect)nameLabelFrame;
- (struct CGRect)statusIconFrame;
- (void)showBottomLine;
- (void)hideLastBottomLine;
- (void)bindDataWithModel:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

