//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TTTElementBaseView.h"

@class JDImageView, UILabel;

@interface TTTElementTextView : TTTElementBaseView
{
    UILabel *_textLabel;
    JDImageView *_imageView;
}

@property(retain, nonatomic) JDImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) UILabel *textLabel; // @synthesize textLabel=_textLabel;
- (void).cxx_destruct;
- (struct CGRect)textLabelFrameWithText:(id)arg1 font:(id)arg2 numLine:(long long)arg3;
- (id)p_attributedText:(id)arg1 attachment:(id)arg2 font:(id)arg3 textColor:(id)arg4 textCenter:(_Bool)arg5;
- (void)p_hideAllLabel;
- (void)p_showOtherText:(id)arg1 numLine:(long long)arg2 font:(id)arg3 textColor:(id)arg4 textCenter:(_Bool)arg5;
- (void)p_showGlobalBuy:(id)arg1 numLine:(long long)arg2 font:(id)arg3 textColor:(id)arg4 textCenter:(_Bool)arg5;
- (void)setFrame:(struct CGRect)arg1 data:(id)arg2 value:(id)arg3 ratio:(double)arg4;
- (id)initWithFrame:(struct CGRect)arg1;

@end

