//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TTTElementBaseView.h"

@class UILabel;

@interface TTTElementProPackTaxUnit : TTTElementBaseView
{
    UILabel *_packTaxlabel;
}

@property(retain, nonatomic) UILabel *packTaxlabel; // @synthesize packTaxlabel=_packTaxlabel;
- (void).cxx_destruct;
- (void)setFrame:(struct CGRect)arg1 data:(id)arg2 value:(id)arg3;
- (id)initWithFrame:(struct CGRect)arg1;

@end

