//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TTTBaseModel.h"

@class NSArray, NSNumber, NSString;

@interface TTTHotPicPriceLabelModel : TTTBaseModel
{
    _Bool _isShow;
    NSString *_show;
    NSString *_bgStyle;
    NSString *_bgColor;
    NSNumber *_fontSize;
    NSString *_fontColor;
    NSString *_shapeStyle;
    NSArray *_lblList;
}

+ (id)objectClassInArray;
@property(nonatomic) _Bool isShow; // @synthesize isShow=_isShow;
@property(retain, nonatomic) NSArray *lblList; // @synthesize lblList=_lblList;
@property(copy, nonatomic) NSString *shapeStyle; // @synthesize shapeStyle=_shapeStyle;
@property(copy, nonatomic) NSString *fontColor; // @synthesize fontColor=_fontColor;
@property(copy, nonatomic) NSNumber *fontSize; // @synthesize fontSize=_fontSize;
@property(copy, nonatomic) NSString *bgColor; // @synthesize bgColor=_bgColor;
@property(copy, nonatomic) NSString *bgStyle; // @synthesize bgStyle=_bgStyle;
@property(copy, nonatomic) NSString *show; // @synthesize show=_show;
- (void).cxx_destruct;

@end

