//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TTTBaseView.h"

@class NSArray, TTTTotalModel, UIScrollView, UIView;

@interface TTTHeadTabImmersiveView : TTTBaseView
{
    double _line2TextPadding;
    _Bool _isAnimating;
    _Bool _isOpti;
    TTTTotalModel *_totalModel;
    UIView *_backLineView;
    UIScrollView *_scrollView;
    NSArray *_buttons;
    unsigned long long _currentIndex;
}

@property(nonatomic) _Bool isOpti; // @synthesize isOpti=_isOpti;
@property(nonatomic) _Bool isAnimating; // @synthesize isAnimating=_isAnimating;
@property(nonatomic) unsigned long long currentIndex; // @synthesize currentIndex=_currentIndex;
@property(retain, nonatomic) NSArray *buttons; // @synthesize buttons=_buttons;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(retain, nonatomic) UIView *backLineView; // @synthesize backLineView=_backLineView;
@property(retain, nonatomic) TTTTotalModel *totalModel; // @synthesize totalModel=_totalModel;
- (void).cxx_destruct;
- (void)changeTabToImmersive:(double)arg1;
- (void)toCenterButton:(double)arg1 animated:(_Bool)arg2;
- (void)selectButton:(unsigned long long)arg1;
- (void)initData:(id)arg1;
- (void)goToOneTab:(unsigned long long)arg1;
- (void)buttonsPressed:(id)arg1;
- (void)updateOffset:(struct CGPoint)arg1 isEndScolled:(_Bool)arg2;
- (void)createScrollView:(id)arg1;
- (double)initTabButtonFrame:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 data:(id)arg2;

@end

