//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TTTBaseView.h"

#import "TTTBaseViewProtocol-Protocol.h"

@class JDImageView, NSString, TTTFloorModel, TTTMatchBuyAuthorAndPageNumView, UILabel, UIView;

@interface TTTMatchBuyView : TTTBaseView <TTTBaseViewProtocol>
{
    JDImageView *_mainPicImageView;
    UILabel *_titleLabel;
    UILabel *_subTitleLabel;
    TTTMatchBuyAuthorAndPageNumView *_authorAndPageNumView;
    UIView *_seperatorLine;
    TTTFloorModel *_floorModel;
}

@property(retain, nonatomic) TTTFloorModel *floorModel; // @synthesize floorModel=_floorModel;
@property(retain, nonatomic) UIView *seperatorLine; // @synthesize seperatorLine=_seperatorLine;
@property(retain, nonatomic) TTTMatchBuyAuthorAndPageNumView *authorAndPageNumView; // @synthesize authorAndPageNumView=_authorAndPageNumView;
@property(retain, nonatomic) UILabel *subTitleLabel; // @synthesize subTitleLabel=_subTitleLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) JDImageView *mainPicImageView; // @synthesize mainPicImageView=_mainPicImageView;
- (void).cxx_destruct;
- (struct CGRect)convertPointCoordinateWithLabelModel:(id)arg1;
- (void)configLabels;
- (void)configOptionalViews;
- (void)configFixedViews;
- (void)bindDataWithViewModel:(id)arg1;
- (void)viewTaped:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

