//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class JDImageView, UIImageView, UILabel;

@interface TTTMedalHeadView : UIView
{
    CDUnknownBlockType _tapBlock;
    JDImageView *_iconView;
    UILabel *_nameLabel;
    UILabel *_descLabel;
    UILabel *_rightLabel;
    UIImageView *_rightArrow;
}

@property(retain, nonatomic) UIImageView *rightArrow; // @synthesize rightArrow=_rightArrow;
@property(retain, nonatomic) UILabel *rightLabel; // @synthesize rightLabel=_rightLabel;
@property(retain, nonatomic) UILabel *descLabel; // @synthesize descLabel=_descLabel;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) JDImageView *iconView; // @synthesize iconView=_iconView;
@property(copy, nonatomic) CDUnknownBlockType tapBlock; // @synthesize tapBlock=_tapBlock;
- (void).cxx_destruct;
- (struct CGRect)arrowFrame;
- (struct CGRect)rightFrame;
- (struct CGRect)descFrame;
- (struct CGRect)nameCenterFrame;
- (struct CGRect)nameFrame;
- (struct CGRect)iconFrame;
- (void)bindDataWithViewModel:(id)arg1;
- (void)taped;
- (id)initWithFrame:(struct CGRect)arg1;

@end

