//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TTTBaseModel.h"

@class NSString;

@interface TTTRankTypeAttrModel : TTTBaseModel
{
    NSString *_alignStyle;
    NSString *_titleColor;
}

@property(copy, nonatomic) NSString *titleColor; // @synthesize titleColor=_titleColor;
@property(copy, nonatomic) NSString *alignStyle; // @synthesize alignStyle=_alignStyle;
- (void).cxx_destruct;

@end

