//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIImageView, UILabel;

@interface TTTShopCouponCouponView : UIView
{
    UIImageView *_backView;
    UILabel *_moneyLabel;
}

@property(retain, nonatomic) UILabel *moneyLabel; // @synthesize moneyLabel=_moneyLabel;
@property(retain, nonatomic) UIImageView *backView; // @synthesize backView=_backView;
- (void).cxx_destruct;
- (void)p_setCouponViewWithMoney:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

