//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TTTBaseView.h"

#import "TTTBaseViewProtocol-Protocol.h"

@class NSString, TTTBaiTiaoPriceView, TTTDiscountView, TTTPlusPriceView, TTTWareImageView, TTTWareModel, TTTWaresBeltView, TTTWaresContrastPriceView, TTTWaresSimilarView, UIButton, UILabel;
@protocol TTTWaresListDelegate;

@interface TTTWaresListView : TTTBaseView <TTTBaseViewProtocol>
{
    id <TTTWaresListDelegate> _delegate;
    long long _sloganTextType;
    TTTWareImageView *_imageView;
    TTTWaresBeltView *_beltView;
    UILabel *_nameLabel;
    UILabel *_sloganLabel;
    TTTBaiTiaoPriceView *_baiTiaoPriceLabel;
    TTTWaresContrastPriceView *_priceLabel;
    UIButton *_cartButton;
    TTTDiscountView *_disView;
    UILabel *_commentLabel;
    TTTWareModel *_ware;
    double _priceLabelWidth;
    TTTPlusPriceView *_plusPriceLabel;
    TTTWaresSimilarView *_similarView;
}

@property(retain, nonatomic) TTTWaresSimilarView *similarView; // @synthesize similarView=_similarView;
@property(retain, nonatomic) TTTPlusPriceView *plusPriceLabel; // @synthesize plusPriceLabel=_plusPriceLabel;
@property(nonatomic) double priceLabelWidth; // @synthesize priceLabelWidth=_priceLabelWidth;
@property(nonatomic) __weak TTTWareModel *ware; // @synthesize ware=_ware;
@property(retain, nonatomic) UILabel *commentLabel; // @synthesize commentLabel=_commentLabel;
@property(retain, nonatomic) TTTDiscountView *disView; // @synthesize disView=_disView;
@property(retain, nonatomic) UIButton *cartButton; // @synthesize cartButton=_cartButton;
@property(retain, nonatomic) TTTWaresContrastPriceView *priceLabel; // @synthesize priceLabel=_priceLabel;
@property(retain, nonatomic) TTTBaiTiaoPriceView *baiTiaoPriceLabel; // @synthesize baiTiaoPriceLabel=_baiTiaoPriceLabel;
@property(retain, nonatomic) UILabel *sloganLabel; // @synthesize sloganLabel=_sloganLabel;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) TTTWaresBeltView *beltView; // @synthesize beltView=_beltView;
@property(retain, nonatomic) TTTWareImageView *imageView; // @synthesize imageView=_imageView;
@property(nonatomic) long long sloganTextType; // @synthesize sloganTextType=_sloganTextType;
@property(nonatomic) __weak id <TTTWaresListDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)p_wareSimilarShow;
- (void)p_wareBeltShow;
- (void)updateComment;
- (void)updateDisView;
- (void)wareSellStatus:(id)arg1;
- (void)p_BaiTiaoPrice;
- (void)p_configColor;
- (void)bindDataWithViewModel:(id)arg1;
- (void)setDefaultSpace;
- (void)wareViewClick;
- (void)shopCart:(id)arg1;
- (id)initWithPageWareFrame:(struct CGRect)arg1;
- (struct CGRect)discountViewFrame;
- (struct CGRect)commentLabelFrame;
- (struct CGRect)plusPriceViewWithCommentFrame;
- (struct CGRect)plusPriceViewNormalFrame;
- (struct CGRect)priceViewWithCommentFrame;
- (struct CGRect)priceViewNormalFrame;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

