//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TTTBaseView.h"

#import "JDiCarouselDataSource-Protocol.h"
#import "JDiCarouselDelegate-Protocol.h"
#import "TTTBaseViewProtocol-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"

@class JDiCarousel, NSString, NSTimer, TTTFloorModel;

@interface TTTWaresCarouselSmallView : TTTBaseView <JDiCarouselDelegate, JDiCarouselDataSource, UIGestureRecognizerDelegate, TTTBaseViewProtocol>
{
    struct CGPoint beginPoint;
    TTTFloorModel *_floorModel;
    JDiCarousel *_carouselView;
    NSTimer *_timer;
    long long _targetIndex;
}

@property(nonatomic) long long targetIndex; // @synthesize targetIndex=_targetIndex;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(retain, nonatomic) JDiCarousel *carouselView; // @synthesize carouselView=_carouselView;
@property(nonatomic) __weak TTTFloorModel *floorModel; // @synthesize floorModel=_floorModel;
- (void).cxx_destruct;
- (struct CGRect)itemViewFrame;
- (void)JDiCarouselDidEndScrollingAnimation:(id)arg1;
- (double)JDiCarousel:(id)arg1 valueForOption:(long long)arg2 withDefault:(double)arg3;
- (void)JDiCarousel:(id)arg1 didSelectItemAtIndex:(long long)arg2;
- (void)JDiCarouselWillBeginScrollingAnimation:(id)arg1;
- (id)JDiCarousel:(id)arg1 viewForItemAtIndex:(long long)arg2 reusingView:(id)arg3;
- (long long)JDiCarouselNumberOfItemsInCarousel:(id)arg1;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (void)dealloc;
- (void)willMoveToSuperview:(id)arg1;
- (void)viewDidEndDisplaying;
- (void)viewWillDisplay;
- (void)resetTimer;
- (void)paned:(id)arg1;
- (void)fadeOutView:(id)arg1 WithDuration:(double)arg2;
- (void)fadeInView:(id)arg1 WithDuration:(double)arg2;
- (void)fadeFromCurrentView:(id)arg1 toNextView:(id)arg2 WithDuration:(double)arg3;
- (void)fadeFromCurrentView:(id)arg1 toNextView:(id)arg2;
- (void)autoScollToNextView;
- (void)updateBackcolor;
- (void)bindDataWithViewModel:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

