//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIColor.h>

@interface UIColor (COCheckoutColorParser)
+ (id)checkout_colorWithHexStr:(id)arg1 checkout_defaultColorValue:(id)arg2;
+ (id)checkout_colorWithHexStr:(id)arg1 checkout_defaultColor:(id)arg2;
+ (id)checkout_colorWithHexStr:(id)arg1 checkout_defaultColorStr:(id)arg2;
@end

