//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIFont.h>

@interface UIFont (ZDMFont)
+ (id)ZDM_GetJDLightFontWithSize:(double)arg1;
+ (id)ZDM_GetJDBoldFontWithSize:(double)arg1;
+ (id)ZDM_GetJDRegularFontWithSize:(double)arg1;
@end

