//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface UIView (ZDM)
+ (id)maskViewWithFrame:(struct CGRect)arg1 alpha:(double)arg2;
- (void)addTapEventUsingBlock:(CDUnknownBlockType)arg1;
- (void)setHandleTarget:(id)arg1;
- (id)handleTarget;
- (void)addCornalBorderWithCornals:(unsigned long long)arg1 color:(id)arg2 width:(double)arg3;
- (void)addCornalBorderViewWithRect:(struct CGRect)arg1 width:(double)arg2 color:(id)arg3;
- (void)changeTocCircleView;
- (void)addRoundCornal:(double)arg1;
- (void)setY:(double)arg1;
- (void)setX:(double)arg1;
- (double)x;
- (double)y;
- (double)maxY;
- (double)maxX;
- (void)zdm_flip;
- (void)zdm_inflate;
@end

