//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "VBListBaseContentModel.h"

@class NSString;

@interface VBListImageContentModel : VBListBaseContentModel
{
    NSString *_aspect;
    long long _articleId;
    NSString *_indexImage;
}

+ (id)replacedKeyFromPropertyName;
@property(copy, nonatomic) NSString *indexImage; // @synthesize indexImage=_indexImage;
@property(nonatomic) long long articleId; // @synthesize articleId=_articleId;
@property(copy, nonatomic) NSString *aspect; // @synthesize aspect=_aspect;
- (void).cxx_destruct;
- (double)cellHeight;
- (void)keyValuesDidFinishConvertingToObject;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end

