//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JDWebViewController.h"

#import "VBListViewControllerProtocol-Protocol.h"

@class JDTokenDAO, NSString, UIScrollView;

@interface VBWebViewController : JDWebViewController <VBListViewControllerProtocol>
{
    JDTokenDAO *_tokenDAO;
    NSString *_URLString;
}

@property(copy, nonatomic) NSString *URLString; // @synthesize URLString=_URLString;
@property(retain, nonatomic) JDTokenDAO *tokenDAO; // @synthesize tokenDAO=_tokenDAO;
- (void).cxx_destruct;
@property(readonly, nonatomic) __weak UIScrollView *vb_scrollView;
- (void)viewDidLoad;
- (id)initWithURL:(id)arg1 usingUIWebView:(_Bool)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

