//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class JDIcon, UIImageView, UILabel, UIView, WSPKButton;
@protocol WanderShopActivePKCellDelegate;

@interface WanderShopActivePKCell : UITableViewCell
{
    UILabel *_nameLabel;
    JDIcon *_plusIcon;
    UIImageView *_iconView;
    UIView *_lineView;
    UILabel *_contentLab;
    UILabel *_praiseNum;
    WSPKButton *_praiseBtn;
    UIImageView *_textView;
    id <WanderShopActivePKCellDelegate> _delegate;
}

@property(nonatomic) __weak id <WanderShopActivePKCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UIImageView *textView; // @synthesize textView=_textView;
@property(retain, nonatomic) WSPKButton *praiseBtn; // @synthesize praiseBtn=_praiseBtn;
- (void).cxx_destruct;
- (void)plusIconDidClicked:(id)arg1;
- (void)hitPraised;
- (void)setCellFrame:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (id)init;

@end

