//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JDViewController.h"

#import "FunctionButtonsViewDelegate-Protocol.h"
#import "GiftRequestManagerDelegate-Protocol.h"
#import "JDBaseToastRealnameVerifyViewDelegate-Protocol.h"
#import "PDCommentFloorViewModelDelegate-Protocol.h"
#import "PDMainViewControllerProtocol-Protocol.h"
#import "PDNavigationBarViewDelegate-Protocol.h"
#import "PDStoreServiceViewModelDelegate-Protocol.h"
#import "TTTAttributedLabelDelegate-Protocol.h"
#import "UIActionSheetDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"
#import "UIViewControllerPreviewingDelegate-Protocol.h"
#import "WareMenuViewDelegate-Protocol.h"
#import "WarePageViewDelegate-Protocol.h"

@class JDImageView, JDSXRecommendView, NSMutableArray, NSString, NewProductModel, PDAddCartRecommendPopView, PDBPSkyEyeView, PDBarrageView, PDBusinessManager, PDMainPageView, PDMenuManager, PDMoreItemModel, PDNavigationBarView, PDSkyEyeView, UILabel, UIView, WareBBottomButtonsView, WareBSKUDetailView, WareCommentDetailListViewController, WareIntroDetailView, WareIntroViewController, WareMenuView, WarePageView;

@interface WareInfoBViewController : JDViewController <WareMenuViewDelegate, PDNavigationBarViewDelegate, UIViewControllerPreviewingDelegate, TTTAttributedLabelDelegate, UIScrollViewDelegate, GiftRequestManagerDelegate, WarePageViewDelegate, JDBaseToastRealnameVerifyViewDelegate, PDStoreServiceViewModelDelegate, PDCommentFloorViewModelDelegate, FunctionButtonsViewDelegate, PDMainViewControllerProtocol, UIActionSheetDelegate>
{
    _Bool _isDetailViewAddedToSuperView;
    NewProductModel *_wareModel;
    PDBusinessManager *_mainBusinessManager;
    WarePageView *_pageView;
    WareIntroViewController *_wareIntroController;
    WareCommentDetailListViewController *_wareCommentDetailListController;
    JDSXRecommendView *_recommendView;
    unsigned long long _needPopAgainType;
    WareIntroDetailView *_detailView;
    WareBSKUDetailView *_skuDetailView;
    WareBBottomButtonsView *_wareButtons;
    UIView *_mainSkuView;
    PDMainPageView *_contentView;
    PDAddCartRecommendPopView *_recommendPopView;
    PDBarrageView *_barrageview;
    PDMenuManager *_menuManager;
    PDSkyEyeView *_skyEyeView;
    PDBPSkyEyeView *_bpSkyEyeView;
    UIView *_animateView;
}

@property(retain, nonatomic) UIView *animateView; // @synthesize animateView=_animateView;
@property(retain, nonatomic) PDBPSkyEyeView *bpSkyEyeView; // @synthesize bpSkyEyeView=_bpSkyEyeView;
@property(retain, nonatomic) PDSkyEyeView *skyEyeView; // @synthesize skyEyeView=_skyEyeView;
@property(retain, nonatomic) PDMenuManager *menuManager; // @synthesize menuManager=_menuManager;
@property(retain, nonatomic) PDBarrageView *barrageview; // @synthesize barrageview=_barrageview;
@property(retain, nonatomic) PDAddCartRecommendPopView *recommendPopView; // @synthesize recommendPopView=_recommendPopView;
@property(retain, nonatomic) PDMainPageView *contentView; // @synthesize contentView=_contentView;
@property(retain, nonatomic) UIView *mainSkuView; // @synthesize mainSkuView=_mainSkuView;
@property(retain, nonatomic) WareBBottomButtonsView *wareButtons; // @synthesize wareButtons=_wareButtons;
@property(retain, nonatomic) WareBSKUDetailView *skuDetailView; // @synthesize skuDetailView=_skuDetailView;
@property(nonatomic) _Bool isDetailViewAddedToSuperView; // @synthesize isDetailViewAddedToSuperView=_isDetailViewAddedToSuperView;
@property(retain, nonatomic) WareIntroDetailView *detailView; // @synthesize detailView=_detailView;
@property(nonatomic) unsigned long long needPopAgainType; // @synthesize needPopAgainType=_needPopAgainType;
@property(retain, nonatomic) JDSXRecommendView *recommendView; // @synthesize recommendView=_recommendView;
@property(retain, nonatomic) WareCommentDetailListViewController *wareCommentDetailListController; // @synthesize wareCommentDetailListController=_wareCommentDetailListController;
@property(retain, nonatomic) WareIntroViewController *wareIntroController; // @synthesize wareIntroController=_wareIntroController;
@property(retain, nonatomic) WarePageView *pageView; // @synthesize pageView=_pageView;
@property(retain, nonatomic) PDBusinessManager *mainBusinessManager; // @synthesize mainBusinessManager=_mainBusinessManager;
@property(retain, nonatomic) NewProductModel *wareModel; // @synthesize wareModel=_wareModel;
- (void).cxx_destruct;
- (void)showSkyEyeViewMTA;
- (id)getFirstFloorViewModelByClassName:(id)arg1;
- (void)updateShopcart:(id)arg1 animated:(_Bool)arg2;
- (void)showNeedRefreshData:(_Bool)arg1;
- (void)showPlusFeeTipsView;
- (void)setHeaderViewWithModel:(id)arg1;
- (void)renderFloor:(id)arg1 floorVMClassName:(id)arg2;
- (void)largePromotionSkinsChange;
- (void)changeSkin;
- (void)platformChangeSkin;
- (void)changeAppTheMeSkin;
- (void)changeWareSkin;
- (void)clearLocParams;
- (id)getLocParamString;
- (id)getLocParams;
- (void)locShopSelected:(id)arg1;
- (void)updateFsPriceFloor:(id)arg1;
- (void)shoeSizeHelp_showSkuDetailView:(id)arg1;
- (void)reloadSizeHelperView:(id)arg1;
- (void)tuwenInvoke:(id)arg1;
- (void)changeMainImageUrlKey:(id)arg1;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)applicationBackgroud:(id)arg1;
- (void)scrollToTuwenDetailView:(id)arg1;
- (void)scrollToProductInfo_MAnimate;
- (void)scrollToProductInfo_M;
- (void)scrollToProductInfo_Local:(id)arg1;
- (void)returnTop:(id)arg1;
- (void)setCurrentPageTo:(long long)arg1 animate:(_Bool)arg2;
- (void)addO2OCart:(_Bool)arg1;
- (void)addCardListCart:(_Bool)arg1;
- (void)addDrugCart:(_Bool)arg1;
- (void)addWareToShopCart:(_Bool)arg1;
- (void)tappedButton:(id)arg1 withViewTag:(long long)arg2 withButtonTag:(long long)arg3;
- (void)reloadContentView;
- (void)stopAllTimer;
- (void)updateYuyueTime:(id)arg1 interval:(double)arg2;
- (void)setupDetailUI;
- (void)refreshRecommendViewData;
- (void)configRecommendView;
- (void)configMenuManagerView;
- (void)setupBasicUI;
- (void)showSkyEyeView;
- (void)scrollToCommentSemanticTagDetailListViewController:(id)arg1;
- (void)scrollToWareCommentDetailListViewController:(id)arg1;
- (void)updateBadge:(id)arg1;
- (void)refreshMyCarsInfo:(id)arg1;
- (void)refreshO2OCarInfo:(id)arg1;
- (void)addGiftToCartSuccess:(_Bool)arg1;
- (void)actionSheet:(id)arg1 didDismissWithButtonIndex:(long long)arg2;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)showActionSheetForService;
- (void)realGotoCustomerServicePage;
- (void)gotoCustomerServicePage;
- (void)gotoServiceViewWithIndex:(long long)arg1;
- (void)showWareCommentAblum;
- (void)responseWareDetailCommentData:(id)arg1;
- (void)refreshBagNum;
- (void)responseFreeFreightInfo:(id)arg1;
- (void)responseBarrageInfo:(id)arg1;
- (_Bool)handleJumpService;
- (void)net_later_handler;
- (void)net_first_handler;
- (void)responseProductMainInfo;
- (void)getMainProuductInfo;
- (void)changeWare:(id)arg1;
- (void)changeAddToCartButtonState:(id)arg1;
- (void)setSkuDetailView;
- (void)setSkuDetailViewBottomButton;
- (void)similarButtonTapped;
- (void)setFavoriteButtonState:(_Bool)arg1 animate:(_Bool)arg2;
- (void)addToCartWithAnimation:(long long)arg1;
- (void)favoriteButtonModelAction:(id)arg1;
- (void)showSkuDetailView:(id)arg1;
- (void)popViewController:(id)arg1;
- (void)pushViewController:(id)arg1;
- (void)closePopupView:(id)arg1;
- (void)stopCommentVideoPlay;
- (id)getPageIndexMenuItemInfo;
- (void)pageviewWillBeginDragging:(id)arg1;
- (void)pageviewDidEndScrolling:(id)arg1;
- (void)pageViewScrollViewRealTimeOffSet:(id)arg1;
- (void)pageViewDidChanged:(long long)arg1 menuType:(long long)arg2;
- (void)JDScrollNavScreenDidScroll:(id)arg1;
- (void)JDScrollNavScreenWillScroll:(id)arg1;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (id)vcCrashAppendInfo;
- (void)backButtonClicked;
- (void)statusBarFrameChanged:(id)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)initViewsWithIntialParam;
- (id)initWithModel:(id)arg1;
- (void)dealloc;
@property(retain, nonatomic) PDNavigationBarView *navigationBarView;
@property(retain, nonatomic) PDMoreItemModel *feedbackModel;
@property(retain, nonatomic) NSMutableArray *moreArray; // @dynamic moreArray;
@property(retain, nonatomic) UILabel *messageNumberLabel;
@property(retain, nonatomic) JDImageView *redDotImageView; // @dynamic redDotImageView;
@property(retain, nonatomic) WareMenuView *menuView; // @dynamic menuView;
@property(retain, nonatomic) UILabel *titleLabel; // @dynamic titleLabel;
@property(retain, nonatomic) UILabel *tuwenLabel; // @dynamic tuwenLabel;
- (id)doorNumSystemFontOfSize:(double)arg1;
- (void)getRedDotCompleted:(id)arg1;
- (void)setRedDotHidden:(_Bool)arg1;
- (void)menuViewDidChanged:(long long)arg1 menuButtonType:(long long)arg2;
- (void)gotoFeedBack;
- (void)gotoHistory;
- (void)goToMyFavorite;
- (void)goToMessageCenter;
- (void)moreAction:(id)arg1;
- (void)pdNavigationBarViewButtonTap:(long long)arg1 sender:(id)arg2;
- (void)shareAction:(id)arg1;
- (void)toastView:(id)arg1 didSelectMenuRow:(long long)arg2;
- (long long)toastView:(id)arg1 maxBadgeNumberAtRow:(long long)arg2;
- (long long)toastView:(id)arg1 badgeNumberAtRow:(long long)arg2;
- (_Bool)toastView:(id)arg1 hasRedDotAtRow:(long long)arg2;
- (id)toastView:(id)arg1 titleForMenuRow:(long long)arg2;
- (id)toastView:(id)arg1 imageForMenuRow:(long long)arg2;
- (long long)numberOfRowsInMenuToastView:(id)arg1;
- (void)configShareButton;
- (void)resetNavigationBarSkin;
- (void)updateNavigationBarTheme:(id)arg1 backgroundImgUrl:(id)arg2;
- (void)navigationBarChangeSkin;
- (void)navigationBarPlatformChangeSkin;
- (void)navigationBarAppThemeChangeSkin;
- (void)refreshNavigationBarTitleView;
- (void)configToastView;
- (void)configNavigationBarView;
- (void)commonPageTrackMTA:(id)arg1;
- (void)commonClickEventMTA:(id)arg1;
- (void)removeNotificationsInDeallocFunction;
- (void)addNotificationsInViewDidLoadFunction;
- (void)removeNotificationsInViewWillDisappearFunction;
- (void)addNotificationsInViewWillAppearFunction;
- (id)previewActionItems;
- (void)previewingContext:(id)arg1 commitViewController:(id)arg2;
- (id)previewingContext:(id)arg1 viewControllerForLocation:(struct CGPoint)arg2;
- (void)traitCollectionDidChange:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

