//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WareCommentBaseCell.h"

#import "WareCommentVideoToastViewDelegate-Protocol.h"

@class JDButton, JDIcon, JDIconGifLabel, JDIconLabel, JDImageView, NSArray, NSMutableArray, NSString, UIButton, UIImageView, UILabel, UITapGestureRecognizer, UIView, WareCommentDetailCellView, WareCommentDetailModel, WareCommentFoldView, WareCommentPlayerView, WareCommentRateView, WareCommentVideoToastView;
@protocol WareCommentBaseDelegate;

@interface WareCommentDetailCell : WareCommentBaseCell <WareCommentVideoToastViewDelegate>
{
    struct CGRect _playViewRect;
    struct CGRect _afterCommentPlayViewRect;
    struct CGRect _selfRect;
    UILabel *_userInfoLabel;
    UILabel *_postDate;
    WareCommentRateView *_rateView;
    UILabel *_commentDetail;
    NSArray *_images;
    UIButton *_commentButton;
    UILabel *_attributeLabel;
    UILabel *_viewCountLabel;
    JDIcon *_icon;
    UILabel *_afterTimeLabel;
    UILabel *_afterContentLabel;
    UIView *_commentImageView;
    UIView *_afterCommentTimeView;
    UIView *_afterCommentImageView;
    UIView *_headView;
    JDButton *_backgroundButton;
    UIView *_mainView;
    UILabel *_addLabel;
    UILabel *_replyLabel;
    NSString *_mediaId;
    NSString *_afterMediaId;
    long long _selectedIndex;
    double _beginTime;
    UIImageView *_userLeveleIcon;
    JDImageView *_essenceImageView;
    JDIconLabel *_plusIcon;
    JDImageView *_userHeaderView;
    JDIconGifLabel *_plusGifIcon;
    NSMutableArray *_commentImageViewArray;
    NSMutableArray *_afterImageViewArray;
    WareCommentPlayerView *_selectedPlayer;
    UITapGestureRecognizer *_tapGes;
    WareCommentFoldView *_commentFoldView;
    WareCommentFoldView *_afterCommentFoldView;
    WareCommentFoldView *_replyFoldView;
    WareCommentDetailCellView *_replyLine;
    _Bool _hasPlayer;
    WareCommentDetailModel *_wareModel;
    id <WareCommentBaseDelegate> _delegate;
    UIButton *_usefulButton;
    WareCommentPlayerView *_playView;
    WareCommentPlayerView *_afterCommentPlayView;
    WareCommentVideoToastView *_videoTostView;
}

@property(retain, nonatomic) WareCommentVideoToastView *videoTostView; // @synthesize videoTostView=_videoTostView;
@property(retain, nonatomic) WareCommentPlayerView *afterCommentPlayView; // @synthesize afterCommentPlayView=_afterCommentPlayView;
@property(retain, nonatomic) WareCommentPlayerView *playView; // @synthesize playView=_playView;
@property(retain, nonatomic) UIButton *usefulButton; // @synthesize usefulButton=_usefulButton;
@property(nonatomic) __weak id <WareCommentBaseDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool hasPlayer; // @synthesize hasPlayer=_hasPlayer;
@property(retain, nonatomic) WareCommentDetailModel *wareModel; // @synthesize wareModel=_wareModel;
- (void).cxx_destruct;
- (id)getDisplayImageViewWithIndex:(long long)arg1;
- (void)didTapCheckButtonVideoToastView:(_Bool)arg1;
- (void)didTapComitVideoToastView:(_Bool)arg1;
- (void)didTapCancelVideoToastView;
- (void)gotoBigImageView:(long long)arg1 player:(id)arg2;
- (void)checkNetwork:(long long)arg1 player:(id)arg2;
- (void)play:(id)arg1;
- (void)Releasevideo;
- (void)prepareForReuse;
- (void)stopPlayer;
- (_Bool)canPlayPlayer:(id)arg1;
- (_Bool)setPlayerPlay:(id)arg1 withRect:(struct CGRect)arg2;
- (void)playOrStopPlayer:(id)arg1 withOldRect:(struct CGRect)arg2;
- (_Bool)scrollInside:(id)arg1 withOldRect:(struct CGRect)arg2;
- (void)scrollExpoMaidian;
- (void)positionChange;
- (void)setPlayerPlay:(id)arg1 withOldRect:(struct CGRect)arg2 isPlay:(_Bool)arg3;
- (void)setPlayers;
- (void)refreshView:(id)arg1;
- (void)wordOpenBack:(_Bool)arg1;
- (void)expoSingleTime;
- (void)expoVisibelSingleTime;
- (void)setBeginTime;
- (void)scrollForSingTime;
- (void)layoutSubviews;
- (void)gotoPlusCenter;
- (void)reloadCell;
- (void)setButtonImage:(_Bool)arg1;
- (void)refreshReplyCount;
- (void)refreshUsefulButton;
- (void)refreshPraiseCount:(id)arg1;
- (void)setUsefulAnimate:(_Bool)arg1 type:(id)arg2;
- (id)getImageView:(id)arg1 withIndex:(int)arg2;
- (void)loadImageView:(id)arg1 withArray:(id)arg2 ResuArray:(id)arg3 show:(_Bool)arg4;
- (void)userfulComment;
- (void)replyComment;
- (void)replyFoldTap:(id)arg1;
- (void)afterFoldTap:(id)arg1;
- (void)foldTap:(id)arg1;
- (void)viewDidTaped:(id)arg1;
- (void)imageviewTap:(id)arg1;
- (void)moreAfterViewTap;
- (void)moreViewTap;
- (void)expoMarkingTag;
- (_Bool)setCurrentPlayer:(id)arg1;
- (void)expoMaidian;
- (_Bool)setPlayerRect:(_Bool)arg1;
- (void)setWithModel:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2 wareComment:(id)arg3;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

