//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ZDMFullscreenViewController.h"

#import "UIScrollViewDelegate-Protocol.h"
#import "ZDMPageViewControllerDelegate-Protocol.h"

@class JDImageView, NSDictionary, NSLayoutConstraint, NSString, UIImageView, ZDMAlbumAnimationModel, ZDMBanner, ZDMPageViewController, ZDMRouter, ZDMTabsRequest;

@interface YPZJHomeViewController : ZDMFullscreenViewController <UIScrollViewDelegate, ZDMPageViewControllerDelegate>
{
    _Bool _navigationItemConfigured;
    _Bool _pullsToNextTab;
    UIImageView *_preferencesTipsView;
    ZDMPageViewController *_pageViewController;
    NSDictionary *_parameters;
    NSString *_testId;
    NSString *_articleChannel;
    NSString *_isInstation;
    ZDMTabsRequest *_tabsRequest;
    ZDMBanner *_banner;
    ZDMBanner *_floatingBanner;
    ZDMAlbumAnimationModel *_animationModel;
    ZDMRouter *_router;
    JDImageView *_floatingImageView;
    NSLayoutConstraint *_bottomSpaceOfPreferencesTipsView;
    UIImageView *_tipsView;
}

@property(retain, nonatomic) UIImageView *tipsView; // @synthesize tipsView=_tipsView;
@property(retain, nonatomic) NSLayoutConstraint *bottomSpaceOfPreferencesTipsView; // @synthesize bottomSpaceOfPreferencesTipsView=_bottomSpaceOfPreferencesTipsView;
@property(retain, nonatomic) JDImageView *floatingImageView; // @synthesize floatingImageView=_floatingImageView;
@property(nonatomic) _Bool pullsToNextTab; // @synthesize pullsToNextTab=_pullsToNextTab;
@property(nonatomic) _Bool navigationItemConfigured; // @synthesize navigationItemConfigured=_navigationItemConfigured;
@property(retain, nonatomic) ZDMRouter *router; // @synthesize router=_router;
@property(retain, nonatomic) ZDMAlbumAnimationModel *animationModel; // @synthesize animationModel=_animationModel;
@property(retain, nonatomic) ZDMBanner *floatingBanner; // @synthesize floatingBanner=_floatingBanner;
@property(retain, nonatomic) ZDMBanner *banner; // @synthesize banner=_banner;
@property(retain, nonatomic) ZDMTabsRequest *tabsRequest; // @synthesize tabsRequest=_tabsRequest;
@property(retain, nonatomic) NSString *isInstation; // @synthesize isInstation=_isInstation;
@property(retain, nonatomic) NSString *articleChannel; // @synthesize articleChannel=_articleChannel;
@property(retain, nonatomic) NSString *testId; // @synthesize testId=_testId;
@property(retain, nonatomic) NSDictionary *parameters; // @synthesize parameters=_parameters;
@property(retain, nonatomic) ZDMPageViewController *pageViewController; // @synthesize pageViewController=_pageViewController;
@property(retain, nonatomic) UIImageView *preferencesTipsView; // @synthesize preferencesTipsView=_preferencesTipsView;
- (void).cxx_destruct;
- (void)showFocusTipsViewIfNeeded;
- (void)on:(id)arg1;
- (void)pageViewController:(id)arg1 didTransitionToViewController:(id)arg2;
- (void)scrollViewDidScrollToOffset:(struct CGPoint)arg1;
- (void)preferencesTipsViewTapped:(id)arg1;
- (void)floatingImageViewPanned:(id)arg1;
- (void)floatingImageViewTapped:(id)arg1;
- (void)imageViewTapped:(id)arg1;
- (void)setFullscreen:(_Bool)arg1;
- (_Bool)showAllWhiteBar;
- (void)handleFloatingImageView;
- (void)showLottieAnimation;
- (void)setupBarButtonItemsWithRequestInfo:(id)arg1;
- (void)requestTabs;
- (void)reconnect;
- (void)recordPV;
- (void)updateConstrainsOfiPhoneX;
- (void)dealloc;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithParameters:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

