//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface ZDMBanner : NSObject
{
    NSString *_identifier;
    long long _type;
    NSArray *_items;
    NSString *_bannerType;
    NSString *_backgroundImg;
    NSString *_title;
    NSString *_subTitle;
}

@property(retain, nonatomic) NSString *subTitle; // @synthesize subTitle=_subTitle;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSString *backgroundImg; // @synthesize backgroundImg=_backgroundImg;
@property(retain, nonatomic) NSString *bannerType; // @synthesize bannerType=_bannerType;
@property(copy, nonatomic) NSArray *items; // @synthesize items=_items;
@property(nonatomic) long long type; // @synthesize type=_type;
@property(copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void).cxx_destruct;
- (id)initWithDic:(id)arg1 type:(long long)arg2;

@end

