//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ZDMRequest.h"

@class NSString, ZDMArticle;

@interface ZDMNewAlbumDetailRequest : ZDMRequest
{
    NSString *_albumArticleIdentifier;
    ZDMArticle *_albumArticle;
}

@property(retain, nonatomic) ZDMArticle *albumArticle; // @synthesize albumArticle=_albumArticle;
@property(readonly, nonatomic) NSString *albumArticleIdentifier; // @synthesize albumArticleIdentifier=_albumArticleIdentifier;
- (void).cxx_destruct;
- (void)responseAlbumArticleDetails:(CDUnknownBlockType)arg1;
- (id)initWithSubmodule:(long long)arg1 albumArticleIdentifier:(id)arg2 parameters:(id)arg3;

@end

