//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class JDImageView, NSString, UIImageView, UILabel, ZDMTab;

@interface ZDMTabNewStyleView : UICollectionViewCell
{
    long long _tabStyle;
    long long _submodule;
    ZDMTab *_tab;
    JDImageView *_iconImageView;
    UILabel *_textLabel;
    UIImageView *_selectedMaskImageView;
    NSString *_defaultBackgroundColor;
    NSString *_defaultSelectedColor;
    long long _currentTabImageTextStyle;
}

@property(nonatomic) long long currentTabImageTextStyle; // @synthesize currentTabImageTextStyle=_currentTabImageTextStyle;
@property(retain, nonatomic) NSString *defaultSelectedColor; // @synthesize defaultSelectedColor=_defaultSelectedColor;
@property(retain, nonatomic) NSString *defaultBackgroundColor; // @synthesize defaultBackgroundColor=_defaultBackgroundColor;
@property(retain, nonatomic) UIImageView *selectedMaskImageView; // @synthesize selectedMaskImageView=_selectedMaskImageView;
@property(retain, nonatomic) UILabel *textLabel; // @synthesize textLabel=_textLabel;
@property(retain, nonatomic) JDImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
@property(retain, nonatomic) ZDMTab *tab; // @synthesize tab=_tab;
@property(nonatomic) long long submodule; // @synthesize submodule=_submodule;
@property(nonatomic) long long tabStyle; // @synthesize tabStyle=_tabStyle;
- (void).cxx_destruct;
- (void)config660UI;
- (void)config653UIWithBackgroundColors:(id)arg1;
- (void)updateViewWithSubmodule:(long long)arg1 tab:(id)arg2 backgroundColors:(id)arg3;
- (void)setupViewsWithTabImageTextStyle:(long long)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

